### ISSUE TITLE
[ECR] [request]:  batch-get-image does not return labels when imageDigest used instead of imageTag

### ISSUE THREAD

**Issue by CONJAUMCGCG** [aws/containers-roadmap#1075]
batch-get-image does return labels with --image-id imageTag=<tag_name> option.
But does not work if I pass --image-id imageDigest=<image_sha256> instead of the imageTag.
aws ecr batch-get-image --repository-name <repo_name> --image-id imageDigest=<image_sha256> --accepted-media-types "application/vnd.docker.distribution.manifest.v1+json" --output json |jq -r '.images[].imageManifest' |jq -r '.history[0].v1Compatibility' |jq -r '.config.Labels'

**Comment by jmahlik** [comment]
Fixing would benefit boto users as well. One can't make a request including both imageTag and imageDigest when using boto or the v1 json doesn't return. 

Example:
```
# This is what you get when doing ecr.list_images
imageIds = {'imageDigest': "a-digest", 'imageTag': 'a-tag'}

# Does not return v1 json if included so has to be delete out.
del imageIds["imageDigest"]

ecr.batch_get_image(
    repositoryName=repo_name,
    # Can't pass the imageDigest in the dict or get v2 json back
    imageIds=imageIds,
    acceptedMediaTypes=[
        "application/vnd.docker.distribution.manifest.v1+json"
    ],
)
```

**Comment by rpnguyen** [comment]
Manifest translation is only available when pulling by tag, not digest ([docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-manifest-formats.html)). If pulling by digest and a translation is performed, some clients will experience an error due to digest mismatch. What is the manifest format that the images were pushed as?
