### ISSUE TITLE
[Fargate] [How to]: Is it possible to add host entry to /etc/hosts file via Fargate 1.3.0 or 1.4.0?

### ISSUE THREAD

**Issue by poonamgp14** [aws/containers-roadmap#1076]
I need to add host entry to /etc/hosts file via Fargate. And, extraHosts via task-definition is not supported with awsvpc. Currently, we are using Fargate 1.3.0 and ready to upgrade to 1.4.0 if the issue can be resolved with 1.4.0.

Also, question asked here - https://github.com/aws/containers-roadmap/issues/886 suggests it is possible to do via 1.3.0 and 1.4 as well. And, I cannot seem to find either ways.

Can somebody suggest how it can be done?

**Comment by mreferre** [comment]
Hi @poonamgp14. Can you talk more about your use case and the need to add to `/etc/hosts`? 

I'll go first: I had a situation where my app needed to connect to another service via hostname only (e.g. not via a FQDN). Since ECS service discovery (which is what powers Fargate name resolution) only works with FQDN and you can't configure `/etc/resolv.conf` at the task level to add a search domain I came up with a workaround to inject the domain as a variable (SEARCH_DOMAIN) and then as part of the image startup script I did: 
```
if [ $SEARCH_DOMAIN ]; then echo "search ${SEARCH_DOMAIN}" >> /etc/resolv.conf; fi 
```

Could you use a similar workaround to manipulate `/etc/hosts`? 

We are looking at how to solve this more "natively" so if you can talk more about what you are trying to achieve that would help. 

Thanks.

**Comment by mreferre** [comment]
https://github.com/aws/containers-roadmap/issues/892

**Comment by lifeofguenter** [comment]
This definitely works in Fargate 1.4.0:

```
if ! getent hosts aws-es-proxy; then
  echo "" | tee -a /etc/hosts # add empty line as /etc/hosts on fargate does not end with one!
  echo "127.0.0.1 aws-es-proxy" | tee -a /etc/hosts
fi
```

(as part of your entrypoint.sh or so)

**Comment by dsalamancaMS** [comment]
> This definitely works in Fargate 1.4.0:
> 
> ```
> if ! getent hosts aws-es-proxy; then
>   echo "" | tee -a /etc/hosts # add empty line as /etc/hosts on fargate does not end with one!
>   echo "127.0.0.1 aws-es-proxy" | tee -a /etc/hosts
> fi
> ```
> 
> (as part of your entrypoint.sh or so)

This one works just fine, I just confirmed.

Also /etc/hosts is mounted as RW, so there shouldn't be any issues when writing to the file.

Which also confirms why the above works

**Comment by poonamgp14** [comment]
I have similar startup script running in fargate as mentioned below:
```
echo "172.28.19.203  $HOSTNAME_SW_NODES" >> /etc/hosts
if [ -n "$(grep $HOSTNAME_SW_NODES /etc/hosts)" ]
    then
        echo "$HOSTNAME_SW_NODES was added succesfully \n $(grep $HOSTNAME_SW_NODES /etc/hosts)";
    else
        echo "Failed to Add $HOSTNAME_SW_NODES, Try again!";
```
However, I still get the error
```
<urllib3.connection.HTTPSConnection object at 0x7fca1d205190>: Failed to establish a new connection: [Errno -2] Name or service not known
```
 It appears to me that there could be network connectivity issue since adding host entry through startup script seems to be a valid option.

**Comment by lifeofguenter** [comment]
@poonamgp14 output your complete `/etc/hosts` file during runtime after your modifications so you can 💯  verify it is correct/as expected.

In my case, at least for 1.4.0, I had to add an extra line-break before adding my stuff.

**Comment by ddyzhang** [comment]
Hi @poonamgp14, do you have any other questions/requests from AWS Fargate at the moment?

Do the workarounds and suggestions posted here work for your use-case?

Thanks!

**Comment by fprochazka** [comment]
Please, can we reopen this? I don't want to handle this in my entrypoint, why can't I configure it with Fargate?

**Comment by NicolasDAmelio** [comment]
> > This definitely works in Fargate 1.4.0:
> > ```
> > if ! getent hosts aws-es-proxy; then
> >   echo "" | tee -a /etc/hosts # add empty line as /etc/hosts on fargate does not end with one!
> >   echo "127.0.0.1 aws-es-proxy" | tee -a /etc/hosts
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (as part of your entrypoint.sh or so)
> 
> This one works just fine, I just confirmed.
> 
> Also /etc/hosts is mounted as RW, so there shouldn't be any issues when writing to the file.
> 
> Which also confirms why the above works

it doesn't work for me.
I get tee: / etc / hosts: Permission denied

How did you manage to modify etc / hosts? I am using PV 1.4 Fargate

**Comment by kevincianfarini** [comment]
My use case for altering `/etc/hosts` stems from a third party API requiring that all network requests originate from a whitelisted IP address. Given my teams infrastructure, it was easiest for us to set up an nginx proxy. 

Rather than issuing the networking request to the proxy IP itself and dealing with the SSL problems that would cause, we opted to go the `/etc/hosts` route. 

Right now, since fargate doesn't support amending the hosts file, we build a shell script which is run as part of our entrypoint which alters the host file on container creation. This feels fragile. 

```dockerfile

ARG nginx_proxy_host

RUN echo "echo ${nginx_proxy_host} some.host >> /etc/hosts" >> /tmp/update_hosts.sh
RUN chmod 777 /tmp/update_hosts.sh

USER root
ENTRYPOINT ["/bin/sh", "-c", "cat /tmp/update_hosts.sh && /tmp/update_hosts.sh && exec java -server -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:InitialRAMFraction=2 -XX:MinRAMFraction=2 -XX:MaxRAMFraction=2 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -jar some.jar"]
```

**Comment by marcin-xalgo-io** [comment]
Is it possible to do it as non-root user?

**Comment by landsman** [comment]
why is this not part of amazonlinux 2023 🤦

**Comment by BeyondEvil** [comment]
Why was this closed as completed when it's obviously not @SaloniSonpal ?

**Comment by JoshMcCullough** [comment]
FWIW, also need this. If for nothing else than to workaround temporary networking issues!
