### ISSUE TITLE
New EKS Region: Northern California

### ISSUE THREAD

**Issue by dgarbus** [aws/containers-roadmap#119]
We would really like to see the EKS service in us-west-1. As far as I can tell, EKS has been made available in other regions with only 2 AZs, so hopefully that is not a limiting factor here.

Thank you!

**Comment by thomasbarton** [comment]
It would be nice to see it on the roadmap under suggested at least so we know the AWS team is thinking about it.

Most of the other proposed EKS Regions are already on the roadmap

**Comment by lwoodson** [comment]
Agreed, we are bottlenecked on adopting EKS until its available in this region.

**Comment by mgalgs** [comment]
> As far as I can tell, EKS has been made available in other regions with only 2 AZs, so hopefully that is not a limiting factor here.

Out of curiosity, can anyone at Amazon comment on how you're achieving a highly-available etcd cluster in regions with only 2 AZs?  As I understand it you need nodes in 3 or more availability zones for your etcd cluster to be considered HA...

**Comment by farbodsafaei** [comment]
Is there a timeline/milestone for this? This has been open for more than a year and I am just curious if any progress been made for this. Thanks!

**Comment by jamesduffy** [comment]
Would love an update on this. We might just have to migrate regions if this isn't coming soon, but a timeline would be great so we can make that decision.

**Comment by abhineetraj** [comment]
Do you have a date when EKS will be available in N.California?

**Comment by talkimhi** [comment]
@mogren @tabern Any update on this?

**Comment by tabern** [comment]
We're continuing to work on this. No date to share, see https://github.com/aws/containers-roadmap#faqs. We'll be sure to move this up in the roadmap as we get close to launch.

**Comment by thomasbarton** [comment]
@tabern It is very frustrating to see many items breeze through the different container roadmap stages Researching, We're working on it, and Coming soon while this one has been stuck in `we're working on it` for over 7 months.

The idea of a container roadmap is great!  But the execution of it has been disappointing when items get stuck with no update or progress indicated.

**Comment by alexejk** [comment]
I think the problem for EKS is that N.Cal has only 2 AZs available for most customers. This means that the HA setup of 3 or more AZs isn't possible and I haven't seen another region with two AZs that supports EKS (I might've missed something).

I think the **main** problem is the N.Cal region in itself. We were forced to move away from it due to the time it takes to roll out  new AWS services there. In many cases it took several years (or 1000+ days) for "new" services to reach N.Cal after initial GA.

**Comment by thomasbarton** [comment]
@alexejk Thank you for that additional info.

My comment was not about the difficulties of implementing the solution.  My comment was about how AWS is communicating with the container roadmap.

If the container roadmap is going to be successful the definitions of the columns need to have meaning.  I understand that publicly committing to timelines is not possible as that would only lead to disappointment.  But i do think the roadmap would be much more successful if items that are in the `We're working on it` or `Coming soon` receive updates once every other month.  Most items wouldnt need updates as they breeze through the stages and are released quickly.  But the handful of hard items that take time, like this one, would benefit by having someone from AWS acknowledge that progress is being made.

Otherwise, the community is going to lose trust in the container roadmap.

I would prefer to see the container roadmap be a success :)

**Comment by clhlc** [comment]
+1

**Comment by yaronmz** [comment]
I agree, we also have important activity in the N. Cal. region and would really need EKS active there ASAP. Please provide updated regarding expected ETA. Please also promote Beta testing for EKS in this region if it can serve as an expedite option for using it in N. Cal. region.
Regards,
Yaron.

**Comment by akuksin** [comment]
Do you have any ETA when EKS expected to be available in N. California?

**Comment by rakesh-nd** [comment]
Any ETA on when EKS will be available in N. California ? Any of you guys running kubernetes yourself on ec2 ?

**Comment by mgalgs** [comment]
@rakesh-nd we ran a kops cluster in us-west-1 for a few years but it was never quite stable... Couldn't wait for eks any longer so we actually migrated to us-west-2 and our eks cluster up there has been extremely stable. I highly recommend moving regions if you need a production k8s cluster. I know it's a pain to move databases, etc. but seriously, it's worth it.

**Comment by rakesh-nd** [comment]
okay. Thank you so much for responding back @mgalgs !

**Comment by gaochundong** [comment]
+1

**Comment by lra** [comment]
Hey, I just noticed I can create an EKS in us-west-1 in the AWS console now. Does that mean we can start using it? Or should I treat it as unstable and expect it to go away in the future?

**Comment by mikestef9** [comment]
It's official!

https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-eks-now-available-n-california-region/
