### ISSUE TITLE
[ECS] How to programmatically get event "unable to place a task because the resources could not be found"

### ISSUE THREAD

**Issue by mattolenik** [aws/containers-roadmap#121]
I'm trying to get some event for when an ECS task fails to be placed, specifically when a task cannot be placed due to insufficient resources. I want [this event here to trigger a Lambda](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-event-messages.html#service-event-messages-1), which I can use to respond with scale-out actions.

I have tried listening to the [ECS Event Stream](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch_event_stream.html), but no event at all was triggered for task placement failure, the Lambda trigger never occurred. I also didn't see anything in CloudWatch logs for ECS at all.

Is there any way to receive notification of this event? We are able to alert on it in DataDog, how do they get it? Do we need to resort to polling?

**Comment by mtsr** [comment]
@toredash Unfortunately that SO solution only works if there is another AWS API Call on the service. New calls will get logged and will include the list of events that have happened on the service. But if you only ever do a CreateService, the service will silently fail to be placed.

**Comment by vimmis** [comment]
+1
Very useful especially when you don't have the liberty to add as many instances you like and allows better CICD checks.

**Comment by jespersoderlund** [comment]
Could also be a Cloudwatch metric "NumberOfUnschedulableTasks" or something similar. Makes it easy to integrate with scaling policies.

**Comment by kalpik** [comment]
> Could also be a Cloudwatch metric "NumberOfUnschedulableTasks" or something similar. Makes it easy to integrate with scaling policies.

This. Please! I don't want to have another lambda function just to catch this. Would be much better to have it exposed in CloudWatch, and then it can be internally supported by Cloudformtion.

**Comment by masneyb** [comment]
The best way that I found to automatically scale an ECS cluster with what AWS currently exposes publicly is to have a Lambda function publish a custom CloudWatch metric with the number of the largest containers that can currently be scheduled in the cluster. EC2 instance autoscaling is triggered off of this custom metric and always keeps enough room in the cluster to start at least one of the largest tasks in the cluster. More details, including the code are at https://techblog.realtor.com/a-better-ecs/ and https://github.com/MoveInc/ecs-cloudformation-templates/blob/master/ECS-Cluster.template.

I would love to see better integration between EC2 and ECS autoscaling so that a lot of this work won't be necessary.

**Comment by coultn** [comment]
Would this solution work?  https://github.com/aws/containers-roadmap/issues/76#issuecomment-485038973

**Comment by mhvelplund** [comment]
@toredash 
> Same scenario. Manual workaround is to use CW Events as described here:
> https://stackoverflow.com/questions/42394656/how-to-listen-for-an-insufficient-cpu-memory-event-in-an-aws-ecs-service

Other comments seem to indicate that this doesn't work for all cases. Have you implemented it with success?

**Comment by coultn** [comment]
FYI this launched recently:  https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-ecs-service-events-now-available-as-cloudwatch-events/

**Comment by Hackathon-G7** [comment]
Hi,
I am trying to Start/Stop EC2 say instance Id: B from Lambda based on CPU utilization of different EC2 Instance Id: A  e.g. 
1-EC2 - A CPU Utilization LT 20% - Stop EC2- B
2- EC2- A CPU Utilization GR 80% - Start EC2 - A
I tried CloudWatch Alarm but stop/start the same EC2 instance rather than different EC2 instance. I created Cloudwathc Rule to tridger Lambda from where I will Start/Stop EC2 instance(s) but Rule doesn't provide CPU Utilization based event triger rather on Scheduled Date/Time.
Do you have any experience or know any material/link where the similar work has been done. 
I will really appreciate your help and prompt response. 
Thanks
