### ISSUE TITLE
[EKS] [request]: Expose built in Prometheus Metrics from kube-scheduler & kube-controller-manager

### ISSUE THREAD

**Issue by jpmignon2** [aws/containers-roadmap#1298]
I have tried to installed the `kube-prometheus-stack` chart in my EKS environment and I am getting the error.
---
alert: KubeControllerManagerDown
expr: absent(up{job="kube-controller-manager"} == 1)

alert: KubeSchedulerDown
expr: absent(up{job="kube-scheduler"} == 1)
---
The other pods proxy, kubelet ... are monitored with success.
I have open a ticket on aws support and after test the support reply :
EKS does not have these metrics published. 
All the metrics you can get will be displayed based on Metric server responses.
EKS will monitor the health of Control Plane using its own internal mechanism.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
This could be Fargate, ECS, EKS, ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by sidewinder12s** [comment]
@mikestef9 Can you update the title of this to something like `Expose built in Prometheus Metrics from kube-scheduler & kube-controller-manager`?

**Comment by georgejohnis** [comment]
Closing the issue since metrics from kube-scheduler and kube-controller-manager are now available on EKS clusters Please see announcement details -

[What's new post](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-eks-kubernetes-control-plane-monitoring/)
[Blog](https://aws.amazon.com/blogs/containers/amazon-eks-enhances-kubernetes-control-plane-observability)
[EKS Docs](https://docs.aws.amazon.com/eks/latest/userguide/view-raw-metrics.html#fetch-metrics-prometheus)

If there are more metrics you would like to see from control plane, please feel free to open an issue and let us know 1\what metrics you need, 2\why you need them, and 3\how you plan to act on those metrics.
