### ISSUE TITLE
[ECS-Fargate] [request]: Fargate 1.4.0 not working with unauthenticated JFrog Artifactory

### ISSUE THREAD

**Issue by henriquesantanati** [aws/containers-roadmap#1302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Fargate 1.4.0 showing pull errors for unauthenticated JFrog Artifactory registry. Fargate 1.3.0 is working without any issues.

**Which service(s) is this request for?**
ECS-Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Fargate 1.4.0 showing the following error while trying to pull the image from an unauthenticated JFrog Artifactory registry:

```
CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "artifactoryserver.com:1": unexpected status code [manifests 1]: 401 Unauthorized 
```
I can see tasks running with Fargate 1.3.0 PV using the same task definition version (with the same image configuration). 

Checking the [Fargate 1.4.0 blog post](https://aws.amazon.com/blogs/containers/aws-fargate-launches-platform-version-1-4/) I can see that the dockerd was replaced by containerd. From containerd issues page, I'm able to see [this similar error](https://github.com/containerd/containerd/issues/2628).

Can you please check why Fargate 1.4.0 is not being able to pull the image from unauthenticated JFrog Artifactory registry while Fargate 1.3.0 is working fine?

**Are you currently working around this issue?**
Either run the task using Fargate 1.3 or push the image inside of ECR.

**Comment by estesp** [comment]
Can you provide the version of JFrog Artifactory you are using? Can you define "unauthenticated" (does this mean you have repositories for which pull is authorized with no credentials?)

**Comment by henriquesantanati** [comment]
Hi @estesp , I'll check the JFrog Artifactory version and I'll back to you. 

Regarding the second question, yes, without any Task definition auth parameter, using Fargate 1.3.0 the tasks were able to run without issue. From Fargate 1.4.0 they are showing the above error.

**Comment by alakesh** [comment]
I tried this experiment in absence of access to any jfrog registry at this moment.

- Created a private registry in ECR and pushed an image
- Logged into using docker login first
- Pulled it using docker cli [ no issue ]

`sudo ./bin/ctr image pull -u=AWS:$ECRPASS xxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/test-jfrog-issue:latest
xxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/test-jfrog-issue:latest:             resolved       |++++++++++++++++++++++++++++++++++++++|`

- Tried pulling it using ctr and i see this error message
`$ sudo ./bin/ctr image pull  xxxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/test-jfrog-issue:latest
    ctr: failed to resolve reference "xxxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/test-jfrog-issue:latest": unexpected status code [manifests latest]: 401 Unauthorized
    `

With the assumption that the registry needs authentication info to be provided, we see this discrepancy in behavior probably because **ctr** is not sending any authentication information [ 401 means no credential provided ].  Docker cli would do it differently, as it would read the credentials [ previously obtained with docker login ] from the credential store and use it, as can be verified from  **~/.docker/config.json**

If the above makes sense then to support same user experience, we need to add a feature like docker's credential store?

**Comment by henriquesantanati** [comment]
Thanks for checking this @alakesh . 

The task is running well with Fargate 1.3.0 platform version. So, I'm not sure how the Fargate can be able to use credential store since there is nothing inside of task definition informing the credentials. 

The issue is with regards the tasks running Fargate 1.4.0. 

Thanks in advance!

**Comment by dgoetsch** [comment]
:+1: Also having this issue, it appeared to start about 2 weeks ago. 

We were previously using fargate 1.4 (Since Mid-February 2021) in all of our services without an issue, but starting around March 6, 2021 we cannot start any tasks on fargate 1.4.0. The task began failing to start after it exited due to an error and was restarted by service.

I noticed the same behavior in the week leading up to March 6, 2021.  I was working on a scheduled task, and it would fail at least once with every invocation.  When scheduling the evening of March 8, it missed a handful of executions when run for more than 24 hours.

Then, at the end of that week (March 12, 2021) we noticed some services begin to fail to come up at all, and the services would just continually thrash.  Changing the platform version resolved these issues.  Today I selected another random service we host in ecs to attempt to run at 1.4 and it failed in the same way.

Artifactory Version: 7.10.2 rev 71002900

**Comment by alakesh** [comment]
Can anyone provide any pointers about where i can get an unauthenticated registry to test docker vs containerd case?

**Comment by dgoetsch** [comment]
I assume you should be able to host artifactory pretty simply: https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory

It looks like the container registry is free: https://jfrog.com/container-registry/

**Comment by alakesh** [comment]
I setup one anonymous registry in Jfrog and ran a pull using docker vs containerd and both worked for me without giving any 401 errors. While we may not scoped out the actual issue here, but this seems interesting.

Unauthenticated registry created:
mybigfatfrog.jfrog.io/docker-repository-alakesh

Using containerd    [  using code with latest commit sha ddf6594fbeeddf30a55e0d2bcdb85956ec792fd2 ]


This host does not have docker installed
```
$ sudo ./bin/ctr image pull  mybigfatfrog.jfrog.io/docker-repository-alakesh/hello-world:latest
mybigfatfrog.jfrog.io/docker-repository-alakesh/hello-world:latest:               resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:1b26826f602946860c279fce658f31050cff2c596583af237d971f4629b57792: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:d1165f2212346b2bab48cb01c1e39ee8ad1be46b87873d9ca7a4e434980a7726:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:b8dfde127a2919ff59ad3fd4a0776de178a555a76fff77a506e128aea3ed41e3:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 3.6 s                                                                    total:  4.0 Ki (1.1 KiB/s)
unpacking linux/amd64 sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24...
done: 0.0 s

```

Using Docker

```
[00:13]ubuntu@ip-172-31-3-237:~$ docker pull mybigfatfrog.jfrog.io/docker-repository-alakesh/hello-world:latest
latest: Pulling from docker-repository-alakesh/hello-world
Digest: sha256:308866a43596e83578c7dfa15e27a73011bdd402185a84c5cd7f32a88b501a24
Status: Downloaded newer image for mybigfatfrog.jfrog.io/docker-repository-alakesh/hello-world:latest
mybigfatfrog.jfrog.io/docker-repository-alakesh/hello-world:latest
```

**Comment by dgoetsch** [comment]
@alakesh do you know what version of containerd runs in fargate?  So far, we've only observed this in a fargate instance, but we can't reproduce either (with containerd 1.3.3)

**Comment by Lefthander** [comment]
@dgoetsch 
for my case it is: Amazon Linux 2   4.14.209-160.339.amzn2.x86_64   containerd://1.4.1

**Comment by ssayala** [comment]
We tried with Artifactory 7.15.3 and were unable to repro.

“version” : “7.15.3"
“revision” : “71503900"

**Comment by alakesh** [comment]
> 👍 Also having this issue, it we first observed it about 2 weeks ago.
> 
> We were previously using fargate 1.4 (Since Mid-February 2021) in all of our services without an issue, but starting around March 6, 2021 we cannot start any tasks on fargate 1.4.0. The task began failing to start after it exited due to an error and was restarted by service. At this point in time I didn't think much of it.
> 
> I noticed the same behavior in the week leading up to March 6, 2021. I was working on a scheduled task, and it would fail at least once with every invocation. When scheduling the task to run throughout the evening of March 8, it missed a handful of executions.
> 
> Then, at the end of that week (March 12, 2021) we noticed some services begin to fail to come up at all, and the services would just continually thrash. Changing the platform version resolved these issues. Today I selected another random service we host in ecs to attempt to run at 1.4 and it failed in the same way.
> 
> Artifactory Version: 7.10.2 rev 71002900

Artifactory Version 7.10.2 is apparently not OCI compliant. Version 7.11.1+ seemed to be OCI compliant. Not sure if this is related to that but is it possible to upgrade your artifactory to latest version and see if you still experience the issue with fargate 1.4?

**Comment by dgoetsch** [comment]
I was digging into this on a call with some of your teammates @alakesh, we had previously only seen this in us-east-1, where we have artifactory version 7.10 running.  In other regions we have version 7.12.x running.   We suspected the fix was related to the OCI fix in version 7.11.1.

On the call we deployed to another region (where the version with the compliance fix is deployed), but it failed in the same way as the one in us-east-1 - which kind of blew our artifactory theory out of the water. 

We also tried duplicating the direct containerd pull with version 1.3.7 against our repo and were also unable to reproduce.

No update yet on when we can try to upgrading - I need to work internally with the teams that manage that stack, but right now its seeming that artifactory may have been a red herring.

**Comment by alakesh** [comment]
> I was digging into this on a call with some of your teammates @alakesh, we had previously only seen this in us-east-1, where we have artifactory version 7.10 running. In other regions we have version 7.12.x running. We suspected the fix was related to the OCI fix in version 7.11.1.
> 
> On the call we deployed to another region (where the version with the compliance fix is deployed), but it failed in the same way as the one in us-east-1 - which kind of blew our artifactory theory out of the water.
> 
> We also tried duplicating the direct containerd pull with version 1.3.7 against our repo and were also unable to reproduce.
> 
> No update yet on when we can try to upgrading - I need to work internally with the teams that manage that stack, but right now its seeming that artifactory may have been a red herring.

Few questions:
a. How many tasks need to run to reproduce this issue? Does it consistently happen with single task as well or you see a pattern with increasing number of tasks?
b. Is there a test repo accessible somewhere that shows this issue consistently using Fargate? That would be very helpful to test/debug and would rule out any config related differences.

**Comment by dgoetsch** [comment]
We saw it with just a single task, it had 4 containers.

I'll work today on a minimal cfn stack that I can share that will duplicate the problem.

**Comment by dgoetsch** [comment]
I think we have an explanation for this behavior. At least, I can explain what happened in my organization.

There's been a number of folks looking into this on our end, and we've come up with an explanation. Some images fail to pull because containerd is a bit pickier when it comes to receiving an unexpected sha.  We see the docker pull work with animage, but fail with containerd for the same image.  The issue is 100% reproducible once you find a bad image.

```
tr: failed commit on ref "manifest-sha256:XXX": commit failed: unexpected commit digest sha256:YYY, expected sha256:XXX failed precondition
```

And it looks like there is an issue that jfrog is aware of: 
https://www.jfrog.com/jira/browse/RTFACT-23923  
https://www.jfrog.com/jira/browse/RTFACT-23767
https://www.jfrog.com/jira/browse/RTFACT-23899

On our end, we are able to work around this issue by updating / changing container versions, but i'm not sure when we'll run into another one.  We are also trying an update to artifactory.

Hopefully this helps anyone else who runs into this issue!

**Comment by alakesh** [comment]
@dgoetsch, Thanks for your update!  Just want to make sure that with the workarounds in place, you are not getting error like this anymore. Can you please confirm?

"CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "artifactoryserver.com:1": unexpected status code [manifests 1]: 401 Unauthorized "

**Comment by dgoetsch** [comment]
Hmmm, maybe this is a slightly different issue.  We never had the specific "401" message from artifactory - just messages about the sha and the HEAD request.

**Comment by henriquesantanati** [comment]
Closing this since it seems to be related with Artifactory Server.
