### ISSUE TITLE
[EKS] [Terraform : Windows managed node group implementation ]: adding vpc controller and linux managed instance before setting up the windows node group helps launching managed windows node group

### ISSUE THREAD

**Issue by paramanandd** [aws/containers-roadmap#1335]
we have managed eks cluster the process we follow to launch the managed windows node groups is below:

1. Setup control plane
2. setup Linux node group (Managed)
3. Setup vpc-controller
4. setup auth configmap for linux and windows nodes
4. setup launch template with windows ami and userdata to register in cluster
5. create managed node group with launch template 

This registers the windows nodes with cluster and we are abe to launch windows pods

is there a issue in this process which we can face in future?

**Comment by kylzhng1** [comment]
I see no issues with this process, step 4 is important since when following a custom Launch template route, MNG will not automatically apply the auth configmap changes required for windows to work, thus we call it out here https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html 
under "Limits and conditions when specifying an AMI ID"

**Comment by goyalpurvi** [comment]
Hi @paramanandd please let us know if this is still an issue, and feel free to reopen it.

> Hi @paramanandd ,
> 
> I see no issues with this process, step 4 is important since when following a custom Launch template route, MNG will not automatically apply the auth configmap changes required for windows to work, thus we call it out here https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html under "Limits and conditions when specifying an AMI ID"
