### ISSUE TITLE
[EKS]: IAM Roles for Service Accounts enhancements for usage across multiple clusters

### ISSUE THREAD

**Issue by mikestef9** [aws/containers-roadmap#1408]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
IAM Roles for Service Accounts ([IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html)) enables you to associate an IAM role with a Kubernetes service account, and follow the principle of least privilege by giving pods only the AWS API permissions they need, without sharing permissions to all pods running on the same node. This feature works well with a smaller number of clusters, but becomes more difficult to manage as the number of EKS clusters grows, notably:

* Needing to create an IAM OIDC provider for each cluster
* Updating the trust policy of every IAM role needed by that cluster with cluster’s OIDC provider URL that maps to a particular namespace and service account name. 
    * Given the 2048 character [limit](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#reference_iam-quotas-entities) of IAM trust policies, only around 5 clusters can be trusted per role. 
    * After 5 clusters, you need to duplicate IAM roles to be used by additional clusters.
    * Coordination between devs and admins - Development teams that own IAM roles often need to re-run Terraform apply or CloudFormation scripts to update trust policies for new clusters.

Given these pain points, EKS is considering a change to the way IRSA works, moving credential vending to the EKS control plane (similar to how [ECS](https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-iam-roles.html) and [Lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html#permissions-executionrole-least-privilege) works). With this change, a trust policy would only need to be updated once to trust a service principal like `eks-pods.amazonaws.com`, then you would call an EKS API to provide the IAM role to service account mapping, ex.

```
aws eks associate-role \
    --cluster-name $CLUSTER_NAME \
    --role-arn $ROLE_ARN \
    --namespace $KUBERNETES_NAMESPACE \
    --service-account $SERVICE_ACCOUNT 
```

We are looking for your feedback on this proposal, and to hear any additional pain points encountered with IRSA today that would not be solved by such a solution.

**Are you currently working around this issue?**
Creating and managing duplicate roles to be used across multiple clusters

**Comment by gregoryfranklin** [comment]
This would be very useful as it is definitely a problem we run into.

Would this work cross-account?  We often associate service accounts with roles in accounts other than the one in which EKS is running.

**Comment by ajohnstone** [comment]
@mikestef9 thanks for raising this.

When running large clusters/platforms on top of AWS and requiring IAM there are a few more constraints than just the trust relationship payload size. 

1. Each AWS account has a hard limit of 5000 IAM roles per account. With the above it would be ideal to not be bound by a single accounts hard limit and to allow cross account assume roles. Running a multi-tenant workload can quite easily consume this limit with a few thousand deployments. 

Given large numbers of IAM roles typically it would be advisable to use Temporary security credentials in IAM.

2. Do you have more details around the implementation of this? E.g. Would this require aws-sdk changes to the credential provider chain and therefore a bump for all tenants using AWS SDKs?

3. How would you limit the trust relationship to a single or group of clusters?

4. Would there be any caveats/gotchas that would need to consider as part of this proposal?

**Comment by mikestef9** [comment]
@gregoryfranklin yes we plan to make cross account roles work with this proposal.

@ajohnstone we haven't settled on implementation yet. One idea is to use a CSI driver to retrieve a pod’s OIDC token from the Kubelet and exchange the token for IAM Role credentials from EKS. Another is a new credential provider in all AWS SDKs, but that would be hampered by requiring all clients to update. 

You manage trust through the EKS API now. The IAM trust policy only is updated once to trust the EKS service principal.

**Comment by phillebaba** [comment]
This might solve a challenge I am currently having with IRSA. There are situations where I have to replace an existing cluster with a new one and then shift traffic to the new cluster, either due to disaster recovery or a change which cant be applied without downtime. Currently this would require all developers to update their trust policy with the new OIDC provider, so that the applications can authenticate from the new cluster.

Would this new solution require all roles to be associated with the new cluster or could that be solved somehow when replacing a cluster?

**Comment by mikestef9** [comment]
You would still need to call the EKS API to add the mapping, but this can be automated using IaC tools as part of the new cluster creation process. There would be no need to update a role trust policy when creating a new cluster, and you no longer run into trust policy character limits when you need a role associated with many clusters.

**Comment by phillebaba** [comment]
It sounds like we would still have the same issues as we do today. In my scenario individual development teams setup their own resources and IAM roles with Terraform, this is a separate state from the one which creates the cluster. The manifests are deployed with FluxCD into the cluster. This enables us to replace a cluster over night without any development team being the wiser as the new cluster will pull down the same manifests as the old one does. The issue here today is that each development team would have to update the OIDC provider in their trust policy.

Correct me if I am wrong but it sounds like there is still a need in the new proposed solution for each team to associate their IAM roles with service accounts in the new cluster. Basically keeping the same issue that we have today but solved with a different IaC resource.

**Comment by gregoryfranklin** [comment]
> Correct me if I am wrong but it sounds like there is still a need in the new proposed solution for each team to associate their IAM roles with service accounts in the new cluster. Basically keeping the same issue that we have today but solved with a different IaC resource.

If teams are creating the IAM roles with terraform, can they not lookup the cluster id using a data source?

We store the current list of OIDC providers in an SSM parameter when we create a cluster.  Terraform is therefore able to lookup the appropriate IDs in order to generate the policy.
The same appears to be true with the new proposal, but instead of needing to template the trust policy there would just be a new resource type to create the mapping.  The cluster name parameter would change each time the cluster is re-built but its a lot easier to just lookup the value for that single parameter than template the trust policy.

**Comment by mikestef9** [comment]
With this proposal, yes there would be an EKS API call to make for each cluster instead of a trust policy update. Additionally, there would no longer be a need to annotate a service account with the IAM role Arn.

So is what you are looking for more along the lines of some way to trust an IAM role for all clusters in an account, without having to specify each cluster?

**Comment by phillebaba** [comment]
@mikestef9 yeah that is basically it. I do not want to have to inform development teams to rerun their Terraform if I replace the cluster. It would be nice to either configure trust to an account of some sort of regex pattern for the cluster name.

**Comment by sidewinder12s** [comment]
If a CSI Driver is used, I hope it's not a daemonset. We're quickly running into issues with the number of daemonsets we need to run on nodes that consume resources we can then not use to run workloads (currently at about 7 per node). At large cluster sizes, this is not insignificant where you might end up with 10k workload pods and 28k daemonset pods. If using the vpc-cni-plugin and IP allocations out of a VPC, it's even worse since now you're consuming potentially scarce IPs.

We've also run into the trust policy size limits already.

Talking from personal experience of dealing with both the AssumeRoleWithWebIdentity & AWS SSO default credential provider chain updates to multiple language SDKs: It is a nice long term change but actually doing it was an absolute nightmare. None of the AWS SDK teams coordinate their work when service teams add new methods leaving all customers in the lurch to deal with it. When you are dealing with 100s of devs and multiple languages this was a giant time sink that AWS was not helpful with.

**Comment by xavipanda** [comment]
This is a must.
In the way it is right now, 1 policy ~400bytes, assume role max policy size 4096bytes. 9clusters are enough to reach this limit.
* IAM Variable interpolations for EKS/OIDC --> inexistent
* Length of the ARN -> Gigantic
* Length of OIDC URL -> Gigantic

IMHO, i can't label the today integration.. where EKS elements are treat as a foreign element of AWS as "production-grade".
Even if we produce 1 role per cluster, we will hit max roles... or max policies, or max attachments..

Does anyone knows a workaround, besides producing resource roles (nodes, cluster, etc) where everyone can access everyone else AWS resources.. ??

**Comment by SQUIDwarrior** [comment]
Yes we also just read head first into the 4096 character IAM policy size limit trying to scale out by adding more clusters. And we're basically stuck right now until we can do something about this.

**Comment by tomthetommy** [comment]
I've also just ran into this issue. So this is a thumbs up from me!

**Comment by javanthropus** [comment]
My team uses ClusterAPI to manage clusters in AWS right now, and we've been discussing an option that does not require any changes to IRSA which some here may find helpful.  The general idea is to run all the clusters under a single trust domain or identity provider.  The big requirement is that you ensure that namespaces are managed the same way in all clusters under the trust domain.  There will be no way for IRSA to distinguish between same named namespaces in clusters under the trust domain.

Configure the clusters to use the same service account issuer.  You have the option to also make them all use the same signing key, but that's not a requirement.  The service account issuer string needs to be a URL that can serve the OIDC discovery documents publicly, such as S3.  You also need to set the service account jwks URI to point into the same location.  This will ensure that the `.well-known/openid-configuration` file generated by the cluster is correctly configured to point to the `openid/v1/jwks` file.

Extract the discovery documents from the clusters.  The `.well-known/openid-configuration` file should be the same for all of them.  Merge the `openid/v1/jwks` files together.  Then copy them to S3 or wherever they need to be hosted to satisfy the issuer URL.  In order to merge the jwks files, concatenate the arrays at `.keys` together and emit the result as JSON.  Note that as you add clusters to and remove clusters from the trust domain, the jwks file will need to be updated accordingly, either adding or removing keys from the array.  We're still working out exactly how we plan to do this via automation.

Merging the jwks files is only necessary if you continue use cluster specific signing keys, which we recommend since that allows you to evict individual signing keys from the trust domain without affecting other clusters.  If you use the same signing key for all clusters though, then you need only copy the OIDC discovery documents from one of the clusters to the hosting solution since all clusters will have identical documents.  You also never need to update the jwks file again as you add and remove clusters under the trust domain.  Buyer beware on this!

Once all of that is set up, you can define a single IAM OIDC provider to represent the trust domain.  Point it to the endpoint you set up for hosting the OIDC discovery documents.  Now create IAM roles as usual using the new provider.  All workloads running in clusters under the same trust domain will be able to use the roles as if they run under a single cluster.  Note the point about namespace handling mentioned earlier.

It would be great if EKS allowed the service account issuer to be specified because then this same solution could be used.

**Comment by GaruGaru** [comment]
I share the same concerns that @phillebaba has expressed: even following IaC best practices updating all the roles trust policies after that a new cluster is provisioned can be pretty complex at scale.
As others have stated before, this is a pretty big limitation for disaster recovery/migration scenarios and also for overall scalability of the IRSA system.

EKS clusters should be able to rely on a **shared OIDC provider**, or users should be able to apply more dynamic trust policies to IAM roles.
Having a shared identity provider would allow active-active or active-passive type cluster deployments to be provisioned 
transparently while being able to enforce tier/env based trust policie (eg. `prod` - `test` - `dev` )  without the current scalability issues.

**Comment by valorl** [comment]
We are in the same situation as @phillebaba and @GaruGaru and would love for it to be possible for a given SA in _any_ cluster in the account to assume the IRSA role automatically, whether that is using a shared OIDC provider, or a more flexible (wildcard) trust policy syntax. It's crucial to be able to do blue/green cluster failovers without a highly coupled, hard-to-scale IaC setup.

**Comment by chaospuppy** [comment]
The solution shared by @javanthropus seems to solve the problem as it’s been stated, albeit with a extra few steps such as creating the .well-known/openid-configuration and associated jwks, and then building a method of  retrieving the public key half of the service account signing key from EKS control planes to place in the jwks if you want a unique signing key per cluster (which is optimal from a security and management perspective).  

Currently I’m not entirely sure it is possible to get the public key portion of the signing key from EKS control planes, or using user-managed keys as SA token signing keys.  Enabling the retrieval of that information via the AWS API would make this solution possible today.

For reference, the pod-identity-webhook repository does [document](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md) all the steps needed for creating a provider independently of an EKS cluster.  I also have a [POC repository](https://github.com/chaospuppy/irsa-demo) demonstrating how to generate a signing keypair and use it as the signing key, as well as some IaC to leverage this setup (granted, this was done using RKE2, not EKS, because there’s no obvious way to get the public key from EKS).

**Comment by valorl** [comment]
> With this proposal, yes there would be an EKS API call to make for each cluster instead of a trust policy update. Additionally, there would no longer be a need to annotate a service account with the IAM role Arn.

@mikestef9 Any chance you'd be ready and willing to share some more details/design around how this is going to work ?

**Comment by jansony1** [comment]
Any update about this feature? Thanks

**Comment by blowfishpro** [comment]
> Instead of calling the EKS API (We have 30+ roles per cluster), can we keep the annotation for the same effect?

This would have some potentially problematic security implications wouldn't it?  If you have permission within kubernetes to modify service accounts in any namespace in any cluster, you could grant access to assume that role.  Something outside the cluster needs to be able to restrict but cluster/namespace at least.

**Comment by DanielMcAssey** [comment]
> > Instead of calling the EKS API (We have 30+ roles per cluster), can we keep the annotation for the same effect?
> 
> This would have some potentially problematic security implications wouldn't it? If you have permission within kubernetes to modify service accounts in any namespace in any cluster, you could grant access to assume that role. Something outside the cluster needs to be able to restrict but cluster/namespace at least.

Fair point, I hadn't thought of that, just thinking of a way to automate this for all our regional clusters

**Comment by kr3cj** [comment]
I'm curious if the new EKS Pod Identity Associations are intended to be part of the solution for this.
* [EKS Pod Identity Assocations](https://github.com/eksctl-io/eksctl/pull/7313/files#diff-189f62d691100052f17770bc7d2633d8c2b87b45bb55a9c7a58fb07a86b48490)
> As a result, IAM roles no longer need to reference an [OIDC provider](https://github.com/eksctl-io/eksctl/blob/e365a89db24ed3739a5d8ac9c655576bf222926e/usage/iamserviceaccounts/#how-it-works) and hence won't be tied to a single cluster anymore.

**Comment by claytonolley** [comment]
Is it worth running yet another daemonset I wonder? 🤔

> Behind the scenes, the implementation of pod identity associations is running an agent as a daemonset on the worker nodes.

**Comment by sidewinder12s** [comment]
And no support for cross-account roles likely requiring application code changes.

**Comment by georgejohnis** [comment]
Closing this issue since EKS announced enhancements to IAM Roles for Service Accounts. Please see details -

    [What's new post](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-eks-pod-identity/)
    [EKS Blog](https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/)
    [EKS Documentation](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html)
    
Feel free to open a separate issue if there are  enhancements/feedback for EKS Pod Identity.

**Comment by project0** [comment]
From the docs it is not really clear to me if this is gonna work in a cross-account scenario. Did someone test it already or can give more clarity here?

**Comment by georgejohnis** [comment]
> From the docs it is not really clear to me if the pod identity feature is gonna work in a cross-account scenario. Did someone test it already or can give more clarity here?

Thank you for the feedback. EKS Pod Identity works cross account scenario. We are in the process of updating EKS user guide to give more clarity on this. We are targeting for the updates to be available in user guide next week or so.

**Comment by georgejohnis** [comment]
> Thank you for the feedback. EKS Pod Identity works in cross account scenario. We are in the process of updating EKS user guide to give more clarity on this. We are targeting for the updates to be available in user guide next week or so.

While the EKS user guide is getting updated, we published a deep dive blog post ([link](https://aws.amazon.com/blogs/containers/amazon-eks-pod-identity-a-new-way-for-applications-on-eks-to-obtain-iam-credentials/)) that covers multiple cross account scenarios.

**Comment by Anomander** [comment]
We use IRSA to provide IAM roles to workloads in a shared cluster. Tenants provision roles in their accounts and we attach them to their containers to appear on startup, akin to an EC2 instance role.

I wouldn't call any of the two currently available modes "cross-account" support. Now, instead of OIDC providers, the tenants need to fill the trust policy of their roles with all these external roles from EKS clusters' accounts, leading to the repeat of the original limitation that spawned this issue.

**Comment by georgejohnis** [comment]
> We use IRSA to provide IAM roles to workloads in a shared cluster. Tenants provision roles in their accounts and we attach them to their containers to appear on startup, akin to an EC2 instance role.
> 
> I wouldn't call any of the two currently available modes "cross-account" support. Now, instead of OIDC providers, the tenants need to fill the trust policy of their roles with all these external roles from EKS clusters' accounts, leading to the repeat of the original limitation that spawned this issue.

If EKS was to extend the [CreatePodIdentityAssoscation()](https://docs.aws.amazon.com/cli/latest/reference/eks/create-pod-identity-association.html)  with an additional parameter, that takes  the tenants role as input would it meet your needs? 
So, something like the below - 

`  create-pod-identity-association
--cluster-name <value>
--namespace <value>
--service-account <value>
--role-arn <role-a>
--target-role-arn <role-b>`

role-a exists in the shared cluster AWS account. role-b is the tenant's AWS account.

Once you create the above association, during runtime, the pods would be automatically injected wth the temp AWS  AWS credentials of role-b, without the need for the application/SDKs to do the (double) role assumption. Would that meet your requirement?

**Comment by cspargo** [comment]
we have similar challenges for cross-account. I think that that suggestion would work for us. It's the double role assumption that is most problematic for us.

**Comment by johngmyers** [comment]
The need to provision an extra role in the cluster's AWS account would make this more troublesome to administer than the OIDC-provider mechanism. Tenants typically have privileges to provision IAM roles into their own AWS accounts, but not into the cluster's AWS account.

So we would continue to consider CreatePodIdentityAssociation() to be non-useful.

**Comment by sidewinder12s** [comment]
Double assumptions also expose people to the chained role assumption hard 1h TTL which I've had to work around/caused issues many times.

**Comment by Anomander** [comment]
> @Anomander If EKS were to extend the [CreatePodIdentityAssoscation()](https://docs.aws.amazon.com/cli/latest/reference/eks/create-pod-identity-association.html) with an additional parameter, that takes the tenants role as input would it meet your needs? So, something like the below -
> 
> ` create-pod-identity-association --cluster-name <value> --namespace <value> --service-account <value> --role-arn <role-a> --target-role-arn <role-b>`
> 
> `role-a` exists in the shared cluster's AWS account. `role-b `is the tenant's AWS account.
> 
> Once you create the above association, during runtime, the pods would be automatically injected with the temp AWS AWS credentials of role-b, without the need for the application/SDKs to do the (double) role assumption. Would that meet your requirement?

What goes into the trust policy of `role-b`? Currently, the major problems for us are not in the plumbing of the role to the pod (a simple annotation on the service account), but the setup we have to do on the tenant's side:
1. Fetch OIDC provider info for each cluster
1. Import OIDC provider for each cluster
1. Add OIDC provider information into role's trust policy
1. Run out of room in the trust policy and fail

If the plan is to put `role-a` into the trust policy, it's not much of an improvement (saves only the need to import OIDC) and still runs into the same constraints.

Additionally, as for @johngmyers, provisioning a role for each unique service account on the platform side is untenable and will quickly run into the 5000 role limit.

**Comment by johngmyers** [comment]
We tend to provision a role per <cluster, serviceaccount> tuple, so that we can scope the permissions to only those resources that need to be accessed by the particular cluster. Unfortunately, the AWS-provided policies aren't good at limiting scope like this.

We maintain a Terraform module which keeps and distributes the mapping from cluster names to ODIC provider paths. That and the need to provision exactly one OIDC provider resource per <cluster, tenant-account> tuple are inconveniences.

As we use a Kustomize-based technology for managing configuration of the `role-arn` annotation and Kustomize doesn't support interpolation of values, the lack of aws/amazon-eks-pod-identity-webhook#95 is particularly troublesome.

**Comment by bryantbiggs** [comment]
> We tend to provision a role per <cluster, serviceaccount> tuple, so that we can scope the permissions to only those resources that need to be accessed by the particular cluster. Unfortunately, the AWS-provided policies aren't good at limiting scope like this.

I believe the [session tags](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-abac.html#pod-id-abac-tags) supported by Pod Identity would help alleviate the need for this, correct?

**Comment by johngmyers** [comment]
> I believe the [session tags](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-abac.html#pod-id-abac-tags) supported by Pod Identity would help alleviate the need for this, correct?

Does the recommended node role permission restrict what the node can pass as a value for that session tag? Or could someone obtaining node role credentials for one cluster access resources owned by a different cluster by passing the other cluster's name in the session tag when making a AssumeRoleForPodIdentity call?

Without these session tags being supportable in self-managed clusters, it's unlikely that the recommended IAM policies for the various workloads would make good use of them.

If a policy uses the `eks-cluster-name` tag instead of the `eks-cluster-arn` tag, it could possibly be subverted by a cluster with the same name but in a different account.

**Comment by bryantbiggs** [comment]
its not the node IAM role that is involved in this, its the EKS auth API 

> EKS Auth API (AssumeRoleForPodIdentity) decodes the JWT token and validates the role associations with the service account. After successful validation, EKS Auth API will return the temporary AWS credentials. It will also set session tags such as kubernetes-namespace, kubernetes-service-account, eks-cluster-arn, eks-cluster-name, kubernetes-pod-name, kubernetes-pod-uid.

You can see more about session tags [here](https://aws.amazon.com/blogs/containers/amazon-eks-pod-identity-a-new-way-for-applications-on-eks-to-obtain-iam-credentials/#support-for-session-tags) along with an example policy

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AuthorizetoGetSecretValue",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "secretsmanager:ResourceTag/kubernetes-namespace": "${aws:PrincipalTag/kubernetes-namespace}",
                    "secretsmanager:ResourceTag/eks-cluster-name": "${aws:PrincipalTag/eks-cluster-name}"
                }
            }
        }
    ]
}
```
