### ISSUE TITLE
Failing to pull image due to Rate Limit

### ISSUE THREAD

**Issue by vigneshraaj** [aws/containers-roadmap#1462]
/kind bug

**What happened?**
When upgraded to the latest version, the pods are not getting started

**What you expected to happen?**
efs-csi-node Pods are running successfully.

**How to reproduce it (as minimally and precisely as possible)?**
```
helm -n kube-system upgrade aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver
kubectl -n kube-system get pods -l "app=efs-csi-node"
```

**Anything else we need to know?**:
We have around 20+ nodes running on that cluster.
It's throwing the following error.
```
  Normal   Pulling    3m39s (x3 over 4m24s)  kubelet            Pulling image "amazon/aws-efs-csi-driver:v1.3.2"
  Warning  Failed     3m39s (x3 over 4m24s)  kubelet            Failed to pull image "amazon/aws-efs-csi-driver:v1.3.2": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning  Failed     3m39s (x3 over 4m24s)  kubelet            Error: ErrImagePull
  Normal   BackOff    3m14s (x5 over 4m23s)  kubelet            Back-off pulling image "amazon/aws-efs-csi-driver:v1.3.2"
  Warning  Failed     3m14s (x5 over 4m23s)  kubelet            Error: ImagePullBackOff
```
https://www.docker.com/increase-rate-limit - Is this a free account?

**Environment**
- Kubernetes version (use `kubectl version`): v1.21
```
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T00:59:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: 1.3.2
- Helm Chart version: aws-efs-csi-driver-2.1.4

**Comment by dcherman** [comment]
(Not an employee of AWS, just a drive by comment)

That image that you're pulling is coming from DockerHub which has rate limits in place for anonymous pulls.  This isn't something that AWS can really control.  I'll bet AWS has provided images there for backwards compatibility, but their official install guide mentions using images from ECR which will not be subject to those problems.

https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html#efs-install-driver

**Comment by toricls** [comment]
You can use the EFS CSI driver image stored in ECR by AWS instead of the images in Docker Hub.

Just use `602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.3.2` for `us-west-2` region for example, by overriding the [Helm chart values](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/helm-chart-aws-efs-csi-driver-2.1.4/charts/aws-efs-csi-driver/values.yaml#L10-L12) with either one of the [`--values` flag or `--set` flag](https://helm.sh/docs/helm/helm_upgrade/).

Note that the `602401143452.dkr.ecr.us-west-2.amazonaws.com` part above depends on the AWS region you're using, so see also the EKS [official documentation](https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html) to find one :)
