### ISSUE TITLE
[EKS] [request]: Allow managed worker nodes to be two versions behind

### ISSUE THREAD

**Issue by bnutt** [aws/containers-roadmap#1473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently you cannot upgrade the EKS API server if your managed node groups are not at the same version of the API server you are currently running. For example, if you are using EKS API 1.18, but the managed worker nodes still use 1.17, you cannot upgrade the API server to 1.19. While this is likely for the sake of guaranteeing stability while using a managed service, it makes cluster upgrades more time consuming as you always need to upgrade all node groups to be at least the same version of the API. With self-managed nodes, you have the option to at least allow the worker nodes to be two API versions behind the API server so that you can upgrade directly to the version of the API server. This aligns with the Kubernetes Version Skew policy. 

The ask here is consider allowing the updateCluster API call to allow the managed worker nodes to be up to 2 versions behind the target version for the upgrade. As an example, allowing a 1.18 EKS API server to upgrade to 1.19 when the worker nodes are on 1.17. The upgrade should be blocked to 1.20 until all worker nodes are at least on 1.18. If the user decides, they can then update the worker nodes to 1.19 directly instead of having to update twice. 

**Which service(s) is this request for?**
EKS managed nodes

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

This request is to reduce the amount of time spent updating worker nodes to be the same version as the API server. For customers with large amount of clusters, this adds a lot time spent doing worker node upgrades when it can be tolerated to do skip level updates. 

**Are you currently working around this issue?**
Updating all managed node group to be the same minor version as the control plane, then updating the control plane to the next minor version.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by elylee** [comment]
EKS now supports Kubernetes 1.28 along with the n-3 version skew policy for worker nodes. Note the upstream skew policy regarding kubelet: https://kubernetes.io/releases/version-skew-policy/#kubelet
"kubelet < 1.25 may only be up to two minor versions older than kube-apiserver".

This means only the following combinations are fully supported by EKS as of this writing:
- 1.23 worker nodes: 1.23, 1.24, 1.25 control plane
- 1.24 worker nodes: 1.24, 1.25, 1.26 control plane
- 1.25 worker nodes: 1.25, 1.26, 1.27, 1.28 control plane
- 1.26 worker nodes: 1.26, 1.27, 1.28 control plane
- 1.27 worker nodes: 1.27, 1.28 control plane
- 1.28 worker nodes: 1.28 control plane

Since EKS no longer supports Kubernetes versions older than 1.23, you will not be able to create EKS Managed Node Group (MNG) with worker node components older than 1.23, nor will any worker node older than 1.23 receive patching from EKS. However, you can connect existing worker nodes on 1.21 and 1.22 to an EKS cluster with a 1.23 control plane; you can connect existing worker nodes on 1.22 to an EKS cluster with a 1.24 control plane.

EKS Kubernetes 1.28 release note: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.28
