### ISSUE TITLE
[EKS] [Security]: Allow restricting access to EKS Kubernetes Public API Endpoint via security group

### ISSUE THREAD

**Issue by dejwsz** [aws/containers-roadmap#1635]
This relates to already implemented feature: https://github.com/aws/containers-roadmap/issues/108. 

But I have a question if it would be possible to do the same thing but with security group instead? This can be done for example with ALB ingress where you can use very handy annotation for this kind of access whitelisting called: "alb.ingress.kubernetes.io/security-groups" what is much better than "alb.ingress.kubernetes.io/inbound-cidrs" imho. This what is done here is similar to inbound-cidrs annotation concept.

It would be good to have an option to use a security group instead.

**Comment by colinbjohnson** [comment]
This is absolutely brilliant, btw.

**Comment by jessesanford** [comment]
I want to promote this feature as I think that this is a far more intuitive way of handling the whitelisting given the parity with all of the other amazon services that use security groups for traffic filtering. The current solution is very EKS centric and feels like it was just a stop gap solution to get ip whitelisting in place. Please prioritize this feature so that securing EKS API endpoints through firewalling is as familiar as other services.

**Comment by mikestef9** [comment]
Closing as duplicate of #1063
