### ISSUE TITLE
[EKS] [request]: Allow to increase container disk space on EKS Fargate

### ISSUE THREAD

**Issue by ustramooner** [aws/containers-roadmap#1794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
It looks like disk volume one gets in Fargate is ~20 GB. It would be helpful to be able to configure the size it in Task/Container configuration. In our case, we would like to go as high as 150 - 200 GB.
(link to doc confirming this limit: https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html)
This is a bit of a clone of https://github.com/aws/containers-roadmap/issues/384 - but EKS was not fixed on this ticket, only ECS

**Which service(s) is this request for?**
Fargate, EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have a container that needs to run on Fargate that is fairly large. It's about 8.5Gb. Starting the POD with this image fails - I'm assuming that downloading then later extracting the image needs double the space. And as the 20Gb is the upper limit, we're not able to run a container this large.

**Are you currently working around this issue?**
Trying to shrink our docker image, but this will be difficult. 

**Additional context**
In this case a workaround of using an EBS/NFS volume won't work as the problem occurs due to a very large docker image

**Comment by pcolmer** [comment]
Our use case is slightly different but the end requirement is the same. We're using EKS+Fargate to provide scalable CI/CD resources for GitLab. To that end, a running pipeline may require more disc space than 20GB. EFS may be a solution but being able to specify the size of the ephemeral storage through the Kubernetes stack is more consistent with the ability already present to specify CPU & memory requirements.

Furthermorre, using ephemeral storage rather than EFS means that we don't have to clean up the storage at the end of each job, or pay for ongoing costs of using EFS storage.

**Comment by JasonRD** [comment]
We have similiar scenario.  
We're using EKS+Fargate to deploy spark job, which will be scaled to Fargate. The spark job requires more than 50GB local disk to calculation, and is sensitive to the performance of disk.

**Comment by bdbrink** [comment]
we plan on using fargate for sensitive data/optimization services, need to be able to write more than 20GBs to ephemeral storage whenever we spin up a pod. Mounting NFS/EFS is not really suitable for us due to the associated cost of managing the external storage, as well as the data being out of date, and regulatory compliance associated with the data we handle.

**Comment by ollypom** [comment]
We are excited to announce that Kubernetes Pods launched onto AWS Fargate through Amazon EKS can now request up to 175GiB of storage. 🎉 🎉 

Resources:

- [Launch Blog](https://aws.amazon.com/blogs/containers/amazon-eks-fargate-adds-support-for-larger-ephemeral-volumes/)
- [Documentation](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html#fargate-storage)
