### ISSUE TITLE
ECS CloudWatch events for Services

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#19]
ECS service event messages that currently show up only in the service event messages will be available at actual CloudWatch events.

**Comment by zbintliff** [comment]
Hi @coultn , wondering if there is any more traction on this issue? Going to the actual services on a cron to get this information isn't very scalable. It leaves quite an observability hole in the ECS story.

**Comment by coultn** [comment]
> Hi @coultn , wondering if there is any more traction on this issue? Going to the actual services on a cron to get this information isn't very scalable. It leaves quite an observability hole in the ECS story.

Thanks @zbintliff, I don't have any more to share right now, but I hope to be able to add some new information soon.

**Comment by hlarsen** [comment]
what is the recommended way to handle this problem without these events? anyone have a workaround or similar solution before i start hacking together something i'm not happy with?

i'm finishing setting up the slack notification portion of some CodePipeline > ECS workflows, however without these events we're basically left with an "Attempting to Deploy" after updating ECR with our new image and deploying it to ECS. ideally we could listen for and forward a few events (starting, steady state) and we'd be good - we're trying to keep people out of the web UI as much as possible.

**Comment by zbintliff** [comment]
Hey @coultn , would this also include ECS holding on to events longer for deleted services and tasks? 

We deploy services in a Blue/Green model (haven't adopted TaskSets yet) but this makes it incredibly hard to debug issues. For example, during an incident teams may need to deploy a config change an a new service is created. The events for the service (launched tasks, task killed because of X) get cleaned up very quickly. Is it possible to expand the time they are held on?

Even more aggressive is the cleanup on Tasks and their events/status. Within the same service if a task is churning slowly (because of an OOM Perhaps) tasks seem to be deleted within an hour, again making it incredibly difficult to collect data during RCAs.

**Comment by coultn** [comment]
@zbintliff If your goal is to enable post-event RCA, you might consider a CloudWatch Events rule that can send the events directly to a CloudWatch log group (see here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/WhatIsCloudWatchEvents.html and https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-cloudwatch-events-now-supports-amazon-cloudwatch-logs-target-tagging-cloudwatch-events-rules/).  This will enable every event that matches your rules to automatically be stored in CloudWatch Logs, and retained according to the policies you set up for CloudWatch Logs.  You can also use CloudWatch Logs Insights queries to query the stored events.  These are exactly the kinds of use cases we look forward to enabling when the ECS CloudWatch Events for Services feature launches.

**Comment by zbintliff** [comment]
Awesome, thanks. Looking forward for this feature.

**Comment by coultn** [comment]
Hi everyone, we are getting closer to launching this feature.  The list of events at launch is tentatively planned as the following (eventType | eventName):

INFO | SERVICE_STEADY_STATE
INFO | TASKSET_STEADY_STATE
INFO | SERVICE_DESIRED_COUNT_UPDATED
WARN | SERVICE_DISCOVERY_INSTANCE_UNHEALTHY
WARN | SERVICE_TASK_START_IMPAIRED
ERROR | SERVICE_DAEMON_PLACEMENT_CONSTRAINT_VIOLATED
ERROR | ECS_OPERATION_THROTTLED
ERROR | SERVICE_DISCOVERY_OPERATION_THROTTLED
ERROR | SERVICE_TASK_PLACEMENT_FAILURE
ERROR | SERVICE_TASK_CONFIGURATION_FAILURE


Here is an example event with (with account number removed):

```json
{
    "version": "0",
    "id": "f425576f-274e-1486-aff4-98ec698ae25f",
    "detail-type": "ECS Service Action",
    "source": "aws.ecs",
    "account": "REDACTED",
    "time": "2019-11-07T19:21:00Z",
    "region": "us-west-2",
    "resources": [
        "arn:aws:ecs:us-west-2:REDACTED:service/sleepy"
    ],
    "detail": {
        "eventType": "INFO",
        "eventName": "SERVICE_STEADY_STATE",
        "clusterArn": "arn:aws:ecs:us-west-2:REDACTED:cluster/testing",
        "createdAt": "2019-11-07T19:21:00.549Z"
    }
}
````

**Comment by wallynd** [comment]
AMAZING.... We cant wait to get our hands on this event stream! Can we get a little more info on what STEADY_STATE means?

**Comment by mwarkentin** [comment]
@wallynd if you go into Events for an ECS service, the service will reach "steady state" when all containers are healthy. 

These are just my guess, but during a deploy, at the end once all new containers are healthy and the old containers have been removed, I would expect this event to fire. If a container dies, and is replaced, I would expect it to fire again.

**Comment by mwarkentin** [comment]
For the failure cases you are probably looking at these events from the list: `SERVICE_TASK_PLACEMENT_FAILURE`, `SERVICE_TASK_START_IMPAIRED`, `SERVICE_TASK_CONFIGURATION_FAILURE`

**Comment by zbintliff** [comment]
These seem pretty comprehensive. I'm going to think through a few more scenarios to make sure there isn't a case that is missing.

Thanks!

**Comment by wallynd** [comment]
Hmm.. How do i tell if there is a new deployment?

**Comment by coultn** [comment]
These events are now available in all ECS regions, see here for documentation:  https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_cwe_events.html

**Comment by hampsterx** [comment]
thnx for early xmas present, fantastic~ I only see instance state and task state change events, does it require an upgrade of the ecs agent or should I just be a bit more patient (ap-southeast-2 region) LOL ?

**Comment by coultn** [comment]
Thanks for your question!  You do not need to do an agent update.  However, depending on your CloudWatch/EventBridge Event rule configuration, you might be filtering out these events.  The following rule will specifically capture the new events only:
```
{
  "source": [
    "aws.ecs"
  ],
  "detail-type": [
    "ECS Service Action"
  ]
}

**Comment by jpmontez** [comment]
@coultn I'm using that event pattern. Even after specifying missing images, putting errors in entry commands, etc., I'm not receiving `WARN` or `ERROR` events.

My services are definitely unable to start tasks and report configuration errors, but are only viewable from the console/API. The service events are not being fired.

The only events that are published are when I manually correct the task revision(s) to the last good state. Those events are just a `SERVICE_STEADY_STATE` notification.

What am I missing here?

**Comment by coultn** [comment]
@jpmontez can you email me , ncoult AT amazon.com ?

**Comment by Adiii717** [comment]
> {
>   "source": [
>     "aws.ecs"
>   ],
>   "detail-type": [
>     "ECS Service Action"
>   ]
> }

this does not work for me, while task Task State Change Events does

**Comment by adushechkin-plesk** [comment]
Doesn't work for me as expected either. I'm using Fargate in eu-west-1, and the only type of "ECS Service Action" I ever saw beyond "SERVICE_STEADY_STATE" was "SERVICE_TASK_START_IMPAIRED" for a task that can't pull its image due to absence of Internet connectivity in its VPC, but this test service was dead at least for a week now, so I'm not sure how long does it take to get that status.

I tried Lambda and log group directly as targets, both have the same output.

I'm testing with two simple cases:
- a task can't pull an image or whatever reason
- ALB deregisters a task because it never passed a healthcheck

Meanwhile, messages like "service dummy-service (port 80) is unhealthy in target-group dummy-tg due to (reason Request timed out)" are seen in the Console, but I can't find them in the log groups neither by text nor by Event ID

@coultn, is there anything I can do to help with the diagnostics? Would be really cool to have that messages available for automation without querying each service once in a while.

**Comment by mbp** [comment]
For Fargate, I have found this feature disappointing, since the only message I ever see is `SERVICE_STEADY_STATE` at random times. It will never output anything if system is auto scaling, or increasing task count using CloudFormation etc. There are so many useful messages in the "Events" tab of the ECS Console, that we don't get.

**Comment by adushechkin-plesk** [comment]
So, I left brand-new (new cluster, new service, new VPC, new everything) broken (can never pull its image because of security group rules) Fargate task overnight and saw first SERVICE_TASK_START_IMPAIRED event 2 hours after creation, which is a bit late to my taste.

Moreover, events in the Console and events from Cloudwatch has different Id's, which is inconvenient.

So, I propose to either reopen this issue or create other issue specifically for Fargate events since I understand that this issue may have non-Fargate focus.

**Comment by mic-kul** [comment]
Is it possible to map back to container or service based on data passed in `SERVICE_TASK_PLACEMENT_FAILURE` event?

**Comment by muthu-vgh** [comment]
how do it force this event to fire, INFO | SERVICE_DESIRED_COUNT_UPDATED, so far no luck, anyone here got it to fire this event

**Comment by dcelasun** [comment]
```json
{
  "source": [
    "aws.ecs"
  ],
  "detail-type": [
    "ECS Service Action"
  ]
}
```

Like @jpmontez I can't make this work either. I've tried with a scheduled task in a cluster with no instances and was expecting a `SERVICE_TASK_PLACEMENT_FAILURE` event. Any ideas @coultn?

**Comment by pinkjosh** [comment]
This is my event rule. 1 task was running with a desired count of 1. I deliberately pushed updated docker that has failed health check so that newly pulled task fails and sends either SERVICE_TASK_START_IMPAIRED or other service ERROR events but none is triggered. This is my rule:

    {
  "source": [
    "aws.ecs"
  ],
  "detail-type": [
    "ECS Service Action"
  ],
  "detail": {
    "clusterArn": [
      "arn:aws:ecs:us-east-1:ACOUNT_NUMBER:cluster/my-cluster"
    ],
    "eventName": [
      "SERVICE_TASK_PLACEMENT_FAILURE",
      "SERVICE_TASK_START_IMPAIRED"
    ]
  }

**Comment by pinkjosh** [comment]
This is my event rule. 1 task was running with a desired count of 1. I deliberately pushed updated docker that has failed health check so that newly pulled task fails and sends either SERVICE_TASK_START_IMPAIRED or other service ERROR events but none is triggered. Can't make it work. Is there another way I could make it trigger the event? This is my rule:

`{
"source": [
    "aws.ecs"
  ],
  "detail-type": [
    "ECS Service Action"
  ],
  "detail": {
   "clusterArn": [
      "arn:aws:ecs:us-east-1:ACOUNT_NUMBER:cluster/my-cluster"
    ],
    "eventName": [
      "SERVICE_TASK_PLACEMENT_FAILURE",
      "SERVICE_TASK_START_IMPAIRED"
    ]
  }
}`

**Comment by tyrken** [comment]
I'm getting SERVICE_TASK_PLACEMENT_FAILURE events come through for ECS services without any load balancer attached, but not for ones with a (classic) ELB on them - not sure about ALB/NLBs.  Still waiting on AWS Support to get through to the internal team about it...

**Comment by pinkjosh** [comment]
> I'm getting SERVICE_TASK_PLACEMENT_FAILURE events come through for ECS services without any load balancer attached, but not for ones with a (classic) ELB on them - not sure about ALB/NLBs. Still waiting on AWS Support to get through to the internal team about it...

Can you please provide the cloudwatch event rule you used. I am using ALB with my ECS service. I would like to see if your rule has something I am missing in mine.

**Comment by tyrken** [comment]
@pinkjosh it's fairly vanilla, and the rule just sends data to CloudWatch Logs for inspection:

```
{
  "source": [
    "aws.ecs"
  ],
  "detail-type": [
    "ECS Service Action"
  ],
  "resources": [
    "arn:aws:ecs:eu-west-1:123accountid:service/my-service-arn1",
    "arn:aws:ecs:eu-west-1:123accountid:service/my-service-arn2"
  ]
}
```

**Comment by violiveira** [comment]
Was anyone ever able to get SERVICE_DESIRED_COUNT_UPDATED? I am doing stress testing against our cluster and the service scaled multiple times. However, I was not able to find any correspondent event.

**Comment by heang-github** [comment]
how about eventType? can we use a list, or it has to be a string?
eventType  = ["WARN", "INFO"]
vs 
eventType  = "WARN"

Thank you
