### ISSUE TITLE
[ECS] Automatic DRAINING state on spot retirement

### ISSUE THREAD

**Issue by tyrken** [aws/containers-roadmap#190]
### Summary
Please auto-set a spot instance to DRAINING when it's being terminated

### Description
When a spot instance is terminated (e.g. by scale down or price event), a 2-minute notification is given via a magic URL: http://169.254.169.254/latest/meta-data/spot/termination-time

I was hoping ECS agent could monitor this & set the container instance state to DRAINING automatically.  This allows slightly cleaner scale-downs than merely dropping containers as the instance powers-off.

I see others have implemented local scripts or code to do this themselves, e.g. https://github.com/ktruckenmiller/aws-ecs-spot-instance-drainer

### Expected Behavior
Container Instance is set to DRAINING briefly before vanishing.

### Observed Behavior
CI stays in ACTIVE until it disappears.

### Environment Details
Using agent version 1.20.3 currently

**Comment by sumitverma** [comment]
+1

**Comment by MarcusNoble** [comment]
It'd be good to see this in EKS as well if possible.

**Comment by ekini** [comment]
The old way of polling the URL in a loop works, but an event-based Lambda is much better, just because it doesn't consume resources when it's not required, and one Lambda can handle multiple clusters. Fits into the free tier as well.

Here is another implementation: https://github.com/springload/spotasaurus a Lambda as a [terragrunt](https://github.com/gruntwork-io/terragrunt) module.

We can see only half of the control plane here, which is ecs-agent. But there is ECS cluster software running somewhere on AWS, and that would be the best place to implement handling of spot termination.

**Comment by coultn** [comment]
This feature will work similarly to https://github.com/aws/containers-roadmap/issues/256, except that ECS cannot prevent a Spot instance from terminating.

**Comment by alvarow** [comment]
+1

**Comment by saurabtanej** [comment]
+1

**Comment by rdawemsys** [comment]
+1

**Comment by orsigiorgio** [comment]
+1

**Comment by barakseri1** [comment]
+1

**Comment by pavneeta** [comment]
Hi Everyone, 
oday, September 27th , Amazon ECS today launched Automated Draining for Spot Instances running ECS Services. This feature will enable ECS customers to safely manage any interruptions of ECS services running on Spot instances due to termination of the underlying EC2 Spot instance.
https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-ecs-supports-automated-draining-for-spot-instances-running-ecs-services/

**Comment by innokentiyt** [comment]
Any news on this? https://github.com/aws/containers-roadmap/issues/256
