### ISSUE TITLE
[EKS] [request]: Enable Pod Priority and Preemption

### ISSUE THREAD

**Issue by alejandrox1** [aws/containers-roadmap#211]
**Tell us about your request**
It would be cool to have [pod priority and preemption](https://v1-10.docs.kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) enabled in order to fully take advantage of the cluster autoscaler via [overprovisioning](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler).

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When using the cluster autoscaler in Kubernetes v1.10.1 (eks.3) the autoscaler will wait for pods to be in `pending` state before trying to scale up. Over-provisioning with `pause` pods allows for extra resources to be accounted for and if needed taken by other pods with higher priority. If this happened then the `pending` `pause` pods will then signal the cluster autoscaler to scale up thus reducing the effect on production workloads.
This feature is already enabled by default in Kubernetes v1.11 but using EKS, this doesn't provide support for API aggregation.

**Comment by whereisaaron** [comment]
Hi @alejandrox1 I thought the same as you about API aggregation because all my apps were breaking on EKS. But [@christopherhein explained](https://github.com/aws/containers-roadmap/issues/152#issuecomment-464217775) that [EKS actually does support API aggregation](https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-eks-enables-support-for-kubernetes-dynamic-admission-cont/), but only if your app is "_running at least the 1.10+ client-go libraries which added support for the exec credential authentication flow"_. So a newer release of `cluster-autoscaler` may work. Do let us know here if you have any success.

**Comment by alejandrox1** [comment]
So a bit of clarification on this issue. I had misunderstood the way that eks platform version worked. I was under the believe that all Kubernetes versions in a given eks platform version had the same set of "features" enabled. Hence my comment - in AWS docs, api aggregation is mostly mentioned in k8s v1.10 and in that version only eks.2 and greater supports api aggregation. 

However, the eks platform version seems to be a point of reference for each kubernetes version independent of others, i.e., k8s v1.10 in eks.1 is not the same as k8s v1.11 in eks.1.
So going back to my request, a simple way to get pod priority and preemption (which is beta in k8s v1.11 and thus enabled by default) is to upgrade from k8s v1.10 to v1.11 (Kubernetes v1.11 in eks.1 and up will support API aggregation already).
