### ISSUE TITLE
required ec2 to serve 100000 node in eks

### ISSUE THREAD

**Issue by amiya-elear** [aws/containers-roadmap#226]
**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
This could be Fargate, ECS, EKS, ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem? 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

i want to know how many ec2 instance is required to manage 100000 node in eks with 500gb ebs

**Comment by tabern** [comment]
@amiya-elear can you give some more details on the cluster you are planning to run here?

A node is an EC2 instance, so to run a 100k node cluster, you will need 100k instances. With EKS or ECS you don’t need to worry about the control plane so this is not a factor.

This being said, the _software_ that underlies EKS (Kubernetes) has known limitations at the scale you are describing (100k nodes). This is a Kubernetes limitation, not an EKS limitation. Recommendation would be to split up your workload into multiple smaller clusters in order to achieve decent performance.

**Comment by tabern** [comment]
@amiya-elear can you give some more details on the cluster you are planning to run here?

A node is an EC2 instance, so to run a 100k node cluster, you will need 100k instances. With EKS or ECS you don’t need to worry about the control plane so this is not a factor.

This being said, the _software_ that underlies EKS (Kubernetes) has known limitations at the scale you are describing (100k nodes). This is a Kubernetes limitation, not an EKS limitation. Recommendation would be to split up your workload into multiple smaller clusters in order to achieve decent performance.

**Comment by tabern** [comment]
@amiya-elear do you mean 100k containers?

**Comment by amiya-elear** [comment]
yes , but those are light wait container those will take 100 to 150 mb data , could you please tell me how may ec2 and how many eks cluster is required, i am very new to aws i need help to create a cost effective infrastructure.

**Comment by amiya-elear** [comment]
how many container one eks can handle ? in one ec2 how many eks cluster can run and one cluster how many node it can handle.

**Comment by amiya-elear** [comment]
my requirement is that i want to host 100000 network management node  in ec2 what is the best practice to that in a cost effective way.

**Comment by tabern** [comment]
@amiya-elear this is actually a pretty nuanced question, right-sizing a cluster is highly dependent on multiple factors that are specific to your workload. The type of Amazon EC2 instance that you choose for your container instances determines the resources available in your cluster. Amazon EC2 provides different instance types, each with different CPU, memory, storage, and networking capacity that you can use to run your tasks. 

What you need to do is fully possible today on AWS. There are some good resources in the Kubernetes docs that may help with sizing your cluster:
- https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
- https://kubernetes.io/docs/setup/cluster-large/

Additionally, if cost savings are important, you may want to look at running some, or all of your cluster with EC2 Spot instances: https://aws.amazon.com/blogs/compute/run-your-kubernetes-workloads-on-amazon-ec2-spot-instances-with-amazon-eks/

**Comment by amiya-elear** [comment]
Thanks tabern ,
i gone through the document that clear lots of doubts and lots of issue, thanks for your help . one small question which is more cost effective host our Kubernetes cluster by  own in ec2 or take AWS EKS services for 100000 container. Kubernetes is open source can we use it for production with out paying anything to manage 100000 container or more then containers?

**Comment by tabern** [comment]
@amiya-elear Amazon EKS runs the same upstream open source Kubernetes software that you would run yourself. With respect to cost, while the software is free, running the control plane and managing it for 100k containers is not. You need to provision the instances for the K8s API server, you need to manage the etcd instances and EBS for cluster state, and you need to keep that all updated and running as you scale out to thousands of EC2 nodes. 

You are going to pay for all of the resources to run the EC2 and EBS instances for the control plane in addition to the time you are going to spend running it all. For example, if you are going to run the control plane with multiple API servers and etcd nodes (like EKS does), you'll need to pay for 5+ EC2 instances which can cost 5*(0.096 to 0.384+) per hour so roughly $0.48 - $1.92 per hour just for EC2 (you also need load balancing, EBS storage, etc for the control plane).

An EKS control plane does cost $0.20 per hour to run, but you get all of this heavy lifting included and don't have to pay anything additional as you scale your cluster. EKS gives you a production-ready cluster without having to figure out all the things you need to do in order to run the K8s control plane.

Glad you found this helpful! I'm closing this issue as your need can be fulfilled on EKS today with existing EKS and K8s documentation.
