### ISSUE TITLE
[EKS] [question]: Unable to patch cloudwatch-agent when using cloudwatch observability add-on

### ISSUE THREAD

**Issue by fluckx-cs** [aws/containers-roadmap#2309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I have an EKS cluster which contain tainted nodes. I have rolled out the eks-addon cloudwatch observability. As we have some tainted nodes I am trying to patch fluentbit and the cloudwatch agent daemonsets to run on all my instances.

I can patch fluentbit fine. When I try to patch the cloudwatch-agent however, it reapplies a configuration without the toleration I've added. Is this intended behaviour? Is this some admission webhook "correcting" the daemonset every time?

**Which service(s) is this request for?**
EKS - Cloudwatch Observability

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I am trying to  have the cloudwatch observability daemonsets run on all my tainted instances by patching in a toleration.
It does not work for cloudwatch-agent. As shown in the screenshot whenever I run my patch command, it will run two deletes and two creates:

<img width="1093" alt="image" src="https://github.com/aws/containers-roadmap/assets/155734383/c6e87e66-87ec-49ab-b53f-12d31939b71e">

**Are you currently working around this issue?**
I cannot work around this issue right now

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by sky333999** [comment]
Hi @fluckx-cs - thanks for raising the issue.

Adding default tolerations and exposing the ability to modify the same via the add-on's advanced config is something we are tracking as a feature request in our backlog.

In the interim, the workaround you used for `fluent-bit` should also work for the `cloudwatch-agent`. Its just the CloudWatchAgent has a CRD so whatever is defined in the CustomResource is considered the desired state and any changes you make to the daemonset directly would get overwritten by the CloudWatchAgentOperator to bring it back the what is the CustomResource.
So instead, you could modify the CustomResource using a command such as the follows to edit it and in here, you can set the tolerations and let the CloudWatchAgentOperator make the changes to the daemonset.
```
kubectl edit amazoncloudwatchagent cloudwatch-agent -n amazon-cloudwatch
```

Note that if you do make these changes manually on your cluster, since its changing state of the resources outside of the context of the EKS add-on, the next time you upgrade your add-on version, these would get flagged as conflicts.
https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-preserve-customer-edits/ gives a good overview of how to handle that situation by choosing one of the `ResolveConflicts` options.

**Comment by fluckx-cs** [comment]
hi @sky333999 ,

I ended up on that CRD yesterday after I created the ticket. My patches didn't work out, but maybe my brain was already a little bit too fried for the day. 

Thanks for the quick reply - looking forward to the native support in the EKS-addon when it gets here! :)

**Comment by fluckx-cs** [comment]
Note: Brain was too fried - patching was successful.

For anybody wondering:

```shell
kubectl patch amazoncloudwatchagents.cloudwatch.aws.amazon.com cloudwatch-agent -n amazon-cloudwatch --type merge --patch-file patch.yaml"
```

`patch.yaml` could look like this

```yaml
spec:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
```
