### ISSUE TITLE
[ECS] [RFC]: Automatic management of instance draining in an ASG

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#256]
Request for comment: please share your thoughts on this proposed improvement to ECS!

With this improvement, ECS will automate instance and task draining.

- Customers can opt-in to automated instance draining for each of their clusters, using the AWS CLI, API, SDK, Cloud Formation, or Console.

- For ECS cluster instances that are members of an EC2 Auto Scaling Group (ASG),  ECS will set the instance to the DRAINING state whenever the ASG initiates termination of the instance. (The existing behavior of DRAINING is that ECS prevents new tasks from being scheduled for placement on the container instance. Service tasks on the draining container instance that are in the PENDING state are stopped immediately. If there are container instances in the cluster that are available, replacement service tasks are started on them. Service tasks on the container instance that are in the RUNNING state are stopped and replaced according to the service's deployment configuration parameters, minimumHealthyPercent and maximumPercent.)

- ECS will prevent the container instance from terminating until all service tasks on the instance have stopped (up to a maximum of 48 hours, based on how ASG instance lifecycle hooks work).

The functionality is similar to what was published in this [blog](https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/).  The main difference is that ECS will automate it for you.

**Comment by Jsmiiii** [comment]
Yes, this sounds great. Although we can manage removing instances from an ASG, this is painful process to do, especially if the ASG tries to re-balance itself across AZs - if the placement policies are set up to do that.

**Comment by tomelliff** [comment]
This would be great. I have a slightly gnarly Lambda function triggered by autoscaling termination hooks that loops to SNS over and over until the instance no longer has any tasks running on it and, while it works fine, always makes me a little uncomfortable every time I look at it.

Probably worth raising as a separate feature request but I'd also love to see daemonset services be the last to be evicted from a container instance. Right now our log shipper service runs as a daemonset and is one of the first things to be stopped when a container instance is drained, meaning logs for the tasks that are being connection drained from the ALB are now dropped.

**Comment by ngamradt-turner** [comment]
We actually use a slightly-modified version of the Lambda solution to do this, would love to see this become standard functionality.

I think we used the blog post to set it up.  There were some bugs with the solution that we had to fix.  It has been stable and works well, but would be great to have ECS manage this instead of the needed Lambda bolt-on solution.

**Comment by QuinnyPig** [comment]
Take it one step further. Imagine being able to drain instances from Fargate into an ECS instance. This unlocks a number of different opportunities for both cost and density stories.

**Comment by rgarcia** [comment]
We have had to implement our own draining logic since we run a handful of "system" containers that collect metrics, logs, etc. from the host. Without some kind of support to kill these containers last, the native draining mode isn't usable for us.

**Comment by sirocode** [comment]
Here are my observations: 

1. ECS service (in homemade green/blue deployment scheme) runs on EC2 Spot instance and has 50-200 policy. A dynamic port is being registered in the target group. Once I get spot termination notice (120 seconds before instance termination) - I run lambda (with is heavily modified lambda covered in https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/) that starts draining for the particular instance (with dynamic port). Because the deregistration delay is set to 30 seconds, draining happens and then (in 30 seconds) I get the same ECS server process running on the same EC2 sport machine again and it's registered in the same target group. Obviously, setting the whole EC2 node to draining state will help to solve the issue for this particular ECS service.

2. ECS service with 100-200 policy. 3 nodes on EC2 spots. When spot node stops - I cannot simply set the node into draining state because service's instance will not be deregistered from the target group - I need to force deregister it using Lambda. This "force deregister" is not good because it does not drain connections. Ideally, I'd like to have something called "force draining" - draining should happen when this scenario happens.

Also, monitoring containers (being run using DAEMON service type) should leave the instance last.

**Comment by rothgar** [comment]
I also would like to see logging/agents able to run in ECS with higher priority so they are evicted last or ignored from draining. Similar to priorityClassName in Kubernetes and critical-pods
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

**Comment by coultn** [comment]
Thanks everyone for your comments!  Regarding the scheduling of DAEMON services, that is being tracked under a separate issue:  https://github.com/aws/containers-roadmap/issues/128

**Comment by rgarcia** [comment]
I'd also like to see automatic DRAINING support for spot instances, i.e. if an instance gets a spot termination notice, automatically set it to DRAINING.

**Comment by Trane9991** [comment]
We wrote the lambda which does the exact thing: https://github.com/getsocial-rnd/ecs-drain-lambda
Supports the *Spot Instance Interruption Notice* and *Auto Scaling Lifecycle Terminate Hooks*.

**Comment by casper-gh** [comment]
> I'd also like to see automatic DRAINING support for spot instances, i.e. if an instance gets a spot termination notice, automatically set it to DRAINING.

+1

We recently migrated to mixed ASG per this [blog](https://aws.amazon.com/blogs/aws/new-ec2-auto-scaling-groups-with-multiple-instance-types-purchase-options/), and also using the lifecycle hook to set ECS host to DRAINING when ASG scales down an instance. My big question right now is will ASG able to detect `autoscaling:EC2_INSTANCE_TERMINATING` event for spot instances within this mixed group.

**Comment by coultn** [comment]
> > I'd also like to see automatic DRAINING support for spot instances, i.e. if an instance gets a spot termination notice, automatically set it to DRAINING.
> 
> +1
> 
> We recently migrated to mixed ASG per this [blog](https://aws.amazon.com/blogs/aws/new-ec2-auto-scaling-groups-with-multiple-instance-types-purchase-options/), and also using the lifecycle hook to set ECS host to DRAINING when ASG scales down an instance. My big question right now is will ASG able to detect `autoscaling:EC2_INSTANCE_TERMINATING` event for spot instances within this mixed group.

The answer is yes - it will handle both ASG lifecycle hooks and Spot termination notices.

**Comment by guilhermesmi** [comment]
This is very useful. One additional comment - the ability to set a Termination Policy to the ASG such that it prioritizes termination of EC2 instances that have no tasks running. Even tough setting the instance to DRAINING ensures ECS to schedule a new task to meet the service Min Healthy Percent / Desired Count, freshly started tasks may not perform as well as old ones due warm local caches, JIT compilation (for JVM), etc.

**Comment by innokentiyt** [comment]
Yes! This is my most desired feature for ASG and ECS.

**Comment by mfortin** [comment]
Would that DRAINING instance prevents other scaling activities on the ASG ? 
Say, the ASG is scaling down as the desiredCount has decreased, a lifecycle termination hook is triggered and part of that process is to DRAIN the ECS container instance. The instance state, in the ASG is TERMINATING:WAIT, and it waits until the instance has drained. However, if there is a new change and there is a new scale out rule, the ASG would not scale out as the lifecycle hook is not yet terminated. Am I right ?

**Comment by awsiv** [comment]
Should we expect instances de-registration in cloudmap as part of this as well?

**Comment by Adiii717** [comment]
Any update of this feature? Auto-scaling does not help enough in case of ECS cluster.

**Comment by jespersoderlund** [comment]
This item should also consider service discover / CloudMap so that tasks are de-registered from being discovered through CloudMap when the instance is being drained

**Comment by eddgrant** [comment]
Hi @coultn ,

We've recently run in to this, we've sticky-taped a workaround together using a Lambda and step function. Having done so I'm now keen to find out when the feature is likely to become available, to try and minimise the lifetime of our homegrown approach.

I know you probably aren't able to give dates, but could you perhaps give us an indication of what stage this work is at?

Cheers!

**Comment by briancurt** [comment]
How would this play out with cluster Capacity Providers? Is the plan (if any) to add this as a Capacity Provider feature, an Autoscaling Group feature, or something else?

**Comment by joshuabaird** [comment]
@briancurt Have you taken a look at the "managed termination protection" feature when using capacity providers/managed scaling?

**Comment by briancurt** [comment]
@joshuabaird Yeah, I'm using it in fact.

To be honest I asked because Capacity Providers have been kinda underwhelming. In theory the concept around them is great, but I found the implementation very restrictive and overly complicated. So if the automatic instance draining will be an ASG feature (without the need for Capacity Providers in between) I may consider moving out of Capacity Providers and back into managing the cluster scaling myself. With automatic instance draining, doing that oneself would be much easier.

**Comment by joshuabaird** [comment]
Ok - yeah, I agree that the CP implementation seems a bit overly complicated.  The main reason we're considering using it is to allow us to scale based on network resources (ENI), etc.

**Comment by CpuID** [comment]
Note: now that https://github.com/aws/containers-roadmap/issues/128 is live, the Python lambda in https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/ will likely always wait for the 900 second lifecycle hook timeout, rather than completing the ASG lifecycle hook once all tasks are terminated. Specifically since `DAEMON` tasks don't exit on `DRAINING` anymore.

@pavneeta I assume you are already onto it, based on assigning yourself yesterday :)

**Comment by Trane9991** [comment]
> Note: now that #128 is live, the Python lambda in https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/ will likely always wait for the 900 second lifecycle hook timeout, rather than completing the ASG lifecycle hook once all tasks are terminated. Specifically since `DAEMON` tasks don't exit on `DRAINING` anymore.

@CpuID, This doesn't seem to be the case, since according to this comment https://github.com/aws/containers-roadmap/issues/128#issuecomment-720262219 `DAEMON` will be stopped on `DRAINING` after all other tasks stopped.

> ECS will now ensure that Daemon tasks are the last task to drain from an Instance - this will allow the monitoring daemons to pick up trailing logs or metrics

**Comment by CpuID** [comment]
Aha, I read it wrong. Thanks for clarifying :)

**Comment by cageyv** [comment]
Post from 2017 still works: https://aws.amazon.com/ru/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/
With terraform/cf + aws cli it possible to achive zero-maintence ECS cluster with EC2 rotation.

**Comment by ohookins** [comment]
Is this expected to work seamlessly with EC2 instance refresh?

**Comment by zen0wu** [comment]
It looks like this is being worked on. Great!

If this works with Instance Refresh then it's 💯!

**Comment by hlarsen** [comment]
We're testing Capacity Providers (vs ASGs) to get the benefit of an on-demand ASG and a spot ASG. With the ECS Agent ECS_ENABLE_SPOT_INSTANCE_DRAINING env var and a Lambda for Lifecycle Hooks, I believe we have proper draining of tasks covered for Spot Terminations and non-spot ASG Terminations (manual termination, maximum instance lifetime, etc). It'd be nice to not have to worry about the lambdas, which I believe this issue will solve for ASGs themselves.

For ASGs, will this also cover instances terminated by the Maximum Instance Lifetime?

Will this also work for ASGs backed by Capacity Providers? What if they have Managed Termination Protection?

**Comment by youngminz** [comment]
I've tested [this](https://aws.amazon.com/ru/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/) with **Instance Refresh**, and I noticed that it works **perfectly**. 💯

**Comment by RajasGujarathi** [comment]
I'd also like to see automatic DRAINING support for ASGs backed by Capacity Providers with Managed Termination Protection enabled.

The challenge with us today is, we want that an *ECS Container instance* should not be running for more than 7 days. After 7 days, the container instance should be replaced with a fresh EC2 instance so that it picks updates from AMI via Launch Template. These container instances are provided by ASG backed by Capacity Provider and have instance scale-in protection *enabled*. Some ECS services have only 1 task running so which means only 1 Container Instance is running, post 7 days this instance does not go away because it has instance scale-in protection enabled.

**Comment by mdomsch-seczetta** [comment]
We have been using the blog approach for a while, and for the most part it works. In our configuration, we have a 1:1 mapping of ECS tasks to EC2 instances.  One complication we've run into is when scaling in from 2 ECS tasks on 2 EC2 instances, to a single ECS task on a single EC2 instance.  The ASG will sometimes choose to remove the EC2 instance that ECS would choose to keep an existing  running task on,  rather than the EC2 instance that ECS would choose to make idle.   We are using the OldestInstance ASG termination policy. When this happens, the ECS task count drops from two to one as it chose to stop a task, and then to zero (seemingly by surprise) as EC2 removes the non-idle instance.  There was never anything unhealthy, ECS  just realizes it has 0 tasks and 1 desired), and then starts up a task again on the still-present-but idle EC2 instance. For a  duration then, we have 0 tasks running, which isn't what we want.

Automating the scale-out and scale-in of EC2 instances for ECS tasks while providing us the ability to have long-lived jobs run to completion without being prematurely terminated, would be fantastic. We had to move from Fargate providers to EC2 for the long-lived jobs, as the maximum 2-minute SIGTERM to SIGKILL limit is insufficient for a few of our long-running jobs.

**Comment by stewartcampbell** [comment]
Long lived jobs problem is at least now solved for you.

https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-task-scale-in-protection/

**Comment by insertjokehere** [comment]
I got bitten by this today - I assumed that ECS was natively "aware" of what the ASG was doing and would intelligently manage moving tasks off an instance before it was shut down. Having this "just work" would be great.

**Comment by cristim** [comment]
I also had this reported by AutoSpotting users and implemented transparent handling for it in the latest version of my AutoSpotting.io tool.

**Comment by matt-domsch-sp** [comment]
> Long lived jobs problem is at least now solved for you.
> 
> https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-task-scale-in-protection/

This is an excellent step but is not enough. While termination protection is enabled, the sidekiq task will not get SIGTERM. If any one job is being processed, termination protection is enabled. Sidekiq is free to pick up additional jobs because it has no indication ECS would like it to stop. It cannot quiesce without such a signal. SIGTERM is a fine signal for such but now we have removed that. We need a signal to quiesce, and a way to keep from being SIGKILLed 2 minutes later.

**Comment by jeroenhabets** [comment]
@AbhishekNautiyal great to see this finally moved to "We're Working On It" 🚀 ! 
Any idea when you'll be starting the test phase (and if you have a GA date)? Can others (like me) sign up for a beta?

**Comment by andrew-aiken** [comment]
I implemented a more efficient version of [AWS's sample code](https://github.com/aws-samples/ecs-cid-sample/blob/master/README.md). It uses EventBridge to trigger when the node is finished draining instead of waiting (`sleep(5)`) until its finished.

https://github.com/andrew-aiken/website-ref/tree/main/ecs_asg_lifecycle

**Comment by petrisorciprian-vitals** [comment]
> > Long lived jobs problem is at least now solved for you.
> > https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-task-scale-in-protection/
> 
> This is an excellent step but is not enough. While termination protection is enabled, the sidekiq task will not get SIGTERM. If any one job is being processed, termination protection is enabled. Sidekiq is free to pick up additional jobs because it has no indication ECS would like it to stop, so it could run forever if there is always at least one job in the queue to pick up. It cannot quiesce without such a signal. SIGTERM is a fine signal for such but now we have removed that. We need a signal to quiesce, and a way to keep from being SIGKILLed 2 minutes later. Since ECS is fine letting tasks now run indefinitely with setting termination protection repeatedly up to 48 hours, let us set stopTimeout to 48 hours also.

Wouldn't doing this in reverse be a solution?
i.e., do not use scale in protection  initially; thus SGITERM arrives; once SIGTERM arrives, set up a handler to enable scale in protection, stop receiving new messages, wait for existing messages to finish, disable scale in protection.

Wouldn't this have the same effect as what you're intending?

I think you're misusing termination protection in this case; you're most likely meant to enable it AFTER receiving the SIGTERM in order to finish processing everything safely, not before, but perhaps I'm misunderstanding something here.

**Comment by longwave** [comment]
It seems this is now available? I'm seeing messages and configuration in the console:

![image](https://github.com/aws/containers-roadmap/assets/197817/e347c321-40de-4f15-a9a3-79c08a187b0a)

![image](https://github.com/aws/containers-roadmap/assets/197817/c343f8da-eba5-4acf-931e-b7db30cb3694)

**Comment by LiJell** [comment]
it seems available now

**Comment by AbhishekNautiyal** [comment]
We are in the process of rolling out ECS Managed Instance Draining. Some of you may already see an option appearing on the Amazon ECS Console and CLI. Please keep an eye out for the launch announcements and blog post in the coming days. We will share an update here as well!

**Comment by AbhishekNautiyal** [comment]
We're happy to announce the launch of Amazon ECS Managed Instance Draining.  Please refer to the [What's New](https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-ecs-managed-instance-draining/), [blog](https://aws.amazon.com/blogs/containers/amazon-ecs-enables-easier-ec2-capacity-management-with-managed-instance-draining/), and [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/managed-instance-draining.html). As always, we look forward to your feedback.

**Comment by SamJoan-hnry** [comment]
This is a great feature! Thanks @AbhishekNautiyal ❤️

**Comment by ajschmidt8** [comment]
Does anyone have this feature working successfully?

I tried enabling the "maxmimum instance lifetime" on my autoscaling group that's associated with my capacity provider and has managed instance draining enabled and it didn't recycle the instance.

I then tried manually toggling an instance refresh and ECS terminated my old instances before the ECS tasks were successfully rescheduled onto the new instances.

Seems like it's not working at all on my end.

**Comment by arnold-almeida** [comment]
I cant see this in the terraform docs yet.

**Comment by ajschmidt8** [comment]
> Not yet. Waiting for this to pop up in the terraform docs.

It's already been added:

- https://github.com/hashicorp/terraform-provider-aws/issues/35415
- https://github.com/hashicorp/terraform-provider-aws/pull/35421
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_capacity_provider#managed_draining

That's what I used to deploy my test cluster on ECS, but it doesn't seem to be working. I have a support ticket open with AWS. They've confirmed the issue and have escalated it to their internal services team.

That's why I'm wondering if anyone else has gotten it working :thinking:.
