### ISSUE TITLE
[EKS]: Release CNI v1.5.0

### ISSUE THREAD

**Issue by mogren** [aws/containers-roadmap#284]
**Tell us about your request**
Release v1.5.0 with fixed for `WARM_IP_TARGET`.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently in v1.4 and earlier, setting `WARM_IP_TARGET` does not not free IPs once they have been allocated. Fixing this is in the milestone for the 1.5 release.

**Are you currently working around this issue?**
How are you currently solving this problem? 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by tabern** [comment]
Release candidate https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.0-rc1

**Comment by tabern** [comment]
Marking this as a preview until it is the default CNI version for EKS

**Comment by seb-steuer** [comment]
I was wondering how this is in Dev Preview and at the same time you already officially suggest people to upgrade to 1.5.0 in your cluster upgrade documentation (link below; see step 10):
https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

**Comment by tabern** [comment]
**AWS VPC Container Networking Interface (CNI) Plugin version 1.5.0 is now the default CNI for new Kubernetes clusters launched by Amazon EKS!**

Version 1.5.0 of the AW VPC CNI plugin improves the behavior of the WARM_IP_TARGET parameter so that any IPs not assigned to pods will be returned back to the subnet. This lowers overall IP address utilization across the cluster. Additionally, a number of bug fixes improve the overall reliability and performance of the CNI for Amazon EKS clusters. 

**Links**
* [AWS VPC CNI v1.5 release notes](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.0)
* [What's new post](https://aws.amazon.com/about-aws/whats-new/2019/07/aws-vpc-cni-version-150-now-default-for-amazon-eks-clusters/)
* [Documentation on updating CNI plugin](https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html)
