### ISSUE TITLE
EKS on Fargate

### ISSUE THREAD

**Issue by outofcoffee** [aws/containers-roadmap#32]
This will allow customers to remove undifferentiated heavy lifting of operating worker nodes, whilst also being able to use the Kubernetes API.

Fargate for EKS reduces or removes the following operational concerns for worker nodes:

- patching
- configuration
- deployment
- secure defaults
- compatibility with backplane

@abby-fuller I'd appreciate your thoughts here.

**Comment by nikovirtala** [comment]
Fargate, as well as Fargate for EKS, was launched on re:Invent 2017, and since then we haven't heard a word about it from AWS. Even with my knowledge about Kubernetes, it relatively easy to say that removing the abstract of a node from Kubernetes is far from being an easy job. Maybe AWS chose a too big but to crack, and promised too much when said that it would be available in 2018? Nevertheless, it would be nice to hear where you are with this today. Many do appreciate your efforts of being more open, and I think it work well also in this case.

**Comment by welemon** [comment]
It was told that Fargate support for EKS will be available within 2018, now that line was removed from Fargate home page, which is sad to see, instead of a transparent update. Some other reference still mention the schedule, such as https://aws.amazon.com/blogs/aws/aws-fargate/

Now we don't see this even on near term roadmap?

**Comment by paulopontesm** [comment]
Also waiting for this. Sad to see it tagged as "proposed", given that we read about this a year ago.

Azure apparently made it: https://azure.microsoft.com/en-us/blog/bringing-serverless-to-azure-kubernetes-service/

**Comment by jstrachan** [comment]
there's a blog on how to [DIY your own kubernetes support on fargate](https://aws.amazon.com/blogs/opensource/aws-fargate-virtual-kubelet/) but I was really hoping for native integration between EKS control plane and fargate to provide _nodeless_ kubernetes support!

**Comment by ejc3** [comment]
There was a tiny bit of info provided here:
https://mobile.twitter.com/nathankpeck/status/1068287315917758464

**Comment by cdenneen** [comment]
Is this on the roadmap? I'm not seeing it.

Being able to deploy to Kubernetes endpoint via kubectl or helm is basically what people are looking for to avoid managing clusters, workers, task definitions, virtual-kublet, etc.

**Comment by arminc** [comment]
I think there are three levels in "managed":
First one is EKS where only the masters are managed and you do the rest. As a user, you can use all kind of services from AWS or your own because there are not 'many' restrictions.

The second one is a fully managed Kubernetes which means master and worker nodes. You can still do a lot of things because you have access to Kubernetes but there are limitations because you don't own the nodes.

The third and last one is Fargate which in my opinion should be an AWS opinionated stack for deploying containers on Kubernetes. This means for me for Fargate to be useful over EKS, AWS needs to provide a way to get secrets, ship logs, gather metrics, etc... in an opinionated way using AWS services. I shouldn't be bothered with IngressControllers I should be able to provide an Ingress for my service and it should be exposed. I am really interested in how AWS is planning to release Fargate for EKS while there are still features missing for EKS which in my opinion are needed to make Fargate working. I hope AWS can prove me wrong and come up with something fancy :)

Running an operator (for example Prometheus) on Fargate would that even make sense and how would that work?

**Comment by rprashad** [comment]
Would be nice to have access to docker.socket to do image builds via ci/cd in this managed eco-system.

**Comment by NaranKPatel** [comment]
I'm seeing increased customer interest on this too, curious if and when it'll launch.

**Comment by gjmveloso** [comment]
Sounds like we have a solid foundation to move this forward faster than previously expected. How about build on top of https://github.com/virtual-kubelet/virtual-kubelet/releases?

**Comment by whereisaaron** [comment]
@gjmveloso EKS Fargate was originally going to use `virtual-kubelet`, and you can use `virtual-kubelet` yourself with Fargate with an unforked/vanilla k8s, so I assume something else went wrong with this product behind the scenes. Pity, I was greatly looking forward to it.

**Comment by groodt** [comment]
Any updates on this roadmap item?

**Comment by github4es** [comment]
anyone know when Fargate for EKS will be made avaiable?

**Comment by igrowheart** [comment]
Re:invent is close, anyone have any update on the 'Fargate for EKS' feature?

**Comment by inductor** [comment]
！！！！！！！！！！！！

Coming Soon :eyes: :eyes: :eyes: :eyes:

**Comment by tabern** [comment]
I'm excited to announce you can now use Amazon Elastic Kubernetes Service (EKS) to run Kubernetes pods on AWS Fargate, the serverless compute engine built for containers on AWS. This makes it easier than ever to build and run your Kubernetes applications in the AWS cloud.

Pods that run on Fargate are billed at the [standard Fargate rates for vCPU and memory](https://aws.amazon.com/fargate/pricing/) and you pay the [standard EKS rate for each cluster that you run](https://aws.amazon.com/eks/pricing/). EKS support for Fargate is available in US East (Virginia), US East (Ohio), Europe (Ireland), and Asia Pacific (Tokyo) regions.

To get started, create a new EKS cluster and define a Fargate profile. eksctl support for Fargate will be available in the latest eksctl [release candidate today](https://github.com/weaveworks/eksctl/releases).

**Learn more in our [Blog](https://aws.amazon.com/blogs/aws/amazon-eks-on-aws-fargate-now-generally-available)**!
