### ISSUE TITLE
[ECS] Feature Request: Auto restart non-essential container (aka local container restart policy)

### ISSUE THREAD

**Issue by fenxiong** [aws/containers-roadmap#326]
Currently, auto restarting non-essential container in a task is not supported. In some use case, although a container doesn't need to be running for a task to run (therefore it's set to be non-essential), it's desirable to try to keep it running by restarting it. Currently the workaround is to schedule a service separately for the non-essential container with daemon scheduling strategy, but this decouples the container from other containers in the task, so it's not very desirable.

**Comment by nilroy** [comment]
This feature is absolutely needed

**Comment by coultn** [comment]
Thanks for your feedback everyone.  Questions for the group: what would your desired behavior be for a container that fails repeatedly?  Would you need to have an optional parameter for controlling the maximum number of restarts?  Exponential backoff?  Something else?   Do you need notifications or logging that this is happening?

**Comment by FernandoMiguel** [comment]
@coultn from my experience, ecs already does some exponential backoff, doesn't it?
I would love a clear indication in the dashboard that a task is restarting (often) rather than it saying running.
Maybe another column with the number of restarts since last deployment?

Also a cloud watch metric for healthiness, ie how long it has been up vs how it had been deployed

**Comment by mehdi-abbad** [comment]
@coultn I always liked the way a similar concept is implemented in erlang [supervisors restart strategy](http://erlang.org/doc/design_principles/sup_princ.html#maximum-restart-intensity). The gist of it is to tolerate a given maximum number of restarts in a given period of time. If the container is constantly restarting it means something wrong is happening, but an occasional restart of an unessential process would not affect the rest of the system.

**Comment by whereisaaron** [comment]
@coultn I think exponential back-off with no maximum restarts, usual k8s approach. The back-off would increase until the period is long enough that continuous restarts pose negligible impact on ECS/Fargate, maybe 10-15m? The containers may we be failing from something external beyond their control, e.g. a 2 hour `us-east-1` outage 😉 so it is better they don't give up and recover after external conditions return to normal.

As @FernandoMiguel said, there should be some way of monitoring for high restart counts, even if only at the Task/Service level. A log entry per restart is handy, particularly if it identifies specific container that restarted.

**Comment by morj** [comment]
Hi! Is anybody aware of some workarounds for this one?

**Comment by whereisaaron** [comment]
@morj, suggest:
1. Make your main container just a monitor for the other sidecar ‘non-essential’ containers. If any sidecar container goes down, bail, and ECS will restart the whole task.
2. Use AWS EKS, it is just a lot more advanced and has all this stuff covered already. I love ECS for Fargate, which has unique advantages, but plain ECS is a kinda primitive compared to EKS IMHO.

**Comment by pparth** [comment]
+1

**Comment by rmalleman** [comment]
This feels like a no-brainer. +1

**Comment by jeswanthamazon** [comment]
+1

**Comment by timurridjanovic** [comment]
Is there a way to restart the non essential container without killing the entire task? 
I have a task with 2 containers, one essential and one non essential. The essential one is always up and running. I would like to use the ECS api (or some work around) to restart the non essential container without killing the task (I want my essential container to still be up and running).

**Comment by lubingfeng** [comment]
Any plan on this?

**Comment by shawnrushefsky** [comment]
I'll join the chorus, and say this would be an immensely useful feature. I would like the restarting behavior to be configurable, such as max number of restarts, exponential back-off.

**Comment by eddwardo** [comment]
That could save a lot of `while true` loops in container entrypoints.

**Comment by c-ameron** [comment]
Is there any further development on this? Coming from a Kubernetes world I thought this would be a given

**Comment by alexlance** [comment]
Anecdotally: we got bitten by this recently. We have a task definition that comprises of one container serving web requests (the "essential" container), and several worker containers that weren't marked essential.

The worker containers crashed because of an intermittent database connectivity issue, and we were left with a frontend serving web requests, but no worker containers to fulfill the backend side of things.

Even a simple "restart=always" style of switch would have made all the difference.

**Comment by GordonMcKinney** [comment]
Our team has the same challenge but for essential containers.

Our ECS Fargate Tasks are comprised of a microservice container (insert your use-case here) and several supporting essential sidecars: Datadog agent, Consul Connect agent, and Envoy. If one of those sidecars exits, the task is terminated, causing a sudden decrease in capacity. Restarting the whole task takes 70-120s, during which time our UX latency numbers increase, triggering monitoring alarms.

From experience, Consul Connect and Envoy processes (not containers) take 2-8 seconds to restart. Therefore, we see a clear benefit for ECS to restart a stopped container instead of terminating the task.

The comments above regarding a maximum restart limit are prudent. A container that has a permanent ABEND shouldn't restart forever.

**Comment by BlueCanary-DM** [comment]
+1

**Comment by tovbinm** [comment]
A must have feature!!

**Comment by alexlance** [comment]
I ended up taking the `while true` (well actually, `until true`) approach of making the containers automatically restart themselves:

restart.sh:
```
#!/bin/bash
set -euo pipefail

# Wrapper script to ensure a process restarts itself if it exits non-zero
until "${@}"; do
  printf '{"level": "FATAL", "timestamp": "%s", "event": "%s", "command": "%s"}' "$(date -Iseconds)" "restarting container" "${@}"
done
```

in the task definition:

```
{
   "command": [
      "./restart.sh", "some", "command", "goes", "here"
    ]
}
```

but it would be more preferable to be able to control this at the ECS level.

**Comment by GordonMcKinney** [comment]
@alexlance We have a similar restart script that handles the following scenarios:

* Must restart a process that experiences an unsolicited exit
* A restart must pause for no less than a second to prevent an infinite restart loop consuming all the CPU for an incorrectly configured process
* Must pass the SIGTERM or SIGQUIT signal to the process
* Must not restart the process when it exits due to a SIGTERM or SIGQUIT
* Must handle signal/exit race conditions

Having the above logic built into ECS/Fargate is desirable because the lifecycle state is known by ECS and unsolicited process exits are easier to manage with that context.

**Comment by cwhyland-jetty** [comment]
> @alexlance We have a similar restart script that handles the following scenarios:
> 
> * Must restart a process that experiences an unsolicited exit
> * A restart must pause for no less than a second to prevent an infinite restart loop consuming all the CPU for an incorrectly configured process
> * Must pass the SIGTERM or SIGQUIT signal to the process
> * Must not restart the process when it exits due to a SIGTERM or SIGQUIT
> * Must handle signal/exit race conditions
> 
> Having the above logic built into ECS/Fargate is desirable because the lifecycle state is known by ECS and unsolicited process exits are easier to manage with that context.

Would you care to share?

**Comment by GordonMcKinney** [comment]
Company confidential. I have to jump through several hoops to share it. Plus it's written in bash instead of Go... nobody wants to see that :-)

**Comment by pp-assis** [comment]
+1

**Comment by Menion93** [comment]
+22

**Comment by henryagbo** [comment]
++1

**Comment by savroman** [comment]
+1

**Comment by AlexeiZenin** [comment]
+1

**Comment by dylanneild** [comment]
+1 to all of this. Allowing non-essential containers to be quietly restarted within the running task definition without also tearing down the essential containers would be ideal.

**Comment by patnym** [comment]
+1

**Comment by Sohit1212** [comment]
+1

**Comment by 91pratyush** [comment]
+1

**Comment by tremendoustj** [comment]
It's highly desirable to get this supported and make it easier for us to spin up the container back if it dies.
+💯

**Comment by adischerrer** [comment]
+1

**Comment by stsitsonis** [comment]
Today, the ECS team announced the availability of setting [Container Restart policies](https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-ecs-restart-containers-task-relaunch/) to facilitate avoiding unnecessary task relaunches and to address concerns raised in this issue, for both essential and non-essential containers. To learn more and to try the feature out, check our [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-restart-policy.html).
Let us know of any questions and what you think!

**Comment by GordonMcKinney** [comment]
@stsitsonis Great news! Thank you! 🙂

**Comment by otbe** [comment]
Its a pitty that one cannot configure the restart policy if the container contains a ` firelensConfiguration`. 😅
This was my main use case for this (restart the otelcol without interferring with the business app)

**Comment by eswets** [comment]
Why was CFN support skipped for this feature? https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/2109

**Comment by poost-frey** [comment]
@stsitsonis Thanks for sharing this! I've been experimenting with the new Container Restart policies and EventBridge rules and haven't been able to get source = 'aws.ecs' to emit any events when a container is restarted. Do you know if this is intended to be supported? We currently use task restart alerts to know when something should be looked at, so similar container restart alerts will be critical.

**Comment by sparrc** [comment]
Feature request related to firelens FLUENT_HOST limitation in bridge network mode: https://github.com/aws/containers-roadmap/issues/2429

**Comment by bmbferreira** [comment]
Is this working for everyone? I'm having a back and forth with AWS support because I don't think this is working properly. I have a non essential container running the opentelemetry collector and when it exits with exit code 137 because of an out of memory it is not restarting automatically. The response from the AWS support:

> Our internal team has conducted a comprehensive review and determined that the problem associated with task ID "XXX" was caused by the container being terminated due to insufficient memory. Despite this, the task continued to run because the container was designated as non-essential.
Based on our findings, the key recommendations are:
> 1. Set a memory reservation for the container: Ensure that the container has a sufficient memory reservation to prevent it from being killed due to an out of memory condition.
> 2. Mark the container as essential: Configure the container to be marked as essential, so that if the restart policy fails, the task will be replaced to maintain the desired state.

🫠 🫠 🫠 

So either there's a lot of details missing on [the docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-restart-policy.html) for this feature or this is not working at all...
