### ISSUE TITLE
Support `--pids-limit` `docker run` flag

### ISSUE THREAD

**Issue by kristiantakvam** [aws/containers-roadmap#354]
Related to #502. Without this flag, it's cumbersome to prevent fork bombs in containers.

**Comment by pparth** [comment]
+1

**Comment by hyksos** [comment]
No special use case required to be needing this except a mixed ECS cluster.
One container can fork bomb the entire host, I'm looking at you JAVA containers...
At which point everything is degraded and with, most of the time, very tangential or seemingly unrelated error messages because the kernel being at max_pids is not something that leads to very clear error messages at the top of the stack.

We have hit this multiple time in production and the only work around we have so far is to set the host max_pids at 4M and hope we don't run out of something else during a fork bomb.
That's when system's guys start to miss the isolation of a VM/hypervisor :)
Jokes aside, it would be useful to surface this in the task definition.

**Comment by joedj** [comment]
We have also had the same problem @hyksos describes, in production.

Support for `--pids-limit` would be appreciated.

Currently, we approximate `--pids-limit` by using a scheduled job to set per-task limits, i.e. something like:

1) Mount `pids` cgroup in `/etc/cgconfig.conf`
2) `yum install libcgroup-tools && systemctl cgconfig enable # amzlinux2`
3) Schedule:
```bash
LIMIT=8192
# amzlinux1
if [ -d /cgroup/pids/ecs ]; then find /cgroup/pids/ecs -mindepth 3 -maxdepth 3 -type f -name pids.max -exec sh -c "echo ${LIMIT} > {}" \; ; fi
# amzlinux2
if [ -d /sys/fs/cgroup/pids/ecs ]; then find /sys/fs/cgroup/pids/ecs -mindepth 3 -maxdepth 3 -type f -name pids.max -exec sh -c "echo ${LIMIT} > {}" \; ; fi
```

**Comment by singhnix** [comment]
Please advise the timeline of this as this issue is opened since 4-5 years now and customers are still looking for the availability.

**Comment by SpeedAndPower** [comment]
Any update on timeline or ETA on this long 6 year old issue? This is becoming a serious gap for our use case
