### ISSUE TITLE
[EKS] [request]: Dashboard

### ISSUE THREAD

**Issue by ld-singh** [aws/containers-roadmap#387]
**Tell us about your request**
What do you want us to build?
In built kubernetes dashboard on the EKS console similar to Kubernetes dashboard.
**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It will be a great help for the EKS user to have all details on the console rather than implementing a Kubernetes dashboard using heapster which is already deprecated. It can help developers see the status of the deployments done through cicd pipelines without needing any kubectl command on local.

**Are you currently working around this issue?**
How are you currently solving this problem? 
Only using kubectl to see status of pods during deployments.

**Comment by mbeacom** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html

**Comment by whereisaaron** [comment]
An EKS console would be great. But I'd be concerned whether AWS could keep the AWS console up to date with Kubernetes API changes.

Alternatively EKS could provide in a clean IAM authentication mechanism that allows AWS console users to directly launch the native Kubernetes dashboard.

BTW the Kubenetes Dashboard has been updated to use Metrics API rather than heapster, and also migrated to Angular:
https://github.com/kubernetes/dashboard/issues/2986#issuecomment-506378385

Release target for 2.0.0 is June 30, but still some issues to address: https://github.com/kubernetes/dashboard/milestone/1

**Comment by ld-singh** [comment]
Good point about keeping up with the Kubernetes API changes. I feel good way to launch dashboard from console  would also be nice. But some UI is definitely needed. Looking forward to 2.0.0.

**Comment by tabern** [comment]
@ld-singh do you think its most important to be able to see Kubernetes API objects (such as pods, deployments, etc) or AWS infrastructure objects from the console (ASGs, EC2, etc) for the cluster?

**Comment by ld-singh** [comment]
Hey @tabern .... I feel it will definitely be useful to see K8s API objects for sure .... for AWS infra i think only stats about how many nodes and their availability status is enough....

**Comment by tdmalone** [comment]
@tabern If 'both' is an option, I would say that!

But if you're wanting a clear preference... I think I would choose the AWS infrastructure objects (ASGs, EC2, LBs, VPCs, etc.), only because there isn't a unified place to see them all together at the moment. There _is_ a way to see the K8S API objects in a unified place - by installing the Dashboard - but I think this issue was asking to make the Dashboard set up process a bit simpler by having something similar (if not the Dashboard itself) already integrated into the EKS console. That would be awesome, and would save a lot of time especially for authentication, and I think for new users getting their head around things.

OTOH having a unified place to view the AWS infrastructure objects all together would also be amazing - but I'm thinking you might want to track that as a separate feature request?

**Comment by ld-singh** [comment]
The new Kubernetes dashboard 2.0 (https://github.com/kubernetes/dashboard/releases) seems to fully support 1.15 version only. Some of the features wont work in versions lower than 1.15.

**Comment by whereisaaron** [comment]
Worth testing, I think the tick just reflects the one version the are targeting and testing with. beta.1 supported 1.14 and not 1.15, beta.2 swapped that.

**Comment by ld-singh** [comment]
Was able to set up but faced this issue (https://github.com/kubernetes/dashboard/issues/4088) as I am not using AWS VPC CNI and using weavenet overlay and was able to fix using hostNetwork:true for dashboard metrics scrapper

**Comment by ld-singh** [comment]
Vmware's octant seems really good option for those looking for a dashboard without running anything in cluster.

https://github.com/vmware/octant

**Comment by Typraeurion** [comment]
I have the K8s Dashboard installed in my cluster, and while it provides most of the status details I need, it has a few quirks for which an AWS solution would be very helpful.
• In order to access the Dashboard, I first have to run “kubectl proxy” in a separate terminal
• Then I need to look up and paste a very long (860-character!) service account token into the Dashboard’s login screen.
• The authentication cookie has a relatively short idle timeout (just a few minutes,) so I have to repeat the above step every time I go back to the dashboard after doing something else.
• Whenever I do re-authenticate, the Dashboard’s namespace reverts to “default” so I need to re-select the namespace I’m working in.
• Setting up RBAC in Kubernetes to give other users restricted but still functional access to the Dashboard is not very easy to do.

**Comment by tabern** [comment]
Merging this with #135
