### ISSUE TITLE
[ECS,Fargate] [request]: Same Target Group for ECS-EC2 and Fargate services

### ISSUE THREAD

**Issue by SantiMunoz** [aws/containers-roadmap#499]
**Tell us about your request**
We would like to have a Target Group that is able to register tasks from a ECS-EC2 service and from a Fargate service at the same time.

**Which service(s) is this request for?**
Fargate and ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We would like to deploy the same service in ECS-EC2 and in Fargate at the same time and use the same ALB and Target Group for both. The idea is to have a stable number of containers in ECS-EC2, but when we need to scale up fast we would like to use Fargate to achieve this, avoiding all the time of creating and provisioning new machines in EC2.

**Are you currently working around this issue?**
Now we have one machine empty to leave room to scale up containers, and while they are scaling up we provision new machines. But at some point you reach the maximum containers that fit in the machines and you have to wait until a new machine is provisioned.

**Comment by akshayram-wolverine** [comment]
Thanks for sharing your use case! You can specify the same target group arn across ecs services running on ec2 and fargate. Have you tried this out?

**Comment by SantiMunoz** [comment]
Hi @akshayram-wolverin, thanks for your replay. I've tried to create a fargate service but it didn't allow me to use an existing Target Group. In the image below you can see how it only allows to create a new TG.
![image](https://user-images.githubusercontent.com/1433624/65753057-6dd55500-e10e-11e9-8030-8e599eff79c1.png)

I opened a support case in AWS and they told me this wasn't possible, that's why I created this issue.

**Comment by clareliguori** [comment]
Hi @SantiMunoz target groups can have only one target type (i.e. IP or Instance).  Fargate tasks must use the IP target type.  In order to share the target group across EC2 and Fargate tasks, you would need to both use the IP target type for the target group and use awsvpc networking mode for your EC2 tasks.

**Comment by SantiMunoz** [comment]
Hi @clareliguori, thanks for clarify that to me. Do you think my use case make sense and my request should move on or it's too deviated from the actual architecture of the Target Groups?

**Comment by clareliguori** [comment]
It sounds like what you're looking for is the ability to create target groups with mixed target types (both IP and instance in the same target group).  I have passed on your request to the load balancing team, and will close this issue since it's a request for a different team outside of Containers.
