### ISSUE TITLE
[EKS] Managed Windows Node Groups

### ISSUE THREAD

**Issue by tabern** [aws/containers-roadmap#584]
**What is this**
Ability to launch Managed Node Groups using EKS-optimized Windows AMIs.

**What is the problem?**
Today, EKS Managed Node Groups support EKS-Optimized Linux AMIs. Windows support will make it easier to run Windows clusters on Amazon EKS.

**Comment by ChanceLee0111** [comment]
Would the recent launch template support on the managed node group resolve/close this roadmap?

**Comment by saiteja313** [comment]
Managed Node Group (MNG) with Custom Launch Template does not support Windows at the moment. 

This is due to following reasons,

1. **EKS MNG does not add `eks:kube-proxy-windows` Kubernetes Group access for Windows worker nodes in 'aws-auth' ConfigMap**
    - EKS MNG adds only `system:bootstrappers` and `system:nodes` Groups at the moment.
    - `eks:kube-proxy-windows` Group in EKS is binded to `system:node-proxier` ClusterRole.
        - `system:node-proxier` ClusterRole allows access to Kubernetes API resources *Endpoints*, *Services* and *Nodes* that are required for node bootstrapping purposes.

2. **EKS MNG does not add below *custom labels* (EKS restricted) to worker node**

    ```
    eks.amazonaws.com/nodegroup=<MNG_NAME>
    eks.amazonaws.com/nodegroup-image=<AMI_ID>
    eks.amazonaws.com/sourceLaunchTemplateId=<LAUNCH_TEMPLATE_ID>
    eks.amazonaws.com/sourceLaunchTemplateVersion=<LAUNCH_TEMPLATE_VERSION>
    ```

**Comment by saiteja313** [comment]
Managed Node Group (MNG) with Custom Launch Template does not support Windows at the moment. 

This is due to following reasons,

1. **EKS MNG does not add `eks:kube-proxy-windows` Kubernetes Group access for Windows worker nodes in 'aws-auth' ConfigMap**
    - EKS MNG adds only `system:bootstrappers` and `system:nodes` Groups at the moment.
    - `eks:kube-proxy-windows` Group in EKS is binded to `system:node-proxier` ClusterRole.
        - `system:node-proxier` ClusterRole allows access to Kubernetes API resources *Endpoints*, *Services* and *Nodes* that are required for node bootstrapping purposes.

2. **Windows nodes take more boostrapping time than linux nodes. Due to this,  EKS MNG fails to add below *custom labels* (EKS restricted) to worker node**
    ```
    eks.amazonaws.com/nodegroup=<MNG_NAME>
    eks.amazonaws.com/nodegroup-image=<AMI_ID>
    eks.amazonaws.com/sourceLaunchTemplateId=<LAUNCH_TEMPLATE_ID>
    eks.amazonaws.com/sourceLaunchTemplateVersion=<LAUNCH_TEMPLATE_VERSION>
    ```

**Comment by Type1J** [comment]
I'd really like managed Windows nodes? Any progress here?

**Comment by paramanandd** [comment]
any update on managed windows?

**Comment by JeffreyGarrett** [comment]
Hello is there any ETA on managed node groups supporting windows?

**Comment by lukehb** [comment]
How is the WIP going? Should we expect this to be "coming soon" in 2022?

**Comment by amchech** [comment]
Any news ?

**Comment by Type1J** [comment]
@akestner It looks like this is a well watched issue. Is there anything that you can tell us?

**Comment by nascit** [comment]
This is a highly requested feature. Would love to see this in 2023.

**Comment by mikestef9** [comment]
EKS now supports Windows containers in managed node groups!

- [What's New](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-eks-automated-provisioning-lifecycle-management-windows-containers/)
- [Documentation](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html)

**Comment by supera74** [comment]
here is an workaround
https://devoriales.com/post/225
gist:  https://gist.github.com/supera74/ec6156992d234d8f2cb334e5b2b61420
