### ISSUE TITLE
[ECR] [scanning]: Include additional severity details, including NVD severity, distro severity, and CVSS score

### ISSUE THREAD

**Issue by csykora-flexion** [aws/containers-roadmap#587]
**Tell us about your request**
Verify the ECR scanning CVE results, they don't seem to match the NVD database on severity.

**Which service(s) is this request for?**
ECR container scanning (Clair)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
An image scan found the following vulnerability:
```{
                "name": "CVE-2018-16428",
                "description": "In GNOME GLib 2.56.1, g_markup_parse_context_end_parse() in gmarkup.c has a NULL pointer dereference.",
                "uri": "https://security-tracker.debian.org/tracker/CVE-2018-16428",
                "severity": "LOW",
                "attributes": [
                    {
                        "key": "package_version",
                        "value": "2.50.3-2+deb9u1"
                    },
                    {
                        "key": "package_name",
                        "value": "glib2.0"
                    }
                ]
            }
```

( Notice the severity level reported: "severity": "LOW", )

However, if I follow the link to more details about the vulnerability: [https://security-tracker.debian.org/tracker/CVE-2018-16428](https://security-tracker.debian.org/tracker/CVE-2018-16428) 
it shows the severity level: "NVD severity : high"

Why does ECR scan severity = "low" and NVD severity = "high"?
I would expect the ECR scan to also show this as a "high" severity.

**Are you currently working around this issue?**
I currently do not have a work around for this issue.

**Additional context**
I'm only pointing out 1 example here, but there are others that I have not included in this example.

**Comment by jtoberon** [comment]
Would you confirm your Linux distro name and version, e.g. Ubuntu 18.04? This probably is your base image layer. You may be able to trace back to this information via the FROM instruction in your Dockerfiles.

**Comment by jtoberon** [comment]
Based on the package_version, I'll assume you're using Debian 9 (codename "stretch").

You're right that the NVD severity is high. If you look at the Urgency column of https://security-tracker.debian.org/tracker/CVE-2018-16428, you'll see that the Debian maintainers set the severity for their distro to low. In general, we use the distro-specific severity if it's available.

**Comment by csykora-flexion** [comment]
Yes, thats correct, the Linux distro:
# lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch

**Comment by jtoberon** [comment]
@csykora-flexion I'd like to change this request to "Include additional severity details, including NVD severity, distro severity, and CVSS score." Then, if you prefer the NVD severity, you have the option of choosing that one. What do you think?

**Comment by csykora-flexion** [comment]
That sounds like a good feature to add.  By including the extra severities, we can evaluate which ever score we'd like.  Thanks for the update.

**Comment by jtoberon** [comment]
Thank for the input! I updated the title to reflect this discussion.

**Comment by 2ffs2nns** [comment]
+1

**Comment by jtoberon** [comment]
@csykora-flexion We added the CVSS score to the findings JSON under the key "CVSS2_SCORE". You can use the following information to derive the NVD severity: https://nvd.nist.gov/vuln-metrics/cvss. So, at this point, you should have two of the three additional severity details (CVSS score, from which you can derive the NVD severity). We will update our docs with this information.

The distro severity is more complicated. Different distros use different qualitative strings (e.g. "high" vs "important"). We normalize these strings, and we use the normalized result to populate our "severity". We're concerned that providing the original values would just make the scan results confusing.

Since your original question was about ECR's severity vs the NVD severity, and we've provided the CVSS score, I am going to close this issue. If anybody wants to revisit the question of whether we should provide the raw distro-specific severity string, please open a new issue.
