### ISSUE TITLE
[ECS] FARGATE_SPOT Default Capacity Provider Not Working with ecs deploy

### ISSUE THREAD

**Issue by e-moshaya** [aws/containers-roadmap#695]
I have "FARGATE_SPOT" as my default capacity provider for the ECS cluster and all the services. However, when I run aws ecs deploy it deploys fine but the launch type for the new tasks are just set to "FARGATE" instead of "FARGATE_SPOT". 

I have blue/green as my deployment type

**Comment by coultn** [comment]
This is essentially the same issue as #675

**Comment by e-moshaya** [comment]
Hi @coultn this is not the same and I believe is a bug. Once I deploy blue/green in Fargate launch type mode with FARGATE_SPOT as the capacity provider, every subsequent tasks using this service is launched using the FARGATE capacity provider. Even after scaling down the tasks to 0 and scaling back to 1 the next day. Both the service and cluster are showing FARGATE_SPOT as the capacity provider.

**Comment by e-moshaya** [comment]
@coultn have you had a chance to look at this issue? As I said, the primary issue is that we have application autoscaling schedules to scale down all services to 0. However, even though capacity provider is set to FARGATE_SPOT for all service.

When the application autoscaling schedule scales out target to 1 the next day, all tasks are launched in FARGATE launch type without capacity provider configuration. We have the ECS Cluster and all ECS SERVICES using FARGATE_SPOT capacity provider as default.

FYI, We are only seeing this issue when we blue/green deploy a new task definition. I understand that blue/green doesn't yet support capacity providers but I would expect the service to revert to the default capacity provider when desired tasks is set to 0, then back to 1 the following day. However, this is not the case

**Comment by coultn** [comment]
At this time, the CodeDeploy blue/green deployment is not compatible with Capacity Providers.  We will update our documentation to reflect this fact, and we are looking at how to change this in the future so that it will work with Capacity Providers.

**Comment by e-moshaya** [comment]
blue/green works fine but launches tasks in FARGATE launch type. My issue is that all the services in the cluster will not launch any tasks in FARGATE_SPOT mode even though the cluster and services are configured to use FARGATE_SPOT. The only way to fix this is to delete all the services and recreate them again.

**Comment by coultn** [comment]
When you say “all services” do you mean that all of those services are configured to use the CodeDeploy deployment controller?  Regardless of how the cluster is configured, any service that is using the CodeDeploy deployment controller is not compatible with capacity providers and will not use capacity providers when running tasks. So in the case of Fargate this means the service will run on FARGATE and not FARGATE_SPOT, because FARGATE_SPOT is only accessible as a capacity provider.

**Comment by travisbell** [comment]
I was just affected by this issue. The strange part to me is that the capacity provider the service says it's using continues to say "FARGATE_SPOT" after you deploy with CodeDeploy. CodeDeploy doesn't error, or throw a warning that anything is changing it simply silently falls back the service to "FARGATE".

It would be really nice to have FARGATE_SPOT supported with CodeDeploy. When #675 is complete, will is automatically bring FARGATE_SPOT support in since then CodeDeploy will be aware of capacity providers?

**Comment by travisbell** [comment]
#675 (or I guess technically, #713) was closed, but the sequence of events I described above hasn't changed. Blue/green deploys still silently turn `FARGATE_SPOT` tasks into `FARGATE`.

So I guess "BlueGreen Deployment for ECS with Capacity Provider" doesn't mean Fargate Spot is supported? Does anyone actually have that working?

**Comment by pavneeta** [comment]
Hi @travisbell , thanks for the feedback and raising the concern. 
I wanted to check if you  updated the [AppSepc](https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-resources.html) file for your ECS services in CodeDeploy ? AWS CodeDeploy uses the AppSpec file as the source of truth for the capacity provider strategy, so if you update the AppSpec file with the capacity provider strategy you want to use and trigger a deployment through CodeDeploy – that should allow you to use FARGATE_SPOT with a Blue-Green Deployment for ECS.

**Comment by travisbell** [comment]
@pavneeta Aha! It was indeed my AppSpec. As you said, it's the source of truth which I guess I didn't necessarily understand. I've got it working now, thanks for the reply.
