### ISSUE TITLE
[ECS] ECS doesn't deregister tasks from load balancer before stopping container

### ISSUE THREAD

**Issue by AlessandroLorenzi** [aws/containers-roadmap#708]
### Summary

When I stop a task, ECS doesn't deregister it from load balancer

### Description

I have an ECS service with multiple tasks, the service has a loadbalancer configured

if I run command like that:

```
aws ecs stop-task --cluster mycluster --task xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
 
I suddendly receive some 502 responses

example siege output:

```
# siege -c 1 http://myservice/uri/
HTTP/1.1 200     0.39 secs:      16 bytes ==> GET  /uri/
HTTP/1.1 200     0.39 secs:      16 bytes ==> GET  /uri/
HTTP/1.1 502     0.39 secs:     138 bytes ==> GET  /uri/
HTTP/1.1 200     0.39 secs:      16 bytes ==> GET  /uri/
HTTP/1.1 200     0.39 secs:      16 bytes ==> GET  /uri/
HTTP/1.1 502     0.39 secs:     138 bytes ==> GET  /uri/
```

this happens for 3~5 seconds.

 

The `HealthCheckIntervalSeconds * UnhealthyThresholdCount` is a longer period so I think that ECS doesn't wait the task deregistration from load balancer before stopping containers.

 

This doesn't happen when the service is scaling down.

### Expected Behaviour

 

ECS should deregister task from load balancer before sending sigterm to container

### Observed Behaviour
 
ECS deregisters task from load balancer after sending sigterm to container

**Comment by lifeofguenter** [comment]
This is important for **cluster control**. As we currently lack that without this feature.

If we look at a standard EC2/ASG/LC deployment, we can easily remove a EC2 instances by disabling them via ASG without interrupting any user experience as it would go first through targetgroup de-registration draining.

With ECS/Fargate we do not have that possibility. So killing a task will cause an immediate downtime as health checks are only post-active.

**Comment by toredash** [comment]
@AlessandroLorenzi is the ECS service by any chance using multiple target groups? We have identified an issue where ECS services that are assigned more than 1 target group, does not get drained as expected by their target group config. They simply get the stop command.

**Comment by SonicV2** [comment]
Has this been fixed? Ran a load test and manually stopped task for. Out of 30,000 requests, there was 12 502 errors.

**Comment by ianneub** [comment]
This might be related to this feature request: https://github.com/aws/containers-roadmap/issues/576

**Comment by arafat-java** [comment]
Can we get some updates on this please

**Comment by slayer** [comment]
Any news? 
AWS ECS is painful 😖 without such simple feature

**Comment by magnetik** [comment]
The same happens when using EC2 spot instance draining. The tasks are stopped, but not registered before.

**Comment by kulinsj** [comment]
I'm experiencing this downtime even when using `update-service` now - old tasks are killed before getting deregistered about 8-10 seconds later causing downtime. This is now happening with ***every*** deployment of a new task definition to all our clusters, leading to frequent front end issues when the API availability drops.

**Comment by VenkateshMakala1** [comment]
This is causing very big issue for customers. please resolve it ASAP.

**Comment by kulinsj** [comment]
As a follow up, in my case the culprit ended up being something else - the overhead on new tasks launching would cause the CPUs on the EC2 instances in the cluster to max out briefly and cause some live traffic to hit 5XX errors at the load balancer level since none of the instances were capable of processing anything else. The old targets _were_ actually being deregistered correctly from the target group, though the timestamps of the events in the ECS logs are confusing (they now say Stopped a task at the *start* of a tasks spin-down steps - before deregistration - instead of at the end - after deregistration - like it used to).

In my case, the "fix" was to tweak the deployment min/max settings on the service to prevent all of the new tasks from spinning up at once to spread out the launch overhead and avoid the single big CPU spike (so we used to use min50% max 200%, instead now we do min100% max150% which splits the laucnhing of new tasks in half). So far this has been effective at preventing the service brownouts during deployment for us. We are also looking into ideas for reducing the launch overhead itself as a more long term solution. If anyone else sees their CPUs spike to ~100% usage on the EC2 instances during deployments, this is likely to help. You may also consider using EC2 instances from the `t` family which handle occasional CPU spikes more gracefully than other types (though we haven't played around with this yet to see in practice how they handle heavy deployments)

**Comment by corddyla** [comment]
We (Amazon ECS team) have launched a set of improvements to load balancing on ECS. Amazon ECS now more accurately routes traffic to running tasks as tasks will be deregistered from the ELB before they enter a stopped state. Furthermore, with these improvements, Amazon ECS also helps your services running on the Fargate Spot capacity provider be more resilient to Spot termination notices.

[https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-elastic-container-service-accuracy-service-load-balancing/](https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-elastic-container-service-accuracy-service-load-balancing/)

Thanks,

Amazon ECS team
