### ISSUE TITLE
[ECS] [Request]: BlueGreen Deployment for ECS with Capacity Provider

### ISSUE THREAD

**Issue by yos1p** [aws/containers-roadmap#713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Before CapacityProvider, we were able to create Service and use BlueGreen deployment. I found this feature very useful. CapacityProvider is also very useful as it allow me to easily scale the instances needed for my ECS cluster.

But why is it not possible for us to use BlueGreen Deployment with CapacityProvider? The option available is only Rolling update. Is the feature going to be implemented soon? 

**Which service(s) is this request for?**
ECS

**Are you currently working around this issue?**
Currently, I use Rolling Update. But given that there will be 2 tasks running, it causes version conflict between the old and the new in one Target Group. If I stop one of the task, it will cause short 502 Bad Gateway for the load balancer.

If I try to create BlueGreen Deployment Group through CodeDeploy, it will throw error:
`Deployment group's ECS service must be configured for a CODE_DEPLOY deployment controller.`

**Comment by gnokoheat** [comment]
Plz, make it usable EC2 type-Blue/Green Deployment with CAS.
Because, EC2 is cheaper than Fargate. Blue/Green is more stable than Rolling update. And also wan to use CAS for stable service. We want to make stable service of low cost. But It has many restrictions in ECS(EC2) Blue/Green deployment now.

**Comment by slwinsett** [comment]
We would like to be able to use FARGATE SPOT with our blue/green deployments as well. Without Capacity Providers, this is not possible.

**Comment by rizblie** [comment]
Can we also include support for service discovery with blue/green?

The current CodeDeploy Blue/green solution is based on the assumption that there is a load balancer with 2 target groups. Customers need blue/green to work with service discovery too.

**Comment by smailc** [comment]
When is this likely to be implemented?

**Comment by Reli4ble** [comment]
Hi,

any updates on this Request ?

**Comment by pavneeta** [comment]
This feature is now generally available. You can use capacity Providers with services using Blue Green deployments using CodeDeploy.

**Comment by eyedean** [comment]
@pavneeta picking "Blue/Green Deployment" is disabled in the console for me at the time of service creation, if I pick a Capacity Provider.  Am I missing something?

<img width="613" alt="Screenshot at Apr 20 14-53-43" src="https://user-images.githubusercontent.com/5694695/115468728-5a09ac00-a1e8-11eb-898c-2227c933920b.png">

**Comment by dhedey** [comment]
Hi @pavneeta thanks for sharing the news! Although, I thought I'd submit my experiences of it not really working right: (not knowing about this previous incompatibility), I created this combination fine via the API with Terraform (which was allowed) but then the cluster didn't actually expand automatically.

In particular, when the Deployment tried to create new tasks in the new Task set, this just hanged essentially waiting for deployment of the new task set. Checking out the Service's Event log, I saw a message such as this:

```
service [redacted] was unable to place a task because no container instance met all of its requirements. The closest matching container-instance [redacted] has insufficient CPU units available. For more information, see the Troubleshooting section.
```

I'd have expected that the service would ask the capacity provider to scale up by the appropriate amount and wait for these instances to spin up, but that didn't seem to happen, it just seemed to panic and do nothing.

I appreciate this isn't the right forum for seeking help, but I wanted to flag up that this feature may not be working quite as planned (or maybe I'm just misunderstanding how this should work).

NB: I also note the same UI when creating a task as eyedean.

**Comment by navied** [comment]
We are seeing the same issues, trying to go over it with AWS support right now. Will let you know if there is any resolution. 

The tasks never launch and go into "provisioning" therefore the capacity provider never knows to scale up. This is basically the issue that was happening before it was "implemented".

**Comment by eyedean** [comment]
Thank you @dhedey and @navied for confirming the issue.  I found a workaround for the UI bug (probably not implemented in the console yet) and updated [my comment above](https://github.com/aws/containers-roadmap/issues/713#issuecomment-823625476).

The main issue still persists though @pavneeta.

## Our Setup ##
1. We have a docker container that is a Node.js web app and we update it frequently.  We push our new images to ECR.
2. We have a Task Definition where we have set it to take 500MB Memory and a static port.
3. We have an ECS Cluster that has a Capacity Provider properly tied to an Auto Scaling Group in EC2 to spin up t3.micro instances (947MB Memory available.)  It has the minimum capacity of 1 and the maximum capacity of 5 instances 
4. We have a Service that takes the Task Definition, has the Capacity Provider of the cluster, and is tied to Blue/Green Deployment in CodeDeploy.  The Task Placement strategy is also DistinctInstance, as it has a fixed port.

## What We Need for Deploys ##
0. Let's assume there is only one EC2 instance in the cluster, already running the service properly.
1. We push the new docker image to ECR.
2. We update the Task Definition to get the new Container Image version.
3. We need to now do a Blue/Green deploy of the new version, with the new Task Definition version.

## What Happens (Actual) ##
* After around 30 seconds of starting the deploy (either from CodeDeploy directly, or by updating the service and checking the force-new-deployment) it keeps complaining that: 
```
service <our-service-name> was unable to place a task because no container instance met all of its requirements.
The closest matching container-instance <the-id-of-the-already-running-container> has insufficient memory available. For more information, see the Troubleshooting section.
```
<img width="1128" alt="Screenshot at Apr 21 13-36-43" src="https://user-images.githubusercontent.com/5694695/115617910-d6fb5b00-a2a6-11eb-8d00-ec3d817fe206.png">

Clearly, the available memory is 487MB which is less than 500MB that it needs -- I deliberately put it like that, in case it doesn't honor **DistinctInstance** Task Placement Strategy of the service, to avoid having two containers of the service in the same instance.  The question is, **Why is it not spinning up a new instance via ASG, instead of complaining?**


## What Should Happen (Expected) ##
* It should see that a new instance is needed (both for DistinctInstance, and for the memory) and spin up a new one using ASG.

## Further Notes ##
* The ASG works as expected when I increase the **Number of Tasks** in the service from 1 to 2.  It spins up a new instance, and everything works smoothly. **So nothing is wrong with the Service communicating to ASG.**
* If I manually increase the number of instances in the cluster, then everything works perfectly and the deploy proceeds as expected till the tend in CodeDeploy. **So, nothing is wrong with the CodeDeploy and blue/green set-up.**
* I spent 5 hours trying out everything I could think of and could play with, including different Task Placement Strategies, different Health check percentages, different Service Auto Scaling values (it's different from EC2 Auto Scaling, I know), but nothing worked.

**Comment by eyedean** [comment]
# Big update! Found a **relatively** simple workaround

From [this comment](https://github.com/aws/containers-roadmap/issues/695#issuecomment-813109530) of @pavneeta I guessed that I could explicitly tell CodeDeploy's [AppSpec](https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-resources.html) to use the cluster's Capacity Provider.

Here is the AppSpec I put for a new Deployment *in CodeDeploy* and worked like a charm!
```

{
  "version": 1,
  "Resources": [
    {
      "TargetService": {
        "Type": "AWS::ECS::Service",
        "Properties": {
          "TaskDefinition": "arn:aws:ecs:us-west-2:<MyAccountNumber>:task-definition/<MyTaskDefinitionName>:19",
          "LoadBalancerInfo": {
            "ContainerName": "<MyContainerName>",
            "ContainerPort": <MyContainerPort>
          },
          "CapacityProviderStrategy": [
            {
                "CapacityProvider": "<MyCapacityProviderNameFromECSCluster>",
            	"Base": 0,
                "Weight": 1
            }
          ]
        }
      }
    }
  ]
}
```

Ideally, it could be auto-discovered; but for now, I am good. :)  Thanks again @pavneeta for your insightful comment on the other ticket! <3

**Comment by ashwinikumar-sa** [comment]
For “updating an existing service to use capacity provider strategy with Blue/Green deployments with CodeDeploy”. it is recommended to specify CapacityProviderStrategy for deployment with existing service in “appspec” file’s resources section. Please refer below CodeDeploy documentation:https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-resources.html#reference-appspec-file-structure-resources-ecs.

However, I think ECS Capacity Provider documentation should also be updated. will be good to have an example

**Comment by LilDrunkenSmurf** [comment]
> Hi @pavneeta thanks for sharing the news! Although, I thought I'd submit my experiences of it not really working right: (not knowing about this previous incompatibility), I created this combination fine via the API with Terraform (which was allowed) but then the cluster didn't actually expand automatically.
> 
> In particular, when the Deployment tried to create new tasks in the new Task set, this just hanged essentially waiting for deployment of the new task set. Checking out the Service's Event log, I saw a message such as this:
> 
> ```
> service [redacted] was unable to place a task because no container instance met all of its requirements.
> The closest matching container-instance [redacted] has insufficient CPU units available. For more information, see the Troubleshooting section.
> ```
> 
> I'd have expected that the service would ask the capacity provider to scale up by the appropriate amount and wait for these instances to spin up, but that didn't seem to happen, it just seemed to panic and do nothing.
> 
> I appreciate this isn't the right forum for seeking help, but I wanted to flag up that this feature may not be working quite as planned (or maybe I'm just misunderstanding how this should work).
> 
> NB: I also note the same UI when creating a task as eyedean.

I'm having similar issues with TF. We're currently running 3 tasks across 2 EC2 containers. If I manually increase it to say, 9, it will put up a 4th task, and then start spitting out errors about how it was unable to place task due to lack of memory. It will not spin up additional EC2 hosts. 

If I manually increase the hosts on the ASG, it will then spin up those tasks. If I then scale down to 3 tasks, it will then slowly take down tasks, and scale-in properly.

This means during blue/green deploys via CI/CD, it will spin up 1 new task, with the latest revision, and then be unable to spin up the other two, meaning I'm running 3 old tasks, and 1 new task.

The only command we run is `aws ecs update-service --cluster [redacted] --service [redacted]  --task-definition $(cat ECSTaskDefinition/[redacted].json | jq -r ".family")`

**Comment by Ruman1996** [comment]
@eyedean, Thanks for your comment, when I mention my capacity provider in appspec file code deploy is able to provision new instance if requirements are not met, but in this we are deploying app, but still the ecs service with blue/green deployment, when stopped(made desired no.of task to 0) and when started(changed no. of task in service to 1) with no existing ecs instances in cluster fails with error **"service <service-name> was unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your cluster. For more information, see the Troubleshooting section"** .
I have default capacity provider for my cluster, same is used in service capacity provider section. 
Capacity provider is working fine for Rolling deployment type, its able to spawn new instance when requirement is not met, facing this in B/G deployment only and I still faced that UI issue which you mentioned [disabled B/G deployment option when capacity provider provider is slected during service creation].

@pavneeta Need help as running code deploy everytime when I need to start task will not help.

**Comment by eyedean** [comment]
I am back here again and the only thing I still need to tell myself is: "**No matter what you do, there is no reliable way to have an ECS service pick an ASG for its update/deploys in the Console/UI.**"

I keep facing the following no matter how I wire an ASG to Service (e.g. via its own properties, or cluster's) when I go to Service > update > "force new deployment".
```
service <XXX> was unable to place a task because no container instance met all of its requirements. The closest matching container-instance <YYY> has insufficient memory available. For more information, see the [Troubleshooting section](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/troubleshooting.html).
```

Still, the only thing that works is creating an AppSpect as per [this comment](https://github.com/aws/containers-roadmap/issues/713#issuecomment-824369017).

It makes 0 sense when a service has a CapacityProvider in its config, it faces that "no container met" error in the first place.  And the CapacityProvider works perfect if you just kick it via a deploy in CodeDeploy via AppSpec.  I am baffled that this bug is still around for years.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/5694695/169663327-e9af2415-794e-4c03-9ba8-657876c52d21.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/5694695/169663365-0ae1042c-da6c-40e2-8c6b-367decb1aa02.png">

**Comment by eyedean** [comment]
I just looked at the deploy that fails and causes that "unable to task because no container" error.

The bug is, when ECS Service "update" is kicking a deploy it fails to add `CapacityProviderStrategy` (filled with its own CapacityProviderStrategy) to the AppSpec file.

I am going to create a separate ticket as this one is closed and the bug is flat out there.
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/5694695/169664107-1a5e9136-a40a-4617-8dcb-ed789ba33f7c.png">

**Comment by ManikandanKF** [comment]
I still don't see any any option to enable Capacity provider along with Blue Green deployment. Is there any timeline for this feature?

**Comment by EmViKay** [comment]
the same question, as @ManikandanKF  when it will be available?

**Comment by aviv-abdoulayecoulibaly** [comment]
you can add livecycle in your aws_ecs_service ressource to ignore capacity provider 
<img width="1003" alt="image" src="https://github.com/aws/containers-roadmap/assets/137073914/98734a64-439a-4750-85fc-62a80fac36da">
