### ISSUE TITLE
[EKS]: How to upgrade worker nodes created by eksctl?

### ISSUE THREAD

**Issue by mrichman** [aws/containers-roadmap#72]
What's the procedure for updating existing worker nodes created by `eksctl`? The [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/update-stack.html) want us to update the existing stack with this template: `https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2018-12-10/amazon-eks-nodegroup.yaml`.

This is obviously not the same template that `eksctl` uses.

Should this be done using `eksctl` somehow, or should we be updating the CloudFormation stack that `eksctl` creates?

Assume I've already upgraded my cluster (i.e. from 1.10 to 1.11) and I've replaced `kube-dns` with CoreDNS.

**Comment by whereisaaron** [comment]
@mrichman the current approach with `eksctl` is to create a new updated node group, e.g. with a newer AMI for a new version of k8s or different options, then drain and delete the old node group.

There is [discussion](https://github.com/weaveworks/eksctl/issues/443) of adding a `--replaces` option to `create nodegroup` so this can be a one-step process.
https://github.com/weaveworks/eksctl/issues/443

So the `eksctl` process is more like the 'Migrating to a New Worker Node Group' AWS documentation. But easier... 😄 
https://docs.aws.amazon.com/eks/latest/userguide/migrate-stack.html

**Comment by astleychen** [comment]
Can someone advise how to migrate an on-demand node group to spot-instanced node group over eksctl? From [doc](https://eksworkshop.com/spotworkers/workers/) here, it seems not able to modify the CFn directly to make the change.

**Comment by tabern** [comment]
By design - standard eksctl node groups are immutable. See https://eksctl.io/usage/managing-nodegroups/#nodegroup-immutability

However, if you [create EKS Managed Node Groups using eksctl](https://eksctl.io/usage/eks-managed-nodes/) these can be upgraded.

Create an eksctl MNG `eksctl create nodegroup --managed` or `eksctl create cluster --managed` 
Upgrade an eksctl MNG `eksctl upgrade nodegroup --name=<mng name> --cluster=<cluster>`
