### ISSUE TITLE
[ECS] distinctInstance placement constraint for a service is incompatible with tasks going to provisioning when managed scaling is enabled

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#723]
Creating a service with a ```distinctInstance``` placement constraint is not interacting with managed scaling correctly.  For example, if you create a service like so : ```aws ecs create-service --cluster MYCLUSTER --task-definition MYTD:1 --service-name MYSERVICE --desired-count 2 --placement-constraints type=distinctInstance --capacity-provider-strategy '[{"capacityProvider":"MYCP","weight":1}]' ``` where ```MYCP``` is an ASG capacity provider with managed scaling enabled, and there is only one instance in the ASG, the service will not cause the second task to go to provisioning.  Instead, the service event messages shows the error ```(service MYSERVICE) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance <instance-id>) encountered error \"DistinctInstance placement constraint unsatisfied.\". For more information, see the Troubleshooting section of the Amazon ECS Developer Guide```

**Comment by regevbr** [comment]
Hi @coultn is there an estimate on this issue? It is causing me real pain as I only get automatic scale in and I have to to the scale out manually...
Thanks

**Comment by petreikis** [comment]
I also ran into an issue related to "distinctInstance" placement constraint when using managed scaling. Not sure if the root cause is the same.

My service could not reach a steady state and was scaling in and out between 1 and 2 instances even when the desired count was set to 1 and autoscaling was turned off. Removing "distinctInstance" placement constraint fixed the problem.

I have also found out a temporary workaround: binding containers to a fixed host port prevents ECS from trying to place two instances on the same host even when "distinctInstance" placement constraint is removed.

**Comment by toredash** [comment]
> I have also found out a temporary workaround: binding containers to a fixed host port prevents ECS from trying to place two instances on the same host even when "distinctInstance" placement constraint is removed.

Thank you for sharing your workaround, I'm in the same boat and didn't think about using host ports to work around this issue.

**Comment by toredash** [comment]
@coultn I've discovered a bug / issue with placement constraint that are similar to this. When updating a deployment from NOT using a capacity provider, to using one, the ECS service will never reach READY state, even if there are container instances available. 
AWS Case ID 6946706501

**Comment by anoopkapoor** [comment]
This has now been resolved and is available in all regions.
