### ISSUE TITLE
EKS free tier

### ISSUE THREAD

**Issue by runningman84** [aws/containers-roadmap#78]
It would be great to have a free tier of EKS which might even run in a non HA control plane setup. Other providers like Google offer similar free services.

**Comment by dasgoll** [comment]
That would be awesome!

**Comment by NauxLiu** [comment]
Please make this happen, I don't want to pay $150 per month for dev, stg clusters.

**Comment by mitchellhuang** [comment]
GCP: $0
Azure: $0
DigitalOcean: $0
AWS: $144/month
Reddit discussion: https://www.reddit.com/r/aws/comments/aa7vrc/eks_pricing/

**Comment by countspongebob** [comment]
We view EKS as a production-grade service, and always want to be sure we are providing a high level of availability. We are going to work to reduce the control plane costs as well so that you can have both HA and low cost without worrying about whether the availability of the service is a corner you should cut.

**Comment by phil-lgr** [comment]
@countspongebob as a consultant I just setup a demo on EKS, and I have to leave it running (CI is enabled), I'm proposing this EKS based solution to my client — the problem is I have to pay $191 CAD per month.. and guess what the dev team like my EKS setup and we will use it

it's sad that dev / consultant will have to assume the costs to prepare demo or test workload.. I'm planning of running my demos on G Cloud for that reason

if we could have a limited version of EKS, with e.g. limited set of machine or max node = 2 with no autoscaling that would make a lot of devs / consultant happy

**Comment by rverma-nikiai** [comment]
@countspongebob still waiting for an announcement from aws team regarding price reduction as per your comment.

**Comment by JnMik** [comment]
I'm using EKS and was planning to minimize cost by scaling down the autoscaling group to zero instances outside business hours (in all environments but prod), but then I see there is still charges for the control plane. Eurk.

SO I'll have to use gitlab pipelines to _terraform destroy_ completely the cluster... (And it takes forever to destroy / create with terraform). Eurk.
 
You really should address that control plane pricing to AT LEAST don't charge it if their is no workers attached. 


Cheers

**Comment by rverma-nikiai** [comment]
@countspongebob Seems like this ticket was closed arbitrarily without closure on your comment. The rationale for such a high price is totally not justified for personal or small projects and we should have an option for low-cost control-pane.

**Comment by xanather** [comment]
Just started getting into Kubernetes and wanted to integrate with some cloud providers as a learning experience. $144 USD a month just do try out AWS is a joke. Will go elsewhere.

I suggest re-opening this issue.

**Comment by mhausenblas** [comment]
@xanather I think it's a fair statement to say that one votes with their feet if they do not like a certain offering. It's a free market and you should use what you feel most comfortable with. Of course I'm sad to learn you don't want to give EKS a chance because of the costs. If you do want to give EKS a try and want $$$ is the only thing that interests you, there are ATM and going forward these options:

1. Keep an eye on #45
1. You can give [EKSphemeral](https://eksphemeral.info/) a try, I wrote it for this purpose

Calling it the offering many folks put a lot of time into a joke is hurting, but I suppose that's something we have to live with.

**Comment by matthewcummings** [comment]
@mhausenblas I won't use the same language as @xanather but this would be a nice feature. I spun up an EKS cluster in my personal account recently, just to test some things out. I accidentally left it running for a few days and was billed $30 for it. Sure, that was my mistake but I had no intention of using that cluster in production. Offering a trial/free-tier option for the control plane would complement AWS' other free-tire options quite well.

**Comment by rpivo** [comment]
I don't think it's a joke, but it would be great if there was a free tier option for devs who like AWS and are wanting to explore using Kubernetes with it. It might even help AWS in the long run by introducing many more devs to the idea of deploying production Kubernetes clusters on AWS.

**Comment by humberaquino** [comment]
+1 @rpivo

Also think offering a few EKS pricing options will benefit AWS and developers. K8s needs node workers to run and they normally need to be m3.medium or larger. Then, we'll normally want a managed DB (i.e. RDS), at least one ELB, ECR for images, CodeBuild/CodePipeline for deployments and so on.

Perhaps something like:
* Free for single managed master (~99.9% SLA), up to 5-10 nodes of max size X.
* Something in between?
* 144 USD for the full HA unrestricted deployment.

**Comment by mitchellhuang** [comment]
Let's be honest here, they could even make the HA plane completely free like every other provider and make profit as usual from the running EC2 instances and bandwidth usage of the node pools.

**Comment by emanuelecasadio** [comment]
I understand the reason to pay for the EKS, but Google offers its GKE High-Available master free of charge. While $144/mo is not a game changer, it is quite annoying for your customer base and limits the capability to deploy multiple clusters.

**Comment by runningman84** [comment]
Another option would be to include eks in the new saving plans.

**Comment by phgn0** [comment]
Please consider this issue. A Kubernetes cluster with very low requests/s should not cost $144/month. 

I have to use GCP until this is addressed, so am also slowly moving all my other services there too.

**Comment by francis-edejer** [comment]
FWIW The 50% price reduction is a step in the right direction. However, this still impedes self-learning and exploration. As AWS and Kubernetes become more mainstream and integrated, a lot of aspiring DevOps and Developers will need free tier access on this service to experiment and catchup. Hope this is still being considered.

**Comment by ysaakpr** [comment]
Very much a case with me as well. Many time while consulting and suggesting cloud provider to go with many non funded startup, i get to this problem, where no node cluster the team forced to have a payment to start with k8s in AWS, while other cloud providers are providing it for free. Since k8s have grown to a level where its becoming defacto std for container running with lots of CI/CD tools and practices available. Looking forward to see a free master plan, at least to include 1 EKS cluster to free plan, the next can be charged, and I believe that going to be the case for consultants and entry level startup where costing is the biggest concern, every penny needed to be saved for a long run. 

Made me to move out to google cloud for my two clients, and had to suggest google cloud as a better to afford platform.

**Comment by cdullrich** [comment]
For maximum adoption of AWS as a cloud solution, a limited developer free tier option seems like a no-brainer. When I'm shopping for solutions, I may do some spikes to look over whichever option is easiest to deploy and manage and if one option costs money to do basic exploration of the product, it will be the lowest on our list. Also, as a DevOps engineer, if I am able to study EKS on my own and end up in a workplace shopping for a cloud/orchestration solution, I can be an advocate for AWS if I have adequate knowledge and experience with it.

**Comment by raspitakesovertheworld** [comment]
This is unacceptable to charge customers for trying this out and doing a demo. Google does much better with their Kubernetes service, which you can try out for free. Considering that Google also offers much better tools for K8s, Amazon will lose customers for this one. In my case, I will go with GKE.

**Comment by rverma-nsl** [comment]
Not sure why amazon cannot bear a cost of mere 72$ per customer when they know they can recover it with ec2. I am also in favour that they should provide 1 free eks cluster as free tier.

**Comment by mitchellhuang** [comment]
Yeah the pricing strategy here is pretty bad. This is not the Bezos way of capturing the entire market first at whatever cost, without concern for profit. Idk what they are thinking over there at the AWS office... this entire price debate is likely a rounding error for them. At the cost of preventing thousands of developers coming onto their k8s platform. Thankfully the ecosystem has developed to where we have things like [kops](https://github.com/kubernetes/kops/) and [typhoon](https://github.com/poseidon/typhoon) to help lower our operating costs and run masters on cheaper instances. But at the end of the day many people do not want to deal with this low level of the abstraction and will instead go to GKE.

**Comment by raspitakesovertheworld** [comment]
GKE is actually really amazing, they offer a lot more tools, you can tell that Google invented Kubernetes. AWS offers many free tiers for demos and learning, but paying just to learn or evaluate their EKS system is kinda ridiculous and unacceptable.

**Comment by joebowbeer** [comment]
Are there other channels that can be used to lobby for this?

This issue is extremely popular, as evidenced by the many thumbs up, but it is probably outside the core purpose of this extremely useful roadmap, which is focused on issues that the AWS developers themselves can fix. And it is closed.

**Comment by mreferre** [comment]
Thanks for the continue feedback and passion around this topic. As Bob alluded to, running a fully redundant K8s control plane across 3 AZs costs a reasonable amount of money. Having that said, we know customers love and appreciate when we lower prices and we are always looking for opportunities to do so. We however want (and have) to do this in a way that is sustainable. For us customer trust is super important and we don't want to give false expectations. The pattern we have always used (and continue to use) is to lower the cost of running the services and passing over the savings to our customers. We would hate to find ourselves in the odd situation of making wrong decisions that would force us to revisit them down the road. This is what we have done last year when we cut the costs of the control plane in half. I can't commit that we will be able to cut it again and/or bring it to 0 but rest assured this ask is well understood and it's discussed regularly within the team.

**Comment by raspitakesovertheworld** [comment]
You might be misunderstanding what I'm saying. I'm not saying EKS is too expensive. Kubernetes is a large scale service and enterprice grace, with a price point to fit. The point that I'm making is that you don't allow a test drive or learning. I have a friend that learned AWS with the free tier, but he won't be learning EKS, because to do labs, learning YOUR system, he would have to pay for that, which does not make sense at all. I recommended to him to go for the Google Kubernetes Engine, which has a 90 day free trial. It is a small setup, but they give you 300 dollars to spend in that time on the nodes and pods. This is enough to learn and trial it. It offers a lot more than what Amazon does by the way, so you not allowing a free limited time trial (like you do with the rest of AWS for learning purposes) just makes your offerings look bad.
Remember: This is just to demo or learn, it is obvious that you can't use this for anything serious, as it is too limited in the free trial stage. I would think this must just be a mistake on your side, because why would you charge for all EKS Kubernetes use, while EC2 instances can be run for free in a learning situation? I doubt that people will pay you just have the privilege to learn your Kubernetes system. ESPECIALLY since Google offers a lot more, they invented Kubernetes and it shows, the dashboards and everything are much better integrated and there is a lot more automation out of the box.

**Comment by ysaakpr** [comment]
Absolutely agree with @raspitakesovertheworld , There are a wide set of users, who want to either try to experiment, or probably demonstrate certain usecase, on a day to day bases or need basis. Especially after kuberntes has become a de-facto mode for contain orchestration, a way to demonstrate and try k8s eco system in aws is a must. Many time i had situations where my clients/friends, who had to setup things on aws cloud had choosen to go with Google cloud, even though i recommended to use aws(since it has better / more managed products available), but due to the pricing model to try things aws has become difficult and later had to move, once the company had sufficient balance. I would recommend AWS to provide at least one cluster on free of cost, and that gonna be a boost for many startups, where saving every penny leads to more time to live.

**Comment by mreferre** [comment]
@raspitakesovertheworld your point is clear and we understand the value of what you are proposing. Yes, providing a less redundant setup would be one way to achieve that. Nothing is off the table right now and I was not suggesting there is one way to lower/eliminate the price.

**Comment by synek** [comment]
Having an EKS free tier would make it much easier for me to grow prototype products into larger-scale products in the AWS ecosystem. Right now I'm forced to either a) start with ECS and then transition to EKS once the product grows, or b) start with GCP and transition the k8s deployment to EKS or transition the rest of the stack to GCP.

Both of these situations are frustrating and ultimately they both lead to fewer of my production workloads running on AWS, and GCP becoming a more enticing option because no transition is necessary.

**Comment by raspitakesovertheworld** [comment]
I don't know who has influence here on the decision makers of AWS, but you want to maybe bring this problem to the attention to the people in charge and fix this: Bring EKS in line with all the other product offerings on AWS: offer a free tier for evaluation. Evaluations are low resource use anyway, nobody will ever consider to try to use this productively, just having 2 nodes a low cpu resources won't be "abusable" for something as resource intensive as Kubernetes. I'm sure this must be an oversight and you don't want to alienate your first time EKS customers and driving them to do trials on other platforms and then maybe find that the Google Kubernetes Engine works really well.
A friend of mine wants to learn EKS and terraform, but does not want to pay for trial use to learn AWS technology so he is learning GKS and terraform instead.

**Comment by parkournerd** [comment]
I'm advising all my developer friends that need to experiment with kubernetes to go with Azure unless this changes.

**Comment by Pkmmte** [comment]
As a long-time AWS customer, the lack of a free EKS tier has pushed me towards Google Cloud.

I wasn't willing to spend $72 just to learn about EKS, so I decided to try out Google Cloud clusters instead. As a result, it made me more familiar with Google Cloud and pushed me towards deciding to migrate an existing infrastructure from AWS over to Google Cloud. I voted with my wallet and I suggest others do so too if they feel strongly about this.

**Comment by SodaGremlin** [comment]
Exactly this... shame, I like some AWS stuff a little more. They are pushing ECS to platform lock people in I think. Also AWS has the fewest management/upgrade tools of all three for the control plane and connected nodes. 

GCP is my new friend, and I do miss my old one. AWS win me back!!!

> As a long-time AWS customer, the lack of a free EKS tier has pushed me towards Google Cloud.
> 
> 
> 
> I wasn't willing to spend $72 just to learn about EKS, so I decided to try out Google Cloud clusters instead. As a result, it made me more familiar with Google Cloud and pushed me towards deciding to migrate an existing infrastructure from AWS over to Google Cloud. I voted with my wallet and I suggest others do so too if they feel strongly about this.

**Comment by ivannedyalkov** [comment]
its 2024 guys...

**Comment by azN2** [comment]
This wont happen.

**Comment by florentsorel** [comment]
Almost 2025... I will try DOKS (digital ocean).

**Comment by jeroenhabets** [comment]
its 2025 guys...
