### ISSUE TITLE
[ECS] [BUG]: Use of full arn on service capacity provider strategy

### ISSUE THREAD

**Issue by lays147** [aws/containers-roadmap#784]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When using Terraform/AWS Cli to set up a Service on an ECS Cluster using a Capacity Provider, on the [docs say](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CapacityProviderStrategyItem.html) that we can use the name of the Capacity Provider or the ARN. 

When using the following command where I use the CP ARN:

`aws ecs create-service --service-name lays-rabbit --task-definition my_task:1--cluster lays-teste-ecs-cluster --desired-count 1 --network-configuration "awsvpcConfiguration={subnets=[],securityGroups=[],assignPublicIp=DISABLED}"  --capacity-provider-strategy capacityProvider=arn:aws:ecs:us-east-2:aws-account:capacity-provider/my-capacity-provider,weight=1,base=1  --region us-east-2
`
The following error happens on service events on the console:

> service lays-rabbit was unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your capacity provider. For more information, see the Troubleshooting section.

But if I use the following command:

`aws ecs create-service --service-name lays-rabbit --task-definition my_task:1 --cluster lays-teste-ecs-cluster --desired-count 1 --network-configuration "awsvpcConfiguration={subnets=[],securityGroups=[],assignPublicIp=DISABLED}"  --capacity-provider-strategy capacityProvider=my-capacity-provider,weight=1,base=1  --region us-east-2
`

My task get up and running within the service without any problem.

**Are you currently working around this issue?**
I use the Capacity Provider Name.

**How to fix it**
1) Fix the use of the full arn when configuring the capacity provider strategy on the ECS 
Service.
**or**
2) Use only the capacity provider name when configuring  the capacity provider strategy on the ECS Service.

**Comment by henriquesantanati** [comment]
I can confirm this behavior. Looking at the CreateService API documentation [1] you can see that the type is an "Array of CapacityProviderStrategyItem objects"

And looking at the "CapacityProviderStrategyItem" API the capacityProvider property description is "The short name or full Amazon Resource Name (ARN) of the capacity provider."

That said, trying to use the ARN on this property, the ECS Service events tab shows the error: "No Container Instances were found in your capacity provider".

I think that the best way to fix it is changing the documentation in order to use only the Capacity Provider Name instead of ARN.

[1] https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html#ECS-CreateService-request-capacityProviderStrategy
[2] https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CapacityProviderStrategyItem.html#ECS-Type-CapacityProviderStrategyItem-capacityProvider

**Comment by pavneeta** [comment]
@henriquesantanati @lays147 Thanks so much for your feedback and surfacing this issue. We are currently looking into the problem and I will update the GitHub issue with mitigating steps once we are able to replicate the problem on our end.

**Comment by anoopkapoor** [comment]
[Documentation ](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CapacityProviderStrategyItem.html) has been updated to reflect "The short name of the capacity provider."
