### ISSUE TITLE
[Fargate] [request]: Fargate Spot Connection Draining Improvements/Directions

### ISSUE THREAD

**Issue by hlarsen** [aws/containers-roadmap#797]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We're looking into Fargate Spot and were wondering if there were improvements to connection draining for Load Balancers coming, such as the ECS Spot Automatic Connection draining. If not, what is the current recommendation for handling this when the termination notice goes out?

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We want to make sure terminating Fargate tasks are seamlessly replaced without just being killed.

**Are you currently working around this issue?**
We're looking into Fargate Spot now; we use normal Farge and ECS Spot with automatic connection draining.

**Comment by Sytten** [comment]
This is critical to any sane usage of fargate spot in production. Could we at least get a work around?

**Comment by toredash** [comment]
@Sytten @hlarsen 
The workaround should be something like:
1) Detect that a Spot task is pending termination
Seems the only way to detect this is via CW Events: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-capacity-providers.html#fargate-capacity-providers-termination - For EC2 there is an API (https://aws.amazon.com/blogs/aws/new-ec2-spot-instance-termination-notices/) available for this information but it does not seem it is available for Fargate Spot

2) De-register the target in the Target Group
Could be done with CW Events Rule => Lambda.

We do the above currently for EC2 Spot termination, but instead of removing the task target from the target group, we issue an ECS Container Instance DRAIN command to remove all tasks from the EC2 host gracefully. But the principle is the same.

I would check an Fargate Spot in meta-data API further to see if that information is present (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html) but from the looks if it isn't present.

I just saw that you could as well block the SIGTERM handler to do a graceful shutdown (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-capacity-providers.html#fargate-capacity-providers-termination). The workflow would then look like this:
1) Interrupt SIGTERM in your container
2) Once SIGTERM is detected, return false on health check generated by the Target Group (not to be confused with the Docker health check)
3) action nr 2 should label the target in your Target Group as unhealthy, and not send more requests towards it. I haven't checked, but I assume in-flight requests would be allowed to finish (e.g. WebSocket connections)

Hope this gives some input on what could be done

**Comment by hlarsen** [comment]
@toredash thanks for the reply. fyi unless i'm missing something you no longer have to do that for EC2 Spot Terminations, it should be taken care of automatically by _Automated Draining for Spot Instances_, correct? it's working well for us.

this type of thing is more what i'm asking about - the cw event > manual draining solution was used by many people for EC2 before it was automated by AWS so users didn't have to deal with the extra automation, make sure it works, monitor the additional automation, etc etc.

if AWS is planning on doing the same Automated Connection Draining for Fargate Spot i don't want to waste time with the extra automation if we can just wait a few months as moving to Fargate Spot isn't a huge priority for us.

**Comment by toredash** [comment]
> @toredash thanks for the reply. fyi unless i'm missing something you no longer have to do that for EC2 Spot Terminations, it should be taken care of automatically by _Automated Draining for Spot Instances_, correct? it's working well for us.

That is correct, but we don't use that feature as we have built our own logic to reduce the chances of downtime. Our solution is based on CloudWatch Events, were we listen to Spot Termination signal, and trigger a lambda. Said lambda will check if the EC2 node is part of an ECS Cluster _and_ ASG. If yes, it will label the EC2 node as unhealthy in the ASG at once, so that the ASG will request a new spot instance at once. Then it will drain the node as normal. With this we have new capacity ready before the terminating spot instance is reclaimed by AWS.


> 
> this type of thing is more what i'm asking about - the cw event > manual draining solution was used by many people for EC2 before it was automated by AWS so users didn't have to deal with the extra automation, make sure it works, monitor the additional automation, etc etc.

True, but we continue with our own approach because of what I've written abov.e

> 
> if AWS is planning on doing the same Automated Connection Draining for Fargate Spot i don't want to waste time with the extra automation if we can just wait a few months as moving to Fargate Spot isn't a huge priority for us.

I have no idea if they intend to, my building this into the container should not be that difficult, but that of course depends on your application.

**Comment by ArnoldKell** [comment]
We just ran into the same issue, as we are looking into migrating from EC2 to Fargate. Is this something we could see in the near future or should we just write a lambda function that handles the Spot Termination signal like @toredash mentioned?

**Comment by jicowan** [comment]
https://gist.github.com/jicowan/ad5e13d12577b41a22f83ed91a3e61bf

**Comment by git-josip** [comment]
@jicowan thank you for this lambda code. 
IS this meant to run periodically checking state of targets or to be triggered by EventBridge event?

**Comment by jicowan** [comment]
@git-josip ECS task state change.  I will try to get permission to publish this to AWS samples along with a decent README.

**Comment by git-josip** [comment]
@jicowan thank you. 
I'll try to put this in terraform scripts so that it is automated. Once I am done I'll share it here.

**Comment by git-josip** [comment]
@jicowan 

https://github.com/git-josip/terraform-fargate-spot-targatet-drain


# terraform-fargate-spot-targatet-drain

Terraform scripts for deploying lambda for de-registering load balancer targets on FargateSpot interruption.

- lambda function code that is used here is written by @jicowan on issue: https://github.com/aws/containers-roadmap/issues/797
  Lambda for de-registering tasks: https://gist.github.com/jicowan/ad5e13d12577b41a22f83ed91a3e61bf
- EventBridge rule is created based on: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-capacity-providers.html#fargate-capacity-providers-termination

## How to

### Overview

All commands are defined in `MakeFile`.
You do not need to have installed `go` or `terraform` environments on your computer.
All commands are executed in inside docker image which needs to be build at the beginning.  

### Init - Build Docker image

At the very beginning we need to build image which will be used laetr for other commands.

Command: `make build` will build local `git-josip/aws-lambda-deregister-targets-fargate-spot` image. In that image we initialize terraform with our terraform configuration. 
Check `DOckerFile` for details.

### Source code compile

To compile your source code, run `make compile`. 
With this command executes `go build` command in docker Go env.
After this command we have new `build/` folder created containing compiled program.
All terrafrom tasks are depending on this one so we do not execute it when runnign `plan` or `apply`

### Terraform commands

`plan`, `apply` and `destroy` are supported terraform commands.
WIth `plan` we will just get output what resources will be created.

In order to run these commands we need to pass AWS acces,secret and region params to make. 

- `make awsDefaultRegion=eu-central-1  awsAccessKey=accessxxx   awsSecretKey=secretxxx plan`
- `make awsDefaultRegion=eu-central-1  awsAccessKey=accessxxx   awsSecretKey=secretxxx apply`
- `make awsDefaultRegion=eu-central-1  awsAccessKey=accessxxx   awsSecretKey=secretxxx destroy`

**Comment by git-josip** [comment]
@jicowan I've updated lambda code to support multiple target groups and fixed issue where deregister was called multiple times. 
// **** First  issue was that target de register was called multiple time, and that was happening because there was 
//      iteration trough all attachments, and we should only filter attachment which has type = `eni` where details 
//      about subnet and ip are.
// **** Second issue was that original code was not working when you have multiple target groups in load balancer, 
//      as in my case, where i have multiple target groups, for api traffic and for management traffic where application
//      health status and info is. I refactored code to use array of target groups.

https://gist.github.com/git-josip/7d4343d4ba3d9e06463a20785da2743f

**Comment by jicowan** [comment]
Is your task part of multiple TGs? Is it exposed on multiple ports?  GetTargetGroups is supposed to get the TG that the task belongs to.

**Comment by git-josip** [comment]
@jicowan yes. my task has multiple ports exposed.
- 8080
- 8081

**Comment by jicowan** [comment]
I don't quite understand the reason for this code: 
https://gist.github.com/git-josip/7d4343d4ba3d9e06463a20785da2743f#file-deregister_target-go-L109-L111
All Fargate tasks have an ENI, no?

**Comment by git-josip** [comment]
@jicowan When I was testing your code I've noticed that my tasks deregister was called multiple times.
That is because there is iteration trough `for _, attachment := range e.Detail.Attachments`
https://gist.github.com/git-josip/7d4343d4ba3d9e06463a20785da2743f#file-deregister_target-go-L108

I've received  event with 3 attachments . 
So deregister was called for each attachment and it should only for one. 

My attachments: 
```
 "attachments": [
      {
        "id": "13a15844-b794-4da2-92ed-4ba28640fc74",
        "type": "eni",
        "status": "ATTACHED",
        "details": [
          {
            "name": "subnetId",
            "value": "subnet-11111"
          },
          {
            "name": "networkInterfaceId",
            "value": "eni-22222"
          },
          {
            "name": "macAddress",
            "value": "0a:d4:a2:12:4c:fc"
          },
          {
            "name": "privateDnsName",
            "value": "ip-10.3.105.142.eu-central-1.compute.internal"
          },
          {
            "name": "privateIPv4Address",
            "value": "10.3.105.142"
          }
        ]
      },
      {
        "id": "7d729dde-68d9-42ad-a2fc-b60bf19a2e59",
        "type": "elb",
        "status": "ATTACHED"
      },
      {
        "id": "c75b5819-ebc3-437d-b590-6e379afaee0c",
        "type": "elb",
        "status": "ATTACHED"
     }
]
```

**Comment by jicowan** [comment]
That's weird. It should loop through the attachments.  I don't know why it would invoke the function multiple times unless there's more than 1 event.

**Comment by git-josip** [comment]
@jicowan it is because deregister task is inside for loop which is iterating trough all attachments.
https://gist.github.com/jicowan/ad5e13d12577b41a22f83ed91a3e61bf#file-main-go-L99

So for every attachment it is called. 
and `privateIPv4Address` and `subnetid` variables are set when attachment is of type `eni` and those variables stay populated even for attachments that are not `eni`. 
- https://gist.github.com/jicowan/ad5e13d12577b41a22f83ed91a3e61bf#file-main-go-L89
- https://gist.github.com/jicowan/ad5e13d12577b41a22f83ed91a3e61bf#file-main-go-L92

**Comment by jicowan** [comment]
Thanks for the explanation. I understand why the deregisterTargets func gets called multiple times, but I'm still not sure why the **lambda function** gets invoked multiple times.  I guess I need to read up on Lambda.

**Comment by git-josip** [comment]
@jicowan lambda is invoked only once, at least on my side. misunderstanding.

**Comment by willronchetti** [comment]
Any updates on this request? Experiencing this issue as well. As stated previously Target Group de-registration should happen automatically when Fargate Spot tasks are associated with a Target Group and are sent a spot termination event. Am fine with porting the above solution but if there is an update forthcoming would rather wait.

**Comment by dajulia3** [comment]
This is preventing us from using fargate spot more broadly in our organization. Seems like it's a table stakes feature for many use cases.

**Comment by lncknight** [comment]
> > @toredash thanks for the reply. fyi unless i'm missing something you no longer have to do that for EC2 Spot Terminations, it should be taken care of automatically by _Automated Draining for Spot Instances_, correct? it's working well for us.
> 
> That is correct, but we don't use that feature as we have built our own logic to reduce the chances of downtime. Our solution is based on CloudWatch Events, were we listen to Spot Termination signal, and trigger a lambda. Said lambda will check if the EC2 node is part of an ECS Cluster _and_ ASG. If yes, it will label the EC2 node as unhealthy in the ASG at once, so that the ASG will request a new spot instance at once. Then it will drain the node as normal. With this we have new capacity ready before the terminating spot instance is reclaimed by AWS.
> 
> > this type of thing is more what i'm asking about - the cw event > manual draining solution was used by many people for EC2 before it was automated by AWS so users didn't have to deal with the extra automation, make sure it works, monitor the additional automation, etc etc.
> 
> True, but we continue with our own approach because of what I've written abov.e
> 
> > if AWS is planning on doing the same Automated Connection Draining for Fargate Spot i don't want to waste time with the extra automation if we can just wait a few months as moving to Fargate Spot isn't a huge priority for us.
> 
> I have no idea if they intend to, my building this into the container should not be that difficult, but that of course depends on your application.

When requesting a new spot from Lambda, make sure the original instance not terminated immediately as long as the new spot healthy. There are two minutes for buffer (termination notive period)

**Comment by git-josip** [comment]
Hi @jicowan , 

I have this lambda running on production and I have experienced strange behaviour. 
I get event when my FARGATE_SPOT task is being terminated, but I never receive `Detail.StopCode == "TerminationNotice"`, actually there is no stopCode at all, I have only `stopReason` . 

I do not get other evens before, and I log every event with this rule from EventBridge: 
```
{
  "source": ["aws.ecs"],
  "detail-type": ["ECS Task State Change"]
}
```

this is even I receive: 

```
{
  "version": "0",
  "id": "78a67cf9-6fd4-41de-761b-9bfa5f45e968",
  "detail-type": "ECS Task State Change",
  "source": "aws.ecs",
  "account": "740150495327",
  "time": "2021-11-18T14:13:23Z",
  "region": "eu-central-1",
  "resources": [
    "arn:aws:ecs:eu-central-1:740150495327:task/prod-cluster/bc095e4facf74b8b91c0db5ba3e8bf10"
  ],
  "detail": {
    "clusterArn": "arn:aws:ecs:eu-central-1:740150495327:cluster/prod-cluster",
    "containers": [
      {
        "containerArn": "arn:aws:ecs:eu-central-1:740150495327:container/prod-cluster/bc095e4facf74b8b91c0db5ba3e8bf10/7f9efa07-902b-4079-96d2-45cb93f14ce8",
        "lastStatus": "RUNNING",
        "name": "myo-core-container-prod",
        "taskArn": "arn:aws:ecs:eu-central-1:740150495327:task/prod-cluster/bc095e4facf74b8b91c0db5ba3e8bf10",
        "networkInterfaces": [
          {
            "attachmentId": "ba731d36-1598-4f83-b465-a3d50dd1ca10",
            "privateIpv4Address": "100.3.117.70"
          }
        ],
        "cpu": "0"
      }
    ],
    "createdAt": "2021-11-15T23:08:54.832Z",
    "launchType": "FARGATE",
    "cpu": "2048",
    "memory": "4096",
    "desiredStatus": "STOPPED",
    "group": "service:myo-core-service-prod",
    "lastStatus": "DEACTIVATING",
    "overrides": {
      "containerOverrides": [
        {
          "name": "myo-core-container-prod"
        }
      ]
    },
    "attachments": [
      {
        "id": "6f3aa01c-0786-4a10-9468-efbea6c4f848",
        "type": "elb",
        "status": "ATTACHED"
      },
      {
        "id": "ba731d36-1598-4f83-b465-a3d50dd1ca10",
        "type": "eni",
        "status": "ATTACHED",
        "details": [
          {
            "name": "subnetId",
            "value": "subnet-0fe520cdd04196b90"
          },
          {
            "name": "networkInterfaceId",
            "value": "eni-04dbf86ad96b261a2"
          },
          {
            "name": "macAddress",
            "value": "0a:4d:59:28:a6:ae"
          },
          {
            "name": "privateDnsName",
            "value": "ip-100-3-117-70.eu-central-1.compute.internal"
          },
          {
            "name": "privateIPv4Address",
            "value": "100.3.117.70"
          }
        ]
      },
      {
        "id": "e2465cd2-9496-4900-a420-1fb59208177c",
        "type": "elb",
        "status": "ATTACHED"
      }
    ],
    "connectivity": "CONNECTED",
    "connectivityAt": "2021-11-15T23:08:58.236Z",
    "pullStartedAt": "2021-11-15T23:09:19.035Z",
    "startedAt": "2021-11-15T23:10:27.583Z",
    "startedBy": "ecs-svc/6522240927423895723",
    "stoppingAt": "2021-11-18T14:13:23.683Z",
    "pullStoppedAt": "2021-11-15T23:09:52.079Z",
    "stoppedReason": "Your Spot Task was interrupted.",
    "updatedAt": "2021-11-18T14:13:23.683Z",
    "taskArn": "arn:aws:ecs:eu-central-1:740150495327:task/prod-cluster/bc095e4facf74b8b91c0db5ba3e8bf10",
    "taskDefinitionArn": "arn:aws:ecs:eu-central-1:740150495327:task-definition/myo-core-task-prod:23",
    "version": 5,
    "platformVersion": "1.4.0"
  }
}
```

**Comment by jicowan** [comment]
Try this, https://github.com/aws-samples/ecs-fargate-drain-function, instead.
[https://opengraph.githubassets.com/5dc83f374887b5786171a86c7009c78408f87ed3795606a7d84aa171db896d0a/aws-samples/ecs-fargate-drain-function]<https://github.com/aws-samples/ecs-fargate-drain-function>
GitHub - aws-samples/ecs-fargate-drain-function<https://github.com/aws-samples/ecs-fargate-drain-function>
Launching Visual Studio Code. Your codespace will open once ready. There was a problem preparing your codespace, please try again.
github.com

________________________________

**Comment by git-josip** [comment]
HI @jicowan , 

there is no issue in deregister function. 
I am just saying, in your function and in AWS Documentation is mentioned that event with contain `detail.stopCode == "TerminationNotice"` but there is no `stopCode` in my event, if you take a look into my previous post. 

In both of these AWS posts it is mentioned there will be `detail.stopCode == "TerminationNotice"`  and also in lambda code that is one of conditions. 
- https://aws.amazon.com/blogs/containers/graceful-shutdowns-with-ecs/
- https://aws.amazon.com/blogs/compute/deep-dive-into-fargate-spot-to-run-your-ecs-tasks-for-up-to-70-less/

**Comment by jicowan** [comment]
Ah, I see. I'll have to investigate whether the event schema changed recently.
________________________________

**Comment by git-josip** [comment]
@jicowan thank for quick response. 
I have found event schema 
at: https://eu-central-1.console.aws.amazon.com/events/home?region=eu-central-1#/registries/aws.events/schemas/aws.ecs%40ECSTaskStateChange/version/1

I can see there is property `stopCode` which is not required, but for some reason it is not populated in my event that is received.

**Comment by jicowan** [comment]
@git-josip I have confirmed that the schema has not changed. If possible, could you open a support ticket with AWS and ask them to look at the event that gets triggered when the task is interrupted?

**Comment by git-josip** [comment]
@jicowan I've already got answer from AWS support team. 
It is the issue on their side and there is no guarantee that `stopCode` will come. 
We should not use it and only field that can be used is `stopReason: "Your Spot Task was interrupted"` 

I will modify deregister function to handle just `stopReason`. Multiple events comes with `stopReason: "Your Spot Task was interrupted"` and only some on those which are still in RUNNING/DEACTIVATING state can be deregistered. 

Answer from AWS support team: 
```
Please note that this is a known issue/bug and according to the internal team  
the 'stopCode' can be empty when 'stopReason' is 'Your Spot Task was interrupted'. 
Moving forward the team has informed that for handling FARGATE_SPOT termination, 
the 'stoppedReason' should only be used instead of 'stopCode'.

I would also like to inform you that our internal team agreed that this indeed contradicts the AWS 
documentation and the team is working internally to make the necessary changes to the documentation. 
Unfortunately, I'll not be able to provide an ETA when it would be reflected. 
```

**Comment by git-josip** [comment]
@jicowan I've managed not to make it work. 
I am not looking anymore stopCode as that field is not coming. I've reported issue about missing stopCode or atleast to update documentation to reflect it. 

Also I've found one more bug in your lambda code, 
I have fixed it here in my repo for registering lambda and eventBridge via terraform. 
- https://github.com/git-josip/terraform-fargate-spot-targatet-drain

Issue was that you've used `break` keyword when iterating trough `Detail.Attachments` and it should be `continue` as `eni` attachment does not need to be first, `break` exits iteration and `continue` just goes to nex item in array. 

https://github.com/git-josip/terraform-fargate-spot-targatet-drain/blob/master/deregister_target.go#L103

**Comment by jicowan** [comment]
Thanks, I've replaced break with continue in my code too. If you send me the ticket number of the support ticket you created, I will follow up with the engineers. You can send it to me directly at ***@***.***
________________________________

**Comment by dbaggott** [comment]
@git-josip @jicowan

During your development did you come across an an easy way to simulate a CW fargate_spot task termination event?  I want to test an image-based version of the lambda without waiting for a task to naturally be reclaimed.

My only idea is to manually construct the event json and test the lambda but constructing all of the event properties correctly seems somewhat daunting.

Any suggestions?

**Comment by git-josip** [comment]
@dbaggott I did not know how to test it as well, but I now have some production events maybe when this occurred. I will try to find those and give you event json which then you can use it for tests. If that works for you.

**Comment by dbaggott** [comment]
@git-josip, thank you, I appreciate the help.  Also, your terraform made my life a lot easier -- thank you!

**Comment by dbaggott** [comment]
In case it helps someone, I managed to simulate an event using the following (set the three variables at the top as appropriate for your case):

```
AWS_ACCOUNT=1234567890
AWS_REGION="us-east-1"
TASK_ARN="arn:aws:ecs:${AWS_REGION}:${AWS_ACCOUNT}:task/default/XXXXXXXXXXXXXXXXXXXXXXX"

DETAIL_JSON=$(aws ecs describe-tasks  --tasks ${TASK_ARN} | jq '.tasks[0] | . + {"stoppedReason": "Your Spot Task was interrupted.", "stopCode": "TerminationNotice"}')

TERMINATION_EVENT=$(cat << EOF
{
  "version": "0",
  "id": "3317b2af-7005-947d-b652-f55e762e571a",
  "detail-type": "ECS Task State Change",
  "source": "aws.ecs",
  "account": "${AWS_ACCOUNT}",
  "time": "2020-01-23T17:57:58Z",
  "region": "${AWS_REGION}",
  "resources": [
    "arn:aws:ecs:us-east-1:280272993626:task/default/644a5d4b0ab34411b04e6825620b3707"
  ],
  "detail": ${DETAIL_JSON}
}
EOF
)

# According to https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs_cwe_events.html the attachment type 
# would be "eni" but describe-tasks uses "ElasticNetworkInterface".  The lambda go code does a check for "eni" so I'm
# assuming that's correct and do the replacement
echo $TERMINATION_EVENT | sed 's/ElasticNetworkInterface/eni/g' | pbcopy
```

**Comment by git-josip** [comment]
@dbaggott this is full event example I get in real scenario: 

```
{
    "version": "0",
    "id": "3f31ea7c-dcad-11ec-9d64-0242ac120002",
    "detail-type": "ECS Task State Change",
    "source": "aws.ecs",
    "account": "1122334455",
    "time": "2022-05-19T03:39:58Z",
    "region": "eu-central-1",
    "resources": [
        "arn:aws:ecs:eu-central-1:1122334455:task/dev-cluster/123456cf4911234560a97bcc68123456"
    ],
    "detail": {
        "clusterArn": "arn:aws:ecs:eu-central-1:1122334455:cluster/dev-cluster",
        "containers": [
            {
                "containerArn": "arn:aws:ecs:eu-central-1:1122334455:container/dev-cluster/123456cf4911234560a97bcc68123456/3f31ecd4-dcad-11ec-9d64-0242ac120002",
                "lastStatus": "RUNNING",
                "name": "mycompany-audit-log-container-dev",
                "taskArn": "arn:aws:ecs:eu-central-1:1122334455:task/dev-cluster/123456cf4911234560a97bcc68123456",
                "networkInterfaces": [
                    {
                        "attachmentId": "3f31ee50-dcad-11ec-9d64-0242ac120002",
                        "privateIpv4Address": "50.66.77.88"
                    }
                ],
                "cpu": "0"
            }
        ],
        "createdAt": "2022-05-12T20:26:20.817Z",
        "launchType": "FARGATE",
        "cpu": "512",
        "memory": "1024",
        "desiredStatus": "STOPPED",
        "group": "service:mycompany-audit-log-service-dev",
        "lastStatus": "DEACTIVATING",
        "overrides": {
            "containerOverrides": [
                {
                    "name": "mycompany-audit-log-container-dev"
                }
            ]
        },
        "attachments": [
            {
                "id": "3f31f256-dcad-11ec-9d64-0242ac120002",
                "type": "elb",
                "status": "ATTACHED"
            },
            {
                "id": "3f31f3d2-dcad-11ec-9d64-0242ac120002",
                "type": "elb",
                "status": "ATTACHED"
            },
            {
                "id": "3f31f54e-dcad-11ec-9d64-0242ac120002",
                "type": "eni",
                "status": "ATTACHED",
                "details": [
                    {
                        "name": "subnetId",
                        "value": "subnet-0242ac120002"
                    },
                    {
                        "name": "networkInterfaceId",
                        "value": "eni-0242ac120003"
                    },
                    {
                        "name": "macAddress",
                        "value": "02:cc:44:88:dd:ee"
                    },
                    {
                        "name": "privateDnsName",
                        "value": "ip-50-66-77-88.eu-central-1.compute.internal"
                    },
                    {
                        "name": "privateIPv4Address",
                        "value": "50.66.77.88"
                    }
                ]
            }
        ],
        "connectivity": "CONNECTED",
        "connectivityAt": "2022-05-12T20:26:24.598Z",
        "pullStartedAt": "2022-05-12T20:26:56.928Z",
        "startedAt": "2022-05-12T20:27:24.306Z",
        "startedBy": "ecs-svc/888123456789032",
        "stoppingAt": "2022-05-19T03:39:58.442Z",
        "pullStoppedAt": "2022-05-12T20:27:11.013Z",
        "stoppedReason": "Your Spot Task was interrupted.",
        "updatedAt": "2022-05-19T03:39:58.442Z",
        "taskArn": "arn:aws:ecs:eu-central-1:1122334455:task/dev-cluster/123456cf4911234560a97bcc68123456",
        "taskDefinitionArn": "arn:aws:ecs:eu-central-1:1122334455:task-definition/mycompany-audit-log-task-dev:331",
        "version": 5,
        "platformVersion": "1.4.0"
    }
}
```

**Comment by dbaggott** [comment]
@git-josip -- thank you!

**Comment by clavinjune** [comment]
> Note: with regard to testing the lambda, this event will trigger the draining but the task is not actually killed since this is just a simulation...
I've tried this same method on my service and it works last week. The deregistered task was stopped with `stoppedReason: task remained in deregistered state for too long`. But after I retry it earlier, the target group re-registered the task (because it's healthy and wasn't stopped), I think it'll be an issue if the `stopTimeout` on container definition is greater than the `Deregistration delay` on target group 🤔 . Any Idea? @git-josip @jicowan

**Comment by jicowan** [comment]
I think there may be a sample in the node termination handler repository.
-J
________________________________

**Comment by corddyla** [comment]
We (Amazon ECS team) have launched a set of improvements to load balancing on ECS. Amazon ECS now more accurately routes traffic to running tasks as tasks will be deregistered from the ELB before they enter a stopped state. Furthermore, with these improvements, Amazon ECS also helps your services running on the Fargate Spot capacity provider be more resilient to Spot termination notices.

https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-elastic-container-service-accuracy-service-load-balancing/

Thanks,

Amazon ECS team

**Comment by chiawendt** [comment]
> ... Amazon ECS now more accurately routes traffic to running tasks as tasks will be deregistered from the ELB before they enter a stopped state
https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-elastic-container-service-accuracy-service-load-balancing/

The post in link has been removed, is this improvement still effective?
