### ISSUE TITLE
[EKS] [request]: Ability to Use one ALB Across Multiple Ingress Objects

### ISSUE THREAD

**Issue by aliabas7** [aws/containers-roadmap#847]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
To have an option to reuse an ALB for multiple Ingress via annotation 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently ALB ingress controller creates an ALB for each ingress object, which can be costly. There are a couple of issues open for the same on other repos i.e. [688](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/688#issue-372901715) and [298](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/298#issue-287585717)

**Are you currently working around this issue?**
Using NLB with nginx-ingress, however, NLB doesn't support WAF, which is the use case.

**Comment by yanivpaz** [comment]
is there ETA for this feature ?

**Comment by rajeshwrn** [comment]
I was came across the same kind of requirement.

Have to deploy 20+ services in kubernetes in AWS Fargate profile. Since the fargate is not support NLB as of now the only option is ALB. But each deployment created new Alb. This needs 20+ public ips and also more cost on alb.

I achieved the solution with two ingress controller, alb ingress and nginx ingress.

Nginx will be the target for alb with port 80. And application services running in cluster with different port and namespaces will communicate nginx.

I have documented my solution. I think it will help your requirement.

https://github.com/rajeshwrn/alb-nginx-controller

**Comment by mikestef9** [comment]
You can now share a single ALB across multiple Kubernetes ingress objects! This controller release includes a number of other enhancements as well, such as support for fully private EKS clusters. See links below for more details.

- [What's New](https://aws.amazon.com/about-aws/whats-new/2020/10/introducing-aws-load-balancer-controller/)
- [Launch Blog](https://aws.amazon.com/blogs/containers/introducing-aws-load-balancer-controller/)
- [Documentation](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html)
