### ISSUE TITLE
issues with ec2 optimised linux ami-0b5225210a12d9951

### ISSUE THREAD

**Issue by steven-cuthill-otm** [aws/containers-roadmap#85]
When running security scan on the "amazon/amzn2-ami-ecs-hvm-2.0.20181112-x86_64-ebs" AMI we are hitting an issue due to 'left over' docker build artifices that we are not able to clean up or remove safely during our customisation  

for example 

`df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser`
`df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -4000`

`"stderr": "find: '/var/lib/docker/overlay2/de3743f9f6ac567b34697332c7ceabdceb18a2016c4a422854b2111042c32d95/merged': No such file or directory\nfind: '/var/lib/docker/containers/1017f985e52936f2f8c1fc6eb2c01fb13ba3ef17465d06cf05fdae7422a645ec/mounts/shm': No such file or directory", "stderr_lines": ["find: '/var/lib/docker/overlay2/de3743f9f6ac567b34697332c7ceabdceb18a2016c4a422854b2111042c32d95/merged': No such file or directory", "find: '/var/lib/docker/containers/1017f985e52936f2f8c1fc6eb2c01fb13ba3ef17465d06cf05fdae7422a645ec/mounts/shm': No such file or directory"]`

when trying to remove the dir we get the error `rm: cannot remove '/var/lib/docker/XXXXX': Device or resource busy` 

i believe before the image is published steps need to be taken to makesure the follow dir are asset free. 

/var/lib/docker/overlay2
/var/lib/docker/overlay
/var/lib/docker/containers

**Comment by samuelkarp** [comment]
Hello!

The directories that you're seeing are not part of the AMI's disk image (i.e., they're not baked into the AMI) but are rather caused by the default startup behavior.  The ECS-optimized AMI is configured to start the ECS agent on boot, which is started as a Docker container.  Those directories that you're seeing are part of how Docker operates; they contain state for the running containers (things like the container root filesystem, container logs, and various metadata).

To get rid of them, you can either run `sudo systemctl stop ecs.service` and `docker rm ecs-agent` to stop and remove the ECS agent container, or you can disable the `ecs.service` systemd unit in your user-data.
