### ISSUE TITLE
(EKS/Fargate) New EKS region for Milan and Cape Town and Northern California

### ISSUE THREAD

**Issue by DJ-Lakewood** [aws/containers-roadmap#949]
I think they all need eks for games to play lower latency as you said eks is a critical component for each server

**Comment by DavidHutchinson01** [comment]
100% Agree with this

**Comment by mikestef9** [comment]
Closing as duplicate. Tracked in #848 #890 #119

**Comment by Yudhistir58** [comment]
Hi there, My apologies for a comment that is of no help to any development. I am from South Africa, I would just like to know if it is possible for us to get EKS in Cape Town anytime soon, or is it a major issue that will take a long time. I guess since it has been 2 months that we have AWS in the country we were all excited for game servers and we don't have any insight at all as to whether we should keep waiting for it soon if it is not possible anytime soon. Just to have an idea would be nice.

I apologize again for any inconvenience caused. Thank you in advance :)
