### ISSUE TITLE
EKS : Consider LTS versions on EKS

### ISSUE THREAD

**Issue by kidanekal** [aws/containers-roadmap#993]
AWS EKS provides us a great comfort managing the control plain for our kubernetes cluster but at the same time, it is forcing us to make a frequent upgrade on kubernetes version. This may not be ideal for critical production clusters. If you see kubernetes 1.16 it got a lot of breaking changes and not compatible with previous k8s api's.

I'm asking the EKS team to consider LTS version on EKS/Kubernetes for customers to be on a version for at least 1 year.

LTS version is a standard practice and it prevents developer cycle doing multiple upgrades every few months for a feature we don't need/want.

**Comment by roarhard** [comment]
As much I like to upgrade frequency, it isn't easy in a large production setup. I like the idea of the LTS version, where the user takes the responsibility of the security posture instead of forcing the user to perform mandatory upgrades.

**Comment by pieterza** [comment]
+1

**Comment by tabern** [comment]
EKS [now supports 4 versions of Kubernetes (with a possible 5th in depreciation) at all times](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html). This means that we support each version for at least 12 months + an additional 2 months of deprecation. This is in line with the Kubernetes project increasing its support from 3 to 4 versions. 

Because we must remain upstream conformant and keeping pace with community Kubernetes releases is critical to maintaining security for EKS clusters, we will continue to follow the community release cycle and support model into the future.

Closing this ticket as the original ask for 1 year of support is shipped 🚢  and we do not plan to increase our support windows beyond this time frame without upstream community support in the future.
